### ISSUE TITLE
addEventListener not supported by IE < 9

### ISSUE THREAD

**Issue by eNepper** [nikhilk/scriptsharp#1]

**Comment by nikhilk** [comment]
I debated whether to add attach/detachEvent ...

Most people are using a wrapper that looks up existence of addEventListener and attachEvent. Either its something like jQuery, or a custom wrapper. jQuery is supported out of the box, and for a custom wrapper, one would write both the wrapper and import definition.

At the same time, if you are authoring for a specific target environment, eg. mobile webkit, you can skip the wrapper and just use addEventListener.

Given that only addEventListener is on Element.

Thoughts? Should AttachEvent also be there, and show up on every element, even though anyone using it directly is probably better served by writing a wrapper?

**Comment by eNepper** [comment]
So if I understand this right I can't use ScriptSharp to write a custom wrapper?

**Comment by nikhilk** [comment]
You could still use script# to create the wrapper if you want to:

Script.Literal("{0}.attachEvent('{1}', {2})", theElement, theEventName, theEventHandler);

**Comment by eNepper** [comment]
Thanks for pointing me in the right direction
