### ISSUE TITLE
foreign characters

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#101]
Apparently, foreign character are encoded by scriptsharp. But in my case it does not produce the desired result:

I have the following : 

Script.Alert("één");

this results in javascript

alert('\ufffd\ufffdn');

when view this in the browser, \uffd shows up as a diamond with a questionmark inside...

**Comment by nikhilk** [comment]
Was your input c# file saved in UTF8 encoding?
When I make sure the c# code is itself saved in UTF8 form, the following script is generated instead (which seems right to me):

```
alert('\u00e9\u00e9n');
```

**Comment by rekna1** [comment]
I changed encoding to UTF, and this seems to solve the issue... VS2010 seems to create cs files by default in another encoding... is this something that can be changed on the solution or project level or some setting in vs?

**Comment by nikhilk** [comment]
VS does have a setting if you go in the text editor settings to detect UTF8 encoding without the UTF8 signature. Not sure if it helps. However your question might be better answered on a VS forum...
