### ISSUE TITLE
'as' casting on delegate not working.

### ISSUE THREAD

**Issue by noamberda** [nikhilk/scriptsharp#103]
Hi,
I am having a delegate that i save into a dictionary. later i would like to cast it back to before invoking it. the cast operation fail with the following error.
Message: Unable to get value of the property 'isInstanceOfType': object is null or undefined
Line: 1283
Char: 5
Code: 0
...ClientScript/mscorlib.debug.js

The script that is generated:
Type.safeCast(userData['DELEGATE'], XXXXX.ClientScript.jsClient.Function

(The UserData is the dictionary)

Noam

**Comment by nikhilk** [comment]
Which version of the compiler are you using?

In 0.7.3 a check for is/as on a delegate type should end up generating script that checks for whether the value is a Function.

**Comment by noamberda** [comment]
i am using 0.7.3

**Comment by noamberda** [comment]
I have looked again into the code. 
it looks like all delegates are from type, XXXX.ClientScript.jsClient.Function. but this type is never defined within the js.

the error is that the type within the safeCast method is null as the .Finction is not defined.
Type.safeCast = function Type$safeCast(instance, type) {
    if (type.isInstanceOfType(instance)) {
        return instance;
    }
    return null;
}

**Comment by nikhilk** [comment]
Fix included in 0.7.4.0
