### ISSUE TITLE
Compiler - Expression expected

### ISSUE THREAD

**Issue by jimmygilles** [nikhilk/scriptsharp#104]
Hello,

The following code does not compile. :-(

``` C#
using System.Runtime.CompilerServices;

namespace Test
{
    public sealed class Queue<T>
    {
        public T Dequeue()
        {
            return default(T);
        }
    }
}
```

I have two errors:
- "expression expected - line 10 - col 21"
- "Expression statement must do work - line 10 - col 29"

Thank you.

**Comment by nikhilk** [comment]
First a generic Queue class already exists in mscorlib, so not sure why you are defining one as well.

Second, this is a dup of issue #44 - which is about defining generic types not being supported. You can only consume generic types defined in an import library (eg. mscorlib).
