### ISSUE TITLE
Unrecognized preprocessor directive stripped out in the .script file

### ISSUE THREAD

**Issue by sejerpz** [nikhilk/scriptsharp#108]
The ScriptSharp preprocessor stripts out all the unrecognized preprocessor directives.

Or in another words: how can I include this snippet in the .script file and get it copied verbatim in the generated javascript source?

/*
# asset(custom/*)

*/ 

...

**Comment by nikhilk** [comment]
All comments are stripped out ... so everything within /\* and */ are going to be stripped out by design.
The way to include a comment is to use //! for a single line comment.

What are you trying to do? If you're trying to include something, you can use #include.

**Comment by sejerpz** [comment]
I tried with //! syntax and indeed the line is copied verbatim to the output, but it's not enough.

I'm testing qooxdoo with script#, I wrote some minimal bindings and I need that comment to be included in the generated source file. The #asset directive is pre-processed by the qooxdoo generate.py script to include resources like icons etc..

Can I use #include to include another file? I yes I can try to put that comment in an external file.

**Comment by nikhilk** [comment]
You can try #include[as-is] and see if it works. Just #include will process the included content.

This approach sounds a bit different than what I'd imagine for this scenario - I'd expect a script framework (like qooxdoo in your case) to be included into the page through its own script/css reference, rather than being inlined into generated script file.

**Comment by sejerpz** [comment]
To be clear all this is pretty new for me (script#, javascript, qooxdoo, sproutcore etc...), but as I understood qooxdoo "pre-processor" (the generate.py script) when building sources produces a minimal JS script with just the used framework classes and assets to speed up the download.

FYI the #include[as-is] worked well :)

Thanks!
