### ISSUE TITLE
Sys.StringBuilder renamed to ss.StringBuilder?

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#109]
Sys.StringBuilder is getting renamed to ss.StringBuilder in the generated .js file - not .debug.js. 
Is this a bug in 0.7.3.0 or how do I stop this happening?

Thanks

Donal

**Comment by nikhilk** [comment]
Which assembly are you using? In mscorlib, StringBuilder is declared with an "ss" script namespace, so don't see how you'd get Sys to begin with. "Sys" used to come from the old msajax assemblies, which are no longer usable.

**Comment by dmcweeney** [comment]
Apologies I was looking at the wrong debug.js file - it is getting renamed to ss in both.

It is the the Sys.StringBuilder I am tring to use - is there a simple way to get to use this without having to create a stub class/dll? Maybe there is already one?

Thanks

Donal

**Comment by nikhilk** [comment]
Sys.StringBuilder is from msajax, which is no longer supported. You'll need to use mscorlib.dll and mscorlib.js, which happens to include a default and equivalent string builder implementation.

**Comment by dmcweeney** [comment]
Ok thanks - I got around this by creating a simple reference project with the Sys.Stringbuilder definition in it.

Thanks

Donal
