### ISSUE TITLE
Script# compilation symbol.

### ISSUE THREAD

**Issue by duckmaestro** [nikhilk/scriptsharp#11]
This is really very minor. I think it would it help in code sharing (both cross-"platform" and cross-team) if there were an official compilation symbol defined for Script# csproj's, for instance SCRIPT_SHARP. It appears that the csproj template already defines CODE_ANALYSIS by default, so my proposal would be to change the default to CODE_ANALYSIS;SCRIPT_SHARP or similar.

**Comment by nikhilk** [comment]
Fixed in v0.7.0.2.
The symbol I added to project templates is SCRIPTSHARP.
