### ISSUE TITLE
ApplicationCacheEvent enum scriptnames are incorrect

### ISSUE THREAD

**Issue by reneg** [nikhilk/scriptsharp#111]
The enum System.Html.Data.ApplicationCacheEvent has script names set for each value, but they are incorrectly prefixed with "on", like "onupdateready" for example.
When using this enum with System.Html.Data.ApplicationCache.AddEventListener, the resulting Javascript codes tries to register for the events with the "on" prefix, for example "onupdateready". But when using the function AddEventListener, one should not prefix the events with "on". Because of this error in the ApplicationCacheEvent enum, registering for Application Cache events with ApplicationCache.AddEventListener silently fails.

The solution is to remove the "on" prefix from all the ScriptName attributes in ApplicationCacheEvent.cs.

**Comment by nikhilk** [comment]
Fix included in 0.7.4.0
