### ISSUE TITLE
Window.ApplicationCache.Status.ToString() generates invalid JavaScript

### ISSUE THREAD

**Issue by Griffitsj** [nikhilk/scriptsharp#114]
compiled version of a call to the C# Window.ApplicationCache.Status.ToString() generates JavaScript which throws a Reference Error: ApplicationCacheStatus is not defined

The Following code:

<pre>
    public class Class1
    {
        public static void DoSomething()
        {
            Script.Alert(Window.ApplicationCache.Status.ToString());            
        }
    }
</pre>

generates the following JavaScript:

<pre>
ScriptLibrary1.Class1.doSomething = function ScriptLibrary1_Class1$doSomething() {
    alert(ApplicationCacheStatus.toString(window.applicationCache.status));
}
</pre>

**Comment by chenxustu1** [comment]
you can try it like this:
                Script.Alert((string)(object)Window.ApplicationCache.Status);

**Comment by Griffitsj** [comment]
That's good to know there's a workaround - thanks.  The problem only seems to occur with Enum's

**Comment by nikhilk** [comment]
Fixed in 0.7.4.0
