### ISSUE TITLE
Comparison against zero emits wrong JavaScript

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#116]
In Script# 0.7.3 and 0.7.4, and possibly earlier versions, comparisons against zero emit the wrong JavaScript.

This C# code:

``` c#
int? x = null;
if (x == 0) { }
```

Emits this JavaScript code:

``` javascript
var x = null;
if (!x) { }
```

Instead of the correct JavaScript code:

``` javascript
var x = null;
if (x === 0) { }
```

If the value being tested was a non-zero integer value like this:

``` c#
int? x = null;
if (x == 1) { }
```

Then the correct code is emitted:

``` javascript
var x = null;
if (x === 1) { }
```

This is a problem not only for nullable types, but also for code that accepts external input where the variable type may not be correct (such as an empty string being passed in where an integer is expected).

A similar problem also exists with != comparisons:

``` c#
int? x = null;
if (x != 0) { }
```

Results in this code:

``` javascript
var x = null;
if (!!x) { }
```

Which is at least consistent, since null is considered equal to zero in both cases.

The problem is worse in 0.7.4 now that constants and enums are inline.  In 0.7.3, constants and enums with a value of 0 would cause the correct comparison to be emitted.  Now that they are inline the incorrect comparison is emitted.

Comparisons in C# using == and != should emit === and !== respectively in JavaScript to avoid treating values like null as equal to zero.

**Comment by mattclay** [comment]
This is also a problem for bool comparisons.

C# code like this:

``` c#
bool? x = null;
if(x == false) {}
```

Results in this JavaScript:

``` javascript
var x = null;
if (!x) { }
```

Which results in null being considered equal to false.

**Comment by mattclay** [comment]
Here is another version of the same bool comparison problem noted above -- it produces the same JavaScript:

``` c#
bool? x = null;
if(!x.Value) {}
```

**Comment by robitar** [comment]
Agreed, I remember this was discussed in an earlier issue and changed. The strict equality operators should be favoured to truthy/falsy tests, the current output is almost never what I expect (or write in js by hand).

You end up having to explicitly test for null/undefined before the if to catch these corner cases.
