### ISSUE TITLE
DateTime class is missing in 0.7.4 Release

### ISSUE THREAD

**Issue by chandramuralis** [nikhilk/scriptsharp#119]
It seems System.DateTime class is removed in new version and it causing our application not to compile in new version.

**Comment by mattclay** [comment]
The 0.7.4 release changed from using the DateTime struct to a Date class.  The change was discussed on issue #67.

**Comment by nikhilk** [comment]
Updated history.txt and release notes to reflect this.

**Comment by chandramuralis** [comment]
Thanks
