### ISSUE TITLE
Enum named constants complied with strange name

### ISSUE THREAD

**Issue by noamberda** [nikhilk/scriptsharp#120]
Hi,
I am using GMapSharp and in the project they have number of enums.
one of the enum is GeocoderStatus. it has a named constant called:
/// <summary>

        /// No result was found for this GeocoderRequest.
        /// </summary>

        ZERO_RESULTS,

I am using it in the following way
if (GeocoderStatus.ZERO_RESULTS == status)

and somehow it complied the following way
if (google.maps.GeocoderStatus.zerO_RESULTS === status) {

so we have a problem as the javascript doesn't recognize this var.
if I change in the javascript to capital letters then its working fine.

Noam

**Comment by robitar** [comment]
I had a look at it: http://gmapsharp.codeplex.com/SourceControl/changeset/view/66760#1148349

If you add the [PreserveName] attribute to the members of the enum, it should work as expected. Perhaps a recent change in the compiler affected case transformation?

**Comment by noamberda** [comment]
[PreserveName] didn't work for me, I have used [ScriptName("ZERO_RESULTS")] and this did the trick. 
thanks for the direction.

**Comment by nikhilk** [comment]
Strange ... was this working before and stopped working recently? Or was it broken all along?
Also, I'd expect [PreserveCase] to work.

**Comment by noamberda** [comment]
I haven't used those enums until now. I have been using the GmapSharp for a while.

I am not sure why [PreserveCase] didn't work.

Noam 

-----Original Message-----

**Comment by nikhilk** [comment]
Also, I'd add it would be better if the chosen name was something like ZeroResults (to match c# naming conventions) and then use [ScriptName] to get desired javascript name.

**Comment by robitar** [comment]
Yes thats also what I would do, define the C# enum using normal names etc. Perhaps the bug happens because its a referenced library?
