### ISSUE TITLE
implicit operator Int32

### ISSUE THREAD

**Issue by lboshuizen** [nikhilk/scriptsharp#122]
In mscorlib 0.7.0.0 is an implicit operator System.Number defined.

This prohibits using the generated assembly as-is

is there a way to do this in another way?

**Comment by nikhilk** [comment]
Not sure what you mean by use the generated assembly "as-is" ... where? Are you trying to use a script# assembly as a regular .net assembly? That will not work... nor is it intended.

**Comment by lboshuizen** [comment]
No real intention to use it as "real" assembly in a production
environment.Although that would be convient from a DRY point of view.

But referencing it in a test project to unittest certain parts of the code
will save the tremendous time now spend in the debugger.

On Mon, Nov 14, 2011 at 2:22 AM, nikhilk <
reply@reply.github.com

**Comment by nikhilk** [comment]
One question that comes up is do you want to unit test the c# code or the generated script.

For the latter, script# supports writing Tests within a Tests namespace and subfolder, and generating a Foo.test.js alongside Foo.debug.js. The test classes and test methods are written in c#, and converted to script, as QUnit test modules and test methods. You can then optionally use a VS unit test project to run the tests by loading pages etc.

For the former, it is possible depending on your specific code to write it in a way such that it can be cross-compiled against the script# mscorlib as well as desktop mscorlib and then run the one compiled using the desktop mscorlib in a standard unit test. Whether you can do so or not depends on your code, its dependencies etc. This is certainly in the realm of interesting, but not gotten any time of the day or resources to try make it happen. To make it more supported, the following would need to happen (and would love to get help):
1. Find out where in script# mscorlib additional instance members have been added to types that correspond to existing types in desktop mscorlib. Those need to be available as extension methods when compiling code against desktop mscorlib.
2. Find out where similar static methods have been added. Those need to be moved into the Script class as opposed to static extensions on existing types.

**Comment by lboshuizen** [comment]
Unittest the c# code. Testing the generated script, from my point of view
the UI is different matter.

I as not aware of the QUnit test possibilities in S#. Release notes hinted
about adding support for it, not about the status an existing
implementation. Are there some docs about it?

By adding the extensions method you are basically trying to make the
mcscorlib member-compliant with the .Net versions. Makes sense. If you can
give me pointer (example) of how you want to accomplish it, I for sure can
lend a hand as it seems to be in both our interest :-)

On Wed, Nov 16, 2011 at 1:35 AM, nikhilk <
reply@reply.github.com
