### ISSUE TITLE
jQuery UI Library

### ISSUE THREAD

**Issue by briantoba** [nikhilk/scriptsharp#129]
Nikhil,

First, thank you very much for your effort with ScriptSharp.

I've started a wrapper for jQuery.UI in this github repo: git@github.com:briantoba/jQuery.UI-Script-Sharp.git

Do you know anybody else working on this? Can you help me, in any way, to get more developers eyes to see if I get a hand and finish this quickly?

Thanks!
Brian

**Comment by briantoba** [comment]
URL: https://github.com/briantoba/jQuery.UI-Script-Sharp

**Comment by nikhilk** [comment]
Awesome to hear... will spread the word once I get a chance in couple weeks.

**Comment by dealproc** [comment]
@briantoba any word on your progress with this?  Since I now see KnockoutJS support as well... if I may be able to contribute to the mapping for the rest of the jQueryUI stuff, and if someone finishes the KnockoutJS support for 2.0, that would help me immensely in a project I'm on.

**Comment by briantoba** [comment]
I really only needed a few modules mapped and stopped after that, feel free
to keep contributing to it, though!

**Comment by nikhilk** [comment]
Closing this in favor of #136.
