### ISSUE TITLE
Using namespace alias causes compile errorr

### ISSUE THREAD

**Issue by ghost** [nikhilk/scriptsharp#13]
In v0.7.0.0, Get the error "Check that your C# source compiles and that you are not using an usupported feature" at line new'ing Bar.B;

using Bar = Foo.Bar;
using B = Foo.Bar.B;

namespace ns
{
  class A
  {
    public void SomeMeth()
    {
      // this works
      Foo.Bar.B b1 = new Foo.Bar.B();
      // this works
      B b2 = new B();
      // this doesn't work
      Bar.B b = new Bar.B();
    }
  }
}

last pdf for v0.5.5.0 says on page 34:

In addition there are a known set of limitations in the current implementation that will hopefully be supported in future builds:

 You cannot specify namespaced-qualified type names either. As a workaround you can use aliases (eg. using Foo = SomeNamespace.SomeType;)

But I could specify namespace-qualified..

**Comment by nikhilk** [comment]
Not sure what makes the first line work, but this isn't a supported scenario right now.
