### ISSUE TITLE
delegate in ScriptSharp being incorrectly generated as function changing the scope of 'this' in javascript

### ISSUE THREAD

**Issue by globalscholar** [nikhilk/scriptsharp#131]
delegates in ScriptSharp are being incorrectly generated as functions instead of ss.Delegate.create even though there is a reference to a private instance variable.
For example, if we write this in a class and _CheckData is an instance variable, then the anonymous delegate should be emitted as ss.Delegate.Create instead of function. This creates problems during javascript binding to events(click, mousedown  etc), where 'this' is changed to the object on which the event happens instead of remaining the class in which the callback was defined.

//emits function in javascript
SomeCallback("SomeData", delegate
{
Util.Test(new string[] { _CheckData });
});

//emits ss.Delegate.create in javascript
SomeCallback("SomeData", delegate
{
 _CheckData = 1;
});

We are using Version: 0.7.3 with some bug fixes.

**Comment by rdeputat** [comment]
Have you found solution?

**Comment by nikhilk** [comment]
A temporary workaround would be use the local variable alternative suggested above and then reference the local variable in the string array initializer.
