### ISSUE TITLE
Imported class with overloaded methods and check that your source compiles error

### ISSUE THREAD

**Issue by volkanceylan** [nikhilk/scriptsharp#14]
When i define two overloaded functions like below in my imported script class (actually its a custom import of jQueryObject)

[Imported, IgnoreNamespace]
public class Query
{
    public Query html(string html) { return null; }
    public string html() { return null; }
    ...
}

And use it like
J.Query.select("#test").html("<a/>").children().attr("href", "#" + id)......

i get an error "Check that your C# source compiles and that you are not using an unsupported feature."

When i change parameterless method to "Html()" like below it works just fine.

```
public Query html(string html) { return null; }
[ScriptName("html")]
public string Html() { return null; }
```

**Comment by nikhilk** [comment]
Create an Import Library to define imported APIs that go beyond what the script# compiler supports (eg. overloads). An import library is basically a vanilla c# project. It doesn't get compiled by the script# compiler.

That said, I don't know why you don't just use the out-of-box jQuery assembly.

**Comment by volkanceylan** [comment]
Thanks, didn't think about it. 

Out-of-box jQuery assembly is great functionally but personally i don't like some naming conventions like GetData() and Data(), GetAttr() and Attr(). I prefer to name and use functions as they are exactly in jQuery. Also jQueryObject name is harder to get with intellisense without using arrow keys, prefer Query to it. And as also extension methods not supported yet, and having to write .Plugin<UiDialog>().dialog("close") to just close a dialog seems too long to me, and i add such common plugins to jQuery object itself. And some others :)
