### ISSUE TITLE
Bug when using properties qualified with namespace

### ISSUE THREAD

**Issue by alenas** [nikhilk/scriptsharp#143]
Hi,

I have a public static property like this:

namespace One {
  public static class Two {
    public static string Locale = "en-AU";
  }
}

and a class in a different file, but the same namespace that is using this property like this:
string Something = "locale" + Two.Locale;

but if I fully qualify that property with namespace, then compile fails (without error):
string Something = "locale" + One.Two.Locale;

was pretty hard to spot what was wrong with a code...

**Comment by jimmygilles** [comment]
Hello, this seams a duplicate of #102
