### ISSUE TITLE
Func missing signatures for 3-8 args

### ISSUE THREAD

**Issue by james-baker** [nikhilk/scriptsharp#146]
Using 0.7.4

My mscorlib.dll is providing 11 signature variations for declaring "Func"s.
They have 0, 1, 2 arg versions, then it jumps to 9, 10, 11, 12, 13, 14, 15, 16 arguments.

Where are the three-through-eight argument (plus TResult) versions?

The 9-16 signatures have in/out labeling and more help-tip text talking about Co/Contravariance.  Seems like they might come from a different place.  I know Func/Action have had a history where successive .NET versions added more signature variants... but if ScriptSharp is making up for the missing ones itself, why did it start at 9 and not 3?

**Comment by mattclay** [comment]
Are you sure you're using 0.7.4?

A fix for this was merged about 6 months ago, before the 0.7.3 release. See issue #82 for details.

**Comment by james-baker** [comment]
You are correct!  I was mistaken, and had not completed the 0.7.2 to 0.7.4 upgrade.  My apologies for the noise.
