### ISSUE TITLE
Function.createDelegate ?

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#148]
Hi,

Is it possible to generate the following code besides using Script.Literal?

var fn = Function.createDelegate(this, function( p0, p1) {
doRemoval("theid");
}
Sys.WebForms.PageRequestManager.getInstance().add_endRequest( fn ) ;

I've an import library build for the PageRequestManager - just cannot get the Function.createDelegate?

I did find somewhere that DomEventHandler may cover this but cannot find that anymore.

Thanks

Donal

**Comment by nikhilk** [comment]
Try something like this (writing from memory, so might be a bit off):

```
Action<type1, type2> fn = (Action<type1, type2>)delegate(type1 p0, type2 p0) { DoRemoval("theid"); }
```

Feel free to re-open if it doesn't work.

**Comment by dmcweeney** [comment]
Hi Nikhil,

Thanks for the quick response. The following is the way I got it working - posting in case someone else needs it or knows a better way.

public void TestMethod()
{
    string nid = "TheId";
    int outer = 234;

```
Action<string, string> x = (Action<string, string>) delegate( string p0, string p1 )
{
    Script.Alert( "nid = " + nid );
    int inner = outer + 2;
    Script.Alert( "inner = " + inner );
} ;

object z = Script.Literal( "Function.createDelegate( this, {0} ) ", (Action<string, string>) delegate( string p0, string p1 )
{
    Script.Alert( "nid = " + nid );
    int inner = outer + 2;
    Script.Alert( "inner = " + inner );
} );
```

}

testMethod: function ScriptLibrary074_Class1$testMethod() 
{
    var nid = 'TheId';
    var outer = 234;
    var x = function(p0, p1) {
            alert('nid = ' + nid);
            var inner = outer + 2;
            alert('inner = ' + inner);
        };
        var z = Function.createDelegate( this, function(p0, p1) {
    alert('nid = ' + nid);
    var inner = outer + 2;
    alert('inner = ' + inner);
} ) ;
    }

Thanks

Donal

**Comment by nikhilk** [comment]
Your delegate doesn't reference any member variables. Only local variables. Hence the compiler generates a simple function, rather than a delegate which remembers the context of the current object instance.

The simple function doesn't need to pay overhead of that extra object instance, and upon invocation, applying the function using that object instance.

Try referencing a member variable, and the compiler should generate a call to createDelegate.
