### ISSUE TITLE
pass a delegate without ss.Delegate.create?

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#149]
Hi,

Is it possible to pass a delegate without ss.Delegate.create getting generated.

eg. c#

pageRequestManager.add_endRequest( this.RemoveNotificationHandler ) ;

generates

pageRequestManager.add_endRequest(ss.Delegate.create(this, this._removeNotificationHandler$1))

Script.Literal( "pageRequestManager.add_endRequest( this.RemoveNotificationHandler )" );

generates

pageRequestManager.add_endRequest( this.RemoveNotificationHandler );

But then creates a renaming problem arises.

Thanks

Donal

**Comment by nikhilk** [comment]
No there isn't and it doesn't make sense.

When you want to pass a reference to this.RemoveNotificationHandler, you're passing a reference to a particular function, but you also want the function to be invoked in the context of "this" object. Delegate sets that up, whereas a simple function reference won't.

**Comment by dmcweeney** [comment]
Hi Nikhil,

I understand now - if I pass a reference to a static method or global method the syntax I am looking for will be generated.

Thanks

Donal
