### ISSUE TITLE
Can't build after installing .net 4.5

### ISSUE THREAD

**Issue by michaelaird** [nikhilk/scriptsharp#156]
It looks like they've added a bunch of classes to System that are missing from CoreLib...

**Comment by nikhilk** [comment]
Bit too vague.
- Any more detail of what?
- Also, are you using a .csproj based on the script# project template or calling csc.exe directly or using your own csproj? If latter, are you explicitly passing in /langversion:ISO-2?

**Comment by michaelaird** [comment]
Here's the errors i'm getting from building CoreLib in VS 2010:

------ Rebuild All started: Project: CoreLib, Configuration: Debug Any CPU ------
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\UInt64.cs(11,11): error CS0012: The type 'System.MulticastDelegate' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\UInt64.cs(11,11): error CS0012: The type 'System.IAsyncResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\UInt64.cs(11,11): error CS0012: The type 'System.AsyncCallback' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Runtime.Serialization.ISerializable' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Runtime.Serialization.IDeserializationCallback' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Collections.Generic.ISet`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Collections.Generic.ICollection`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Collections.Generic.IEnumerable`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Collections.IEnumerable' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Collections\Generic\Queue.cs(11,11): error CS0012: The type 'System.Collections.Generic.IEqualityComparer`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Runtime.cs(541,11): error CS0012: The type 'System.Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Runtime.cs(541,11): error CS0012: The type 'System.Collections.Generic.IList`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Runtime.cs(541,11): error CS0012: The type 'System.Collections.IList' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Runtime.cs(541,11): error CS0012: The type 'System.Collections.ICollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Runtime.cs(583,11): error CS0012: The type 'System.Reflection.EventInfo' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Diagnostics\Debug.cs(12,11): error CS0012: The type 'System.Diagnostics.TextWriterTraceListener' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Diagnostics\Debug.cs(12,11): error CS0012: The type 'System.Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Diagnostics\Debug.cs(12,11): error CS0012: The type 'System.Diagnostics.TraceEventCache' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
D:\Projects\scriptsharp-GITHUB\src\Libraries\CoreLib\Diagnostics\Debug.cs(12,11): error CS0012: The type 'System.Diagnostics.TraceEventType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Compile complete -- 20 errors, 0 warnings
Build started 03/03/2012 6:18:25 AM.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1591,0661,0660,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /doc:......\bin\Debug\mscorlib.xml /define:TRACE;DEBUG /errorendlocation /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Core.dll" /debug- /filealign:512 /keyfile:....\ScriptSharp.snk /optimize- /out:obj\Debug\mscorlib.dll /target:library /warnaserror+ /utf8output Collections\Generic\ListMapCallback.cs Collections\Generic\ListItemMapCallback.cs Collections\Generic\CompareCallback.cs Collections\Generic\ListItemKeyGenerator.cs Collections\Generic\ListItemCallback.cs Collections\Generic\ListCallback.cs Collections\Generic\ListItemFilterCallback.cs Collections\Generic\ListFilterCallback.cs Collections\Generic\ListAggregator.cs Collections\Generic\ListItemAggregator.cs Collections\Generic\ObservableCollection.cs Collections\Generic\Stack.cs Collections\Generic\Queue.cs Collections\Generic\Dictionary.cs Collections\Generic\KeyValuePair.cs Collections\Generic\ListGrouping.cs Collections\Generic\List.cs Collections\Generic\IReadonlyCollection.cs Collections\Generic\ICollection.cs Collections\Generic\IEnumerable.cs Collections\Generic\IEnumerator.cs Collections\ICollection.cs Collections\IReadonlyCollection.cs Collections\ObservableCollection.cs Callback.cs ComponentModel\IApplication.cs ComponentModel\IEventManager.cs ComponentModel\DependencyAttribute.cs ComponentModel\IInitializable.cs ComponentModel\IContainer.cs ComponentModel\ObserverManager.cs ComponentModel\IObserver.cs ComponentModel\Observable.cs Diagnostics\SyntaxValidationAttribute.cs Tuple.cs Nullable.cs Diagnostics\ConditionalAttribute.cs Diagnostics\SuppressMessageAttribute.cs Runtime.cs ScriptMetadata.cs Globalization\CultureInfo.cs Globalization\DateFormatInfo.cs Globalization\NumberFormatInfo.cs ScriptInfo.cs Serialization\JsonStringifyCallback.cs Serialization\JsonParseCallback.cs Serialization\Json.cs Array.cs Collections\ArrayAggregator.cs Collections\ArrayCallback.cs Collections\ArrayFilterCallback.cs Collections\ArrayGrouping.cs Collections\ArrayItemAggregator.cs Collections\ArrayItemCallback.cs Collections\ArrayItemFilterCallback.cs Collections\ArrayItemKeyGenerator.cs Collections\ArrayItemMapCallback.cs Collections\ArrayList.cs Collections\ArrayMapCallback.cs Boolean.cs Byte.cs CancelEventArgs.cs Char.cs CompareCallback.cs Arguments.cs Action.cs Testing\Assert.cs Func.cs Record.cs Date.cs Diagnostics\Debug.cs Decimal.cs Delegate.cs Collections\Dictionary.cs Collections\DictionaryEntry.cs Double.cs Enum.cs EventArgs.cs EventHandler.cs Exception.cs Function.cs IDisposable.cs Collections\IEnumerable.cs Collections\IEnumerator.cs Int16.cs Int32.cs Int64.cs Math.cs Number.cs Object.cs Collections\Queue.cs RegularExpression.cs SByte.cs Script.cs Single.cs Collections\Stack.cs String.cs StringBuilder.cs StringReplaceCallback.cs Type.cs UInt16.cs UInt32.cs UInt64.cs Void.cs Properties\AssemblyInfo.cs ....\ScriptSharp.cs Testing\TestEngine.cs Testing\TestClass.cs "C:\Users\michael.DOM\AppData\Local\Temp.NETFramework,Version=v4.0.AssemblyAttributes.cs"

Build FAILED.

Time Elapsed 00:00:00.14
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I'll see if i can submit a patch later today.

**Comment by michaelaird** [comment]
I was able to get this to build again by changing the Target Framework to 2.0 instead of 4.0. Is that an appropriate fix? or could that cause problems elsewhere?

**Comment by nikhilk** [comment]
That seems like a reasonable fix that requires project file to be updated.
The couple of things I wonder:
- I would have thought the existing 4.0 target framework would not have been affected, and these new mscorlib requirements would only show up post 4.0.
- Its non-obvious what the implications are, but hopefully this won't regress something else.
- Does this fix need to be applied to the project templates, i.e. for all script# projects, and not just the sources for building mscorlib?

**Comment by michaelaird** [comment]
Unfortuately, it looks like .net 4.5 is another .net 3/3.5 where they patched the CLR in place and added new requirements to mscorlib. i tried to implement some of the missing classes in Runtime.cs but then I got an error like this:

error CS0520: Predefined type 'System.AsyncCallback' is declared incorrectly

Do you know if there's documentation on how these things need to be declared?

Changing the target framework to 2.0 for CoreLib worked and I was able to compile the other reference libraries without changing the target framework.
