### ISSUE TITLE
Templates in VS11 Beta

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#157]
The first thing I noticed is that the Script# templates do not work in VS11 Beta, at least not out of the box. However, I am able to successfully load and compile a Script# solution that had been created using VS2010.

In attempt to get them to work, I copied the templates from VS10 into VS11, re-registered templates and created a new Script# Script Library project. This works fine.

I then added an Import Library project, which fails because it cannot find various files in the template, like "AssemblyInfo.cs" and "Class1.cs". These files are present and correct in the template zip file.

I tracked it down to one difference - the .zipinfo file. This file exists in the Script Library project template but not in the Import Library template. After copying it from the Script Library template to the Import Library template (and modifying the file to suit its new template name and contents, etc) I can now successfully create an Import Library project in VS11 Beta.

Unfortunately I can't find out a lot of information about this file - is it something proprietary to Script#? I've had a look through some other template types and I can't see it being used anywhere else. It's also interesting that only 1 Script# project seems to use it, and VS11 has some sort of problem loading templates that do not have it.

Do you think it would be appropriate to modify the templates project so that all templates now have this file?

**Comment by nikhilk** [comment]
The .zipinfo shouldn't actually be there. It is a remnant of a file that directed the build process to list what to zip (which has since been replaced by msbuild tasks), and was specific to the homegrown script# build process. Looks like one .zipinfo remained in the source tree.

Its odd that the existence of a .zipinfo makes a template work...

I wonder if something has changed in VS11 that must be accounted for in the .vstemplate files … and the existence of a .zipinfo file (or perhaps any other file) is simply side-stepping that logic. I suspect you're hitting a bug in VS itself...

**Comment by andrewharry** [comment]
How did you get along? did you get the templates working in VS 2012 RC?

**Comment by stevehobbsdev** [comment]
I've just tested with the RC and it looks as though the templates from VS2010 now work just fine without modifying the templates themselves. Here is what I did:
1. Find C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\ProjectTemplates\CSharp\Script#
2. Copy the contents of that folder into the equivalent folder for VS2012: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\ProjectTemplates\CSharp\Script# (if the Script# folder does not exist, create it)
3. Delete C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\ProjectTemplatesCache
4. Run VS2012

You should also perform the above steps for the ItemTemplates folder as well.

**Comment by nikhilk** [comment]
Thanks for sharing. Couple of things...
- The right thing to do here is potentially not rely on msi to install the templates, and instead leverage the vsix functionality, and nuget for libraries. Need to look into that, and would be awesome to see some help here.
- For folks who want to go further with this in the meantime, the wix sources for setup are in the repository. They can be modified to do the right thing, for adding Dev11 support in the installer.

**Comment by nikhilk** [comment]
No longer an issue since the move to vsix as the distribution mechanism.
