### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#160]
Hi Nikhil,

is the software license still the same as that in the pdf for 0.5.5.0 (Nov 2009).
I'm wondering what are the license implications for including mscorlib.js and mscorlib.debug.js in a product. The license states that you may not "Sell, re-license, sub-license, rent, lease any part of the Software or create derivative works" which would imply that mscorlib cannot be distributed as part of a product.

Thanks

Donal

**Comment by nikhilk** [comment]
The license does enable you to redist the script files.

The updated license is in the EULA that appears in the installer.

Side note - plan is to convert all the sources themselves to the Apache license.
