### ISSUE TITLE
Array.push, splice etc

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#161]
Hi Nkhil,

Wondering why the above and other array methods are not included on the Array type? 
I see in mscorlib there are extensions added (add, removeAt, etc) to the JS Array class that are accessible via the List and ArrayList classed you have defined. I know you can get them using Type.InvokeMethod but it does defeat the purpose of not being able to access the native JS methods from Array.

Thanks

Donal

**Comment by nikhilk** [comment]
The equivalents - add, insert, replace, extract - cover the functionality of push, splice etc. The idea was to have a more c#/.net-ish interface rather than the raw javascript interface. Push does appear on Stack where it more closely matches the semantics.

Is there specific functionality that isn't covered?

**Comment by dmcweeney** [comment]
Maybe I'm losing the plot but I dont see any add/insert/delete methods on the Array class. I see them on List and ArrayList but not on Array.

The reason why I am following this path is that I possibly do not want to ship mscorlib.js with our code - thus me trying to use and get access to the native Array methods.

The other thing that would be really useful in this scenario is if there was some attribute one could set at the project level to flag mscorlib extensions at compile time. For example if I inadvertently used ss.StringBuilder a warning would be thrown.

Thanks

Donal

**Comment by dmcweeney** [comment]
Sorry didnt mean to close...

**Comment by andrewharry** [comment]
This is interesting.  On one hand the closer to C# Script# stays the easier it is to cut and paste existing code (from C#)
But would it be so bad if the Array class exposed the 'extra' native methods as well?

I personally would rather having both.  Especially when I'm trying to learn from javascript examples.

**Comment by nikhilk** [comment]
Added various methods (https://github.com/nikhilk/scriptsharp/commit/2f6a24daa9da97df015fef7629dc277163e7d6d3) ... basically stuff other than Push/Pop, which I think shouldn't show up on Arrays/Lists (they're available on Stack). Will be includedin next build.
