### ISSUE TITLE
Extension methods?

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#163]
Is it possible using Script# to write extension methods for existing js objects.
ie output would be like:

if (!Array.prototype.myMethod) 
{
    Array.prototype.myMethod = function Array$myMethod(p0) 
    {
        // implementation
    }
}

Thanks

Donal

**Comment by andrewharry** [comment]
Extention methods in C# are great and a powerful feature.  I use these all of the time.
The good bit is that unless you include the namespace you don't need to worry about them.

In javascript though the story is quite different.  If you modify the array prototype with something that change is going to be present everywhere.  This could of course be exactly what was intended and hallelujah!  but it isn't the same behaviour as C# hence the potential issue.

If well documented I say bring on C#4.0 features (or was it only 3.5?)

**Comment by volkanceylan** [comment]
I don't think extension methods should be implemented by defining them on prototype. Just like C# compiler does under the hoods, ScriptSharp should convert someObject.someExtensionMethod to SomeExtensions.someExtensionMethod(someObject)

**Comment by dmcweeney** [comment]
Going back to the question - Is it possible today to use Script# to write extension methods for existing js objects. 
If not any plans for the future - regardless of implementation.

**Comment by volkanceylan** [comment]
in a static constructor you can do whatever you like using Script.Literal, Type.SetField etc. e.g.

static Test() { Script.Literal("Array.prototype.myMethod = myArrayMethod"); }

void myArrayMethod() { ... }

**Comment by andrewharry** [comment]
@volkanceylan true forgot that C# is just presenting syntax sugar and is really just mapping the target object into a parameter for the static method.  So yeah, should be quite doable in Script# once it supports 3.5

**Comment by dmcweeney** [comment]
Ah never thought of the static constructor...

Thanks

Donal
