### ISSUE TITLE
Import library global var declaration

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#168]
Hi,

I know global variables are horrible etc but I was wondering is it possible to define a global var for an import library? Script.Literal is the alternative but there are alot more benefits if its typed/where used/etc.

Thanks

Donal

**Comment by nikhilk** [comment]
Have to think some more about this... but you might be able to define a class like System.Html.Window and a member on it representing your global variable. After all global variables end up on the window object in the browser.

**Comment by dmcweeney** [comment]
Hi Nikhil,

Thanks for the pointer. Got it working as follows in case someone else needs to do it:

```
[IgnoreNamespace, ScriptName( "window" ), Imported]
public static class ExternalGlobalVariables
{
    [PreserveCase, PreserveName]
    public static Element variableName ;
}
```

Thanks

Donal
