### ISSUE TITLE
ScriptSkip has no effect on methods

### ISSUE THREAD

**Issue by davidwengier** [nikhilk/scriptsharp#17]
I am trying to use Script# with KnockoutJS, and so when my properties (actually public fields, due to IntrinsicProperty limitations) are used they need to be used as functions in JavaScript. I have this working with the following code:

```
[PreserveCase]
[ScriptName("NameFirst")]
public ObservableString _NameFirst;

[ScriptSkip]
[PreserveCase]
public string NameFirst()
{
    return null;
}

[AlternateSignature]
[PreserveCase]
public extern void NameFirst(string value);
```

So as you can see, I have public fields that are prefixed with an underscore, but told to render without. This works fine, and since the fields are only referenced once, when setting up the Knockout object, its a small price to pay. I then have methods for getting and setting the values from KnockOut, which work well too. From the consumer side of this class, everything is fine.

The problem is that when this class is generated as JavaScript, the ScriptSkip attribute is ignored, and an empty NameLast function is output. I want to prevent this function from being output. I can't use the Imported attribute since that can only go at class level. I can't make both methods extern (which is what they really are) because Script# requires at least one concrete method.

Is this what the ScriptSkip attribute is supposed to do? Is there another way to get Script# to ignore certain methods?

The only workaround at the moment is to define the methods first, then define the fields, which means the generated JavaScript at least works, but it still has a lot of unnecessary generated code.

**Comment by nikhilk** [comment]
First, ScriptSkip is only intended to be used in imported types in imported libraries... so its not going to work here.

You might be able to try this in an import library:

[Imported]
public sealed class ObservableString {
  [ScriptName("")]
  public string Get() { return null; }

  [ScriptName("")]
  public void Set(string value) { }
}

Then in your class:

public class FooViewModel {

```
public ObservableString Xyz;
```

}

However your usage is going to be:

FooViewModel vm = new FooViewModel();
string x = vm.Xyz.Get();

Which is not optimal... even if all this works, which I am not sure.

I've been experimenting a bit with observables etc. in the context of Script# and earlier in the context of Silverlight, and I think a better view model pattern is to keep the observable aspect an implementation detail of the property, and have regular property/getter setters... which is different from the Knockout model which exposes observability into the public contract. Seeing the interest here I think I'll try to pick up where things were with that implementation and share it... but by definition its going to be different from Knockout, even if it addresses a similar problem space.

**Comment by davidwengier** [comment]
Thanks, the ScriptName("") works fine. I had moved away from "ObservableString" to just one "Observable" class though, so I need to go back to that now.  It would be good if I could make Observable generic ideally.

I'm interested to see what you have in the works.

**Comment by robitar** [comment]
The way I handle this is to define (in an imported library) a delegate like the following:

```
[Imported, IgnoreNamespace]
public delegate T Observable{T}(params T[] value);
```

Then in your model class, add a public field like this:

```
class ViewModel {
    public readonly Observable{string} Name = Ko.Observable{string}();
}
```

**Comment by robitar** [comment]
Hmm, hitting tab posted my comment before it was done...

With that, you can get and set the observable as a function:

```
string name = viewModel.Name();
viewModel.Name("foo");
```

**Comment by nikhilk** [comment]
This approach looks good to me.
