### ISSUE TITLE
Compilation on Linux/Mono fails

### ISSUE THREAD

**Issue by Meai1** [nikhilk/scriptsharp#171]
/.../scriptsharp/src/Libraries/CoreLib/Decimal.cs(60,60): Error CS0584: Internal compiler error: Outer conversion routine is out of sync (CS0584) (CoreLib)

And about ~20 more errors, not sure where to go from here, I'm not a Mono expert either.

**Comment by nikhilk** [comment]
If there are some folks with resources to pick up the investigation, that would be awesome.
However, at this point this isn't on the priority stack, and without enough information to suggest any specific fix, I will close this issue.
