### ISSUE TITLE
StringBuilder

### ISSUE THREAD

**Issue by jimmygilles** [nikhilk/scriptsharp#173]
Hello,

In mscorlib.js, I see that the implementation of the method "Append" of a StringBuilder is not totally correct.

```
append: function StringBuilder$append(s) {
    if (!ss.isNullOrUndefined(s)) {
        this._parts.add(s);
        this.isEmpty = false;
    }
    return this;
},
```

If I call the method with an empty string, "isEmpty" is set to false but it should stay to true (if it was still true).
I think it would be better to check s with the method "isNullOrEmpty" instead of "isNullOrUndefined".

Thanks !!

**Comment by nikhilk** [comment]
isNullOrEmpty assumes the parameter is a string. If append were passed in something like the number 0, we do want to append it ... so a better check is:

```
if (!ss.isNullOrUndefined(s) && s !== '') {
```
