### ISSUE TITLE
build failed when running from msbuild

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#175]
Strange one this...

My build was failing when running from the msbuild command line - just FAILED coming from the ScriptCompilerTask - where running withing VS 2010 the project and solution build fine.

After some investigation I narrowed it down to so static method stubs I had added for the Ajax array extensions - for example:

```
[Imported, IgnoreNamespace, ScriptName( "Array" )]
public static class AjaxArray
{
    [ScriptName( "contains" )]
    public static bool Contains<T>( T[] array, T item )
    {
        return false;
    }
}
```

I was under the impression that it was ok to define template method in inport librarys?

And ideas why it all builds in VS but not from the msbuild command line.

Thanks

Donal

**Comment by andrewharry** [comment]
Have you tried changing the scriptname to object? in the class attribute?

**Comment by dmcweeney** [comment]
Same behaviour - builds fine in VS but fails from msbuild command line

Thanks

Donal

**Comment by nikhilk** [comment]
Odd.
To be sure though, the compiler error is coming from compiling an assembly referencing this import library though, right? More specifically, the code above should itself not be compiled by script# at all. Can you confirm?

Assuming that is fine, perhaps you can share the solution containing both assemblies.

**Comment by dmcweeney** [comment]
Apologies yy mistake - its not working in VS either.
When I was building the repro I discovered what was happening. In the VS Error List window there is a warning being displayed - "The event ... is never used" but no error messages displayed. However if you look in the output window you will see the Build Failed message. As there were no errors being displayed in the Error List window I was assuming the build was fine...

Is it possible to get an error bubbled up from the script compiler task for conditions such as these?

Also I was under the impression that the Imported attribute indicated an import library and that the definition of generic methods were supported in import librarys?

Thanks

Donal

**Comment by andrewharry** [comment]
That's true, in practice I found it only worked if in a separate assembly

**Comment by dmcweeney** [comment]
I have it in a separate assembly but mixing code generation with the Imported attribute. Is there as assembly-wide "Imported" attribute that overrides all code generation?

Thanks

Donal

**Comment by nikhilk** [comment]
I am not sure what you mean when you're asking for an assembly-wide Imported attribute.

The way to build an import library is to create a project that doesn't invoke the script# compiler at all. Consequently, no code-gen either, i.e. nothing to override. The regular c# compiler continues to run, and produces the import library that you can reference in a project that does invoke the script# compiler.

The Import library project template has this all setup (specifically, its a regular c# project without any script# tasks but includes a reference to the script# mscorlib, instead of the default .net one).

Hope that helps...

**Comment by dmcweeney** [comment]
I see now the difference in the 2 csproj files as regards the imports of the targets. I have my projects created as normal script# projects and was wondering the best way to get them changed to an import library as not all the classes are adorned with the Imported attribute. The reason for this was to get the generic method definitions working. I guess the best way is to hack the csproj file.

Thanks

Donal
