### ISSUE TITLE
Minimised Script Version and Script.Literal calls

### ISSUE THREAD

**Issue by andrewharry** [nikhilk/scriptsharp#176]
I have a project using script# which runs fine with the debug javascript - but fails with the minimised version.

I have narrowed it down to calls such as this:

```
    static Global() {
        jQuery.OnDocumentReady(delegate {
            SyncData sync = null;
            Script.Literal("sync = typeof(SyncData) != 'undefined' ? SyncData : null");

            if (sync != null) {
                //Do Something with sync object
            }

        });
    }
```

In the minimised version of the above code the sync variable is renamed to '$1_0'
but the literial section remains as is.

I guess I should explain what the code is trying to achieve.
On the html page I have serialised a variable from the server called 'SyncData'
and the above javascript is trying to capture it's value.

Ultimately I need to be using the minimised script and need to get a good work around capturing global objects.

**Comment by andrewharry** [comment]
Found a good answer for dealing with global variables

https://github.com/nikhilk/scriptsharp/issues/168#issuecomment-4720216

**Comment by nikhilk** [comment]
You have to use a replacement token so the compiler can put in the right identifier. Use {0} in the string and pass in SyncData as an arg to Script.Literal.

That said why use Script.Literal? Use Type.GetScriptType for typeof functionality and Script.IsUndefined or maybe Script.Value for ensuring a value.

Even if you use Script.Literal, keep the assignment itself outside Script.Literal.
