### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by michaelaird** [nikhilk/scriptsharp#179]
Nikhil,

Are you gearing up for a new release? If so, there are a couple of things i'd like to contribute (updates to the jQuery API, etc).

Michael.

**Comment by nikhilk** [comment]
Would like to release an update/refresh in the not too distant future ... and address some of the key issues reported, so I can get past that, and then plan some of the larger workitems incl. overhaul of the codegen.

Feel free to let me know what you'd like to contribute and we can plan around them.

**Comment by michaelaird** [comment]
In particular, i'm thinking of the new jQuery On/Off methods, but I'll happily take on adding all the "new" stuff from jQuery 1.7 (http://api.jquery.com/category/version/1.7/)

**Comment by nikhilk** [comment]
They are now in ... I think it was your pull request right? Can you check the sources and see if they look good?

Any other jquery updates to take care of?

Sent from my phone

On May 23, 2012, at 10:05 AM, "Michael Aird" reply@reply.github.com wrote:

In particular, i'm thinking of the new jQuery On/Off methods.

---

**Comment by michaelaird** [comment]
Ah. I see it now. it was elkdangers' commit. looks good.
