### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by eNepper** [nikhilk/scriptsharp#18]
I got two classes named Event. The first one is my own wrapper class and the second one is from an imported lib.

I'm getting an error saying: Check that your C# source compiles and that you are not using an unsupported feature.  
When I'm trying to use the imported lib like this

``` Javascript
imported.lib.Event.AddListener(element, 'click', handler);
```

**Comment by nikhilk** [comment]
Use a using alias to distinguish the two - you can't use namespace qualified names.
