### ISSUE TITLE
Check that your C# source compiles and that you are not using an unsupported feature.

### ISSUE THREAD

**Issue by KarlMaynardDK** [nikhilk/scriptsharp#180]
I have my own import library that defines access to my webservices, which compiles no problem. But when i come to call a method the Script# compiler reports an error:

"Check that your C# source compiles and that you are not using an unsupported feature."

following the line number in the error it points at the following code line in my script:

Etrack1Client.Client.EnquiryLock(enquiryId, LockSuccededOpenWindow, LockFailed);

VS2010 doesnt indicate any errors with it.

If i simply add **"using Etrack1Client;"** to my source, then change the code to be:

Client.EnquiryLock(enquiryId, LockSuccededOpenWindow, LockFailed);

It compiles no problems.

**Comment by mattclay** [comment]
The Script# compiler does not support inline references to namespaces.  As you discovered, a using statement must be used to reference types in other namespaces.
