### ISSUE TITLE
jQuery variables wrong case

### ISSUE THREAD

**Issue by OzBob** [nikhilk/scriptsharp#188]
JSON that is being read (note the capital Greeting and Timestamp)

``` JSON
{"Greeting":"Hello 111! Its script# demo time...","Timestamp":"20/06/2012 3:30:27 AM"}
```

Is not readable by javascript generated in Script# from Nikhil's Mix11 Demo code:HelloPage.jQuery.cs

``` HelloPage.jQuery.cs
    [Imported]
    public sealed class ServerResult : Record {
        public string Greeting;
        public string Timestamp;
    }
...
    jQuery.GetData<ServerResult>(url,
        delegate(ServerResult data) {
            string greeting = String.Format("{0}\r\nGenerated on {1}...",
                            data.Greeting, data.Timestamp);
                            Script.Alert(greeting);
        });
```

because it generates all LOWERCASE jQuery variables:

``` wrongCaseGenerated
 var url = '/HelloService.ashx?name=' + encodeURIComponent(name);
            $.get(url, function(data) {
                var greeting = String.format('{0}\r\nGenerated on {1}...', data.greeting, data.timestamp);
```

I would have expected this:

``` correctedCaseGenerated
                var greeting = String.format('{0}\r\nGenerated on {1}...', data.Greeting, data.Timestamp);
```

**Comment by nikhilk** [comment]
Add [PreserveCase] attributes on the individual fields. That will cause the generated script to have Greeting and Timestamp.

I can't remember which JSON serializer I used the demo ... the serializer on the server might have been doing camel-casing which is in sync with how script# auto-camel-cases. If the serializer you're using doesn't do that, then your script# code needs to account for it.

Hope that helps.
