### ISSUE TITLE
Overriden Events

### ISSUE THREAD

**Issue by jimmygilles** [nikhilk/scriptsharp#197]
Hello Nikhilk,

A problem with event definition.
Here is the code

``` c#
using System;

namespace ScriptLibrary1
{
    public abstract class Class1
    {
        public abstract event EventHandler MyEvent;

        public abstract void MyFunction();

        public static Class1 Create()
        {
            return new Class2();
        }
    }

    internal class Class2 : Class1
    {
        public override event EventHandler MyEvent;

        public override void MyFunction()
        {
            if (MyEvent != null)
                MyEvent(this, null);
        }
    }

    public static class Class3
    {
        public static void MyOtherMethod()
        {
            Class1 tmp = Class1.Create();
            tmp.MyEvent += delegate(Object sender, EventArgs args)
            {
                Script.Alert("hello");
            };
        }
    }
}
```

Class3 is supposed to be in an other DLL so it can't instantiate Class2 directly.

In this code, Class1 is an abstract class that can't be an interface because it defines some methods.
Class2 is internal and inherits Class1 and I must override the event otherwise the compiler doesn't let me call "MyEvent".
Then in Class3, I attach a method to this event.

In debug it works, but it doesn't work in release because in the javascript, I have:

``` javascript
...
ScriptLibrary1.Class1.prototype={add_myEvent:function(value){this.$0=ss.Delegate.combine(this.$0,value);} ...
...
ScriptLibrary1._Class2.prototype={add_$1:function($p0){this.$2=ss.Delegate.combine(this.$2,$p0);} ...
...
ScriptLibrary1.Class3.myOtherMethod=function(){var $0=ScriptLibrary1.Class1.create();$0.add_myEvent(function($p1_0,$p1_1){alert('hello');});}
...
```

As you can see, in javascript, the class3 calls the "add_myEvent" method (from Class1) instead of "add_$1" (from Class2).

Do you know if there is an easy workaround ? Thanks !

Jimmy

**Comment by nikhilk** [comment]
I haven't tried it, but its possible explicitly implemented events with add/remove accessors might work. I suspect the rules to prevent minimization of an inherited member aren't applying to event fields.

**Comment by jimmygilles** [comment]
As a workaround, I changed "internal" to "public" (I hope it can be fixed with the next release :-))
Thanks
