### ISSUE TITLE
MissingMethodException when using a Script# assembly from another .NET assembly.

### ISSUE THREAD

**Issue by jpoehls** [nikhilk/scriptsharp#199]
I'm testing Script# right now and created a simple Script# class library with a single class.

The class has a method that does something like this:

``` csharp
public static string[] SplitName(string name)
{
    return name.Split(' ');
}
```

It compiles fine and generates the JS output file but when I reference this assembly from my NUnit project and try to test it a `MissingMethodException` is thrown.

```
System.MissingMethodException : Method not found 'System.String[] System.String.Split(Char)'.
```

What am I doing wrong?

**Comment by ghost** [comment]
I suppose it would not be possible, because S# uses different core library which has it's own types. NUnit on the contrary uses standard .NET 3.5 or 4.0 mscorlib dll. I suppose the best way for you is to leverage a special Unit Testing project that comes as a template with S# installation.

Hope that helps!

**Comment by nikhilk** [comment]
To add to what @ALive43 said, you add Test Classes (available as a template under the Script# node in the Add New Item dialog), as well as potentially helper test code within a Tests subfolder in your project. This creates a Foo.test.js build output alongside Foo.debug.js and Foo.release.js, which contains the test code you wrote exposed as QUnit tests.

You can then use Foo.test.js with QUnit and run them as you like. As an option, script# provides a unit test project to drive deploying and loading these tests, and report success/failures into the VS unit testing experience.

See this sample https://github.com/nikhilk/scriptsharp/tree/master/samples/AroundMe for a demonstration of the unit testing model.
