### ISSUE TITLE
Upgrade from 0.6.3 to 0.7.0.2 causes "Build Failed" with no error information.

### ISSUE THREAD

**Issue by vgribok** [nikhilk/scriptsharp#20]
After upgrading from 0.6.3.0 to 0.7.2.0 started getting dreaded Build Failed with not errors. In the process project's .js and xml doc files get generated successfully, but DLL does not.

I tried two different approaches with the same outcome:
1. Upgraded S# solution from 0.6.3.0 to 0.7.0.2.0 by changing mscorlib entry in csproj files, and some projects stopped building with dreaded Build Failed and no error messages, while other projects are OK.
2. Created a brand new 0.7.0.2 S# project and started adding CS files one by one and building. After adding a complex code file with 1500+ lines of code, started getting build failure. Removing the file makes project build again. The same file built fine in 0.6.3.0.

We are heavily invested in S# with a production project on the line. S# upgrade process was not smooth before, but this one is a show stopper and now we are really concerned. We would appreciate any help with the issue. I can email the project if there is a secure place to place it into.

All the best,
Vlad.

**Comment by nikhilk** [comment]
What is the line at which the failure occurs?

**Comment by chandramuralis** [comment]
It is not failing in any specific line. In the build output it will just say Build failed and it doesn't say any other info.

**Comment by nikhilk** [comment]
OK, you can email the project over ... specifically to the point where your project starts failing after you created a new project.

**Comment by nikhilk** [comment]
Fixed in 0.7.1.
