### ISSUE TITLE
Can you please support Generics?

### ISSUE THREAD

**Issue by ranc** [nikhilk/scriptsharp#209]
We would love to have support for generics, it should be trivial in JS as you just need to ignore it:

Example:
    class SomeGenericClass<T>
    {
        private T GetValue()
        {
            return default(T); 
        }
    }

Will compile to:
getValue: function ...()
{

**Comment by nikhilk** [comment]
Its not really a trivial feature... otherwise it would be done. It wasn't when it was added to c# itself btw. Generics within the compiler itself require significant work, even if they don't have lots of impact on the generated script.

**Comment by ranc** [comment]
Yes, I respect that, I also closed this one as I saw I am not the first to speak about it.

BTW, in issue #177 one suggested to open up the core. I advise this. we can contribute also for the lack of testing you mentioned.

You did an amazing work! let more people contribute, that is what open source is all about. I see lots of good will on this.

THANKS!
