### ISSUE TITLE
Can you please support Extension Methods?

### ISSUE THREAD

**Issue by ranc** [nikhilk/scriptsharp#211]
This would really help us write a neater code!

**Comment by nikhilk** [comment]
I'm doing some investigation around this and other c# features and how to best do them. Those language features are top of the priority list.

**Comment by ranc** [comment]
Thanks! good to know.

**Comment by danieldegtyarev** [comment]
Yep, nice)

**Comment by nikhilk** [comment]
Closing this bug for now, but for sure, this will be accounted for in the revamping of the compiler.
