### ISSUE TITLE
KnockoutMapping.ToObject not compiled correctly

### ISSUE THREAD

**Issue by dennis3001** [nikhilk/scriptsharp#213]
For some reason [ScriptAlias("ko.toJS")] attribute on this method does not seem to work here.
The calls to the method are translated as ko.mapping.toObject which, of course, causes a JS error:
Object #<Object> has no method 'toObject' 

Please adise

**Comment by nikhilk** [comment]
Can you see the sources for Knockout and point out where things are incorrect? Better yet, create a fix and share it. When I look at KnockoutMapping.cs, I don't see a ToObject method.

There is a ToObject method on Knockout, but it doesn't have a ScriptAlias and should be generating ko.toJS as written.

**Comment by dennis3001** [comment]
Thanks for the quick response. 
I was not using latest source but the one from the installer. My code does not compile though when I use latest source that I build. I get a few "Check that your C# source compiles and that you are not using an unsupported feature" errors where I use ObservableArray.
But I guess this issue can be closed since those problems are unrelated...
