### ISSUE TITLE
How to install current build of Script#?

### ISSUE THREAD

**Issue by danieldegtyarev** [nikhilk/scriptsharp#215]
Previously I managed to install it with a nice script in bin direcory. I see it changed now. I have tried to found any instructions or found something similar, but failed. Also I didn't managed to compile it, ZipX issues and FxCop dependencies (which FxCop I need to install?).

It would be very nice to add some lines in readme to describe it.
Daniel

**Comment by nikhilk** [comment]
Once you build (more on that next) you double click the resulting ScriptSharp.vsix generated in the bin directory. This installs templates along with default nuget packages.

To install other nuget packages built as part of the build process (relevant if you change any of the import libraries and need to ignore the ones in the public nuget.org package repository), go into Visual Studio's package manager settings in Tools|Options, and add a new local package repository pointing to bin\Zip\Packages folder, and add packages from there.

This will go into the docs around building/working with the script# repository once I get a wiki page up. If you are not building script# yourself, then simply download the vsix (https://github.com/nikhilk/scriptsharp/downloads), install it and you're set.

Now for the build errors... I thought FxCop was installed as part of visual studio. It is referencing assemblies pointed at by the $(CodeAnalysis) variable in msbuild. Sounds like you don't have them installed as part of VS... for me, they were in %programfiles(x86)%\microsoft visual studio 11.0\Team Tools\Static Analysis Tools\FxCop as well as in %programfiles(x86)%\microsoft visual studio 11.0\Common7\IDE\PrivateAssemblies. Can you check if you have those? If not, sounds like I need to add them to the repository.

**Comment by andrewharry** [comment]
I have fxcop installed and I didn't do anything special other than installing VS2012 RTM on a clean copy of windows7
