### ISSUE TITLE
Error building resources with 0.7.5

### ISSUE THREAD

**Issue by michaelaird** [nikhilk/scriptsharp#216]
I'm getting the following error when i try to build a project that has resource files:

1>  "C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\Resgen.exe" /useSourcePath /r:e:\TempProjects\MvcApplication13\packages\ScriptSharp.0.7.5.0\tools\mscorlib.dll /r:E:\TempProjects\MvcApplication13\packages\ScriptSharp.Lib.HTML.0.7.5.0\lib\Script.Web.dll /compile Resource1.resx,obj\Debug\ScriptLibrary1.Resource1.resources
1>  Processing resource file "Resource1.resx" into "obj\Debug\ScriptLibrary1.Resource1.resources".
1>e:\TempProjects\MvcApplication13\packages\ScriptSharp.0.7.5.0\tools\ScriptSharp.targets(54,5): error MSB4062: **The "ResXCodeGeneratorTask" task could not be loaded from the assembly e:\TempProjects\MvcApplication13\packages\ScriptSharp.0.7.5.0\tools\ScriptSharp.Build.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.**
1>
1>Build FAILED.

**Comment by nikhilk** [comment]
Did you uninstall the old version? Guessing it is picking up ScriptSharp.Build from the GAC.

**Comment by michaelaird** [comment]
That (plus a reboot) did the trick. 

I'm in the process of writing up documentation on how to update an existing ScriptSharp project to 0.7.5.0. Is this useful or do already have this documented?

**Comment by nikhilk** [comment]
No there isn't yet, and that would be useful.
The key steps I think are:
1. Removing the ScriptSharp.targets reference from the csproj and replacing it with the standard CSharp targets reference.
2. Removing the references to mscorlib.dll and other script# assemblies.
3. Installing the nuget packages needed - certainly the package with id "ScriptSharp", and others depending on the references removed in #2.

Also see the History.txt file for any other changes in 0.7.5.

**Comment by michaelaird** [comment]
Here are the steps I went through:
1. Uninstall any previous versions of ScriptSharp (on my system this required a reboot to fully take effect)
2. Install ScriptSharp 0.7.5 vsix
3. Rename `Properties\{ProjectName}.script` to `Properties\{Script.Template` and `Properties\{ProjectName}.ruleset` to `Properties\{FxCop.ruleset`
4. Change Custom Tool to blank (empty) for for any resx files.
5. Remove all references
6. Unload the project and edit the csproj file
7. Change ProjectGuid to {CBB0568B-ECE5-4899-96D4-5852424FF690}
8. Replace 

```
<TemplateFile>Properties\{ProjectName}.script</TemplateFile>
<CodeAnalysisRuleSet>Properties\{ProjectName}.ruleset</CodeAnalysisRuleSet>
<ReferencePath>$(SolutionDir)\packages\ScriptSharp.0.7.0\Framework</ReferencePath>
```

with 

```
<ScriptTemplate>Properties\Script.template</ScriptTemplate>
<CodeAnalysisRuleSet>Properties\FxCop.ruleset</CodeAnalysisRuleSet>
<GenerateScript>True</GenerateScript>
<GenerateResources>True</GenerateResources>
```
1. Remove `<Import Project="$(SolutionDir)\packages\ScriptSharp.0.7.0\ScriptSharp.targets" />`
2. Add `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` at the end 
3. Reload project
4. Add ScriptSharp nuget package
5. Add any other needed nuget packages
6. Rebuild!

Step 2 (and the associated renaming in step 8) are optional but keep the project in line with the default project template (and possible updates in the future).

**Comment by michaelaird** [comment]
One more thing. It looks like the order of Imports matters (particularly if you're using nuget package restore). In the end, the last 3 lines of my .csproj file look like this:

```
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\..\packages\ScriptSharp.0.7.5.0\tools\ScriptSharp.targets" Condition="Exists('..\..\packages\ScriptSharp.0.7.5.0\tools\ScriptSharp.targets')" />
  <Import Project="$(SolutionDir)\.nuget\nuget.targets" />
```

**Comment by nikhilk** [comment]
Thanks! This is awesome... and helps to get some more eyes on it. Later in the day I'll try to get a wiki topic opened on this so it can be better maintained, as well as hopefully more discoverable.

I think step 7 should not apply ... every project gets a unique guid within the solution, and you probably don't want to change it for an existing project.

The nuget.targets is needed if you've enabled nuget package restore, and is nuget specific.

**Comment by michaelaird** [comment]
I agree with your feedback.

For the nuget.targets, i've realized there's a chicken-egg problem for package restore on a build server. the ScriptSharp.targets file doesn't exist until **after** package restore has run.

i'm looking at the solution the OctoPack guys used around copying the targets file to a different folder and commiting it to source control (https://github.com/OctopusDeploy/OctoPack/blob/3a8e858633db9c30c58f96e4a537f2a79be6cd53/source/tools/Install.ps1) but i'm not too sure how to test this locally...

**Comment by nikhilk** [comment]
Ideally the nuget folks would hook into the vs solution prebuild event to execute restore targets in projects within solution.

Can test locally by updating package and building new vsix. Since default packages are embedded in vsix, there is no need to publish a package to try it out.

**Comment by michaelaird** [comment]
OK. I've got this working locally by copying mscorlib.dll, ScriptSharp.Build.dll, ScriptSharp.dll and ScriptSharp.targets to a "known" location and committing them separately. I'll try to update the install.ps1 file to take care of this later today.

**Comment by nikhilk** [comment]
To be honest, I didn't understand what the OctoPack install script does differently. Perhaps you can explain what it does.

I settled on the current install script after fair amount of trial and error ... this area of nuget/vs doesn't seem completely solid, given both nuget and the install script are trying to modify the project (eg. addition of packages.config, and targets reference).

**Comment by michaelaird** [comment]
The octopack install script checks if package restore is enabled (Get-MSBuildProperty RestorePackages $project). If it is, it copies the .targets file to a solution level folder (in their case .octopack) and adds the import to point at that folder. Then it's up to the developer to check in that .octopack folder so that it can "bootstrap" itself before the package is restored.

i think this is a reasonable solution until nuget improves this scenario.

**Comment by nikhilk** [comment]
I don't what is there right now is worse off. Developer has to know one package has to be checked in... same as what you describe without the rest of complexity.

Also when ScriptSharp package is added at project creation time, package restore likely isn't enabled.

**Comment by michaelaird** [comment]
How about this: let's leave it as is for now. I'll add my steps to enable
package-restore to the docs wiki and we'll see how people feel about it. If
they want it to be handled by the install.ps1 we can revisit it later....

**Comment by nikhilk** [comment]
I opened an issue on the nuget site - http://nuget.codeplex.com/workitem/2471 - for this. Lets see what comes of it. Would probably help to go vote it up.

Potentially the nuget.targets can be updated to invoke msbuild on the current project file after the restore is done as a workaround. Something to try. It does mean you have to edit the nuget.targets file generated for you when enabling package restore.

Everything here is a gotcha/additional step... so ideally this is something that nuget would intrinsically recognize as a scenario and support more elegantly.

**Comment by michaelaird** [comment]
I'm going to close this issue for now. Let me know if you think I should open a separate one to track the "nuget package restore" issue.

**Comment by ghost** [comment]
Thanks michaelaird- this was really helpful to get our projects upgraded to the latest. However, a couple of additions in case others use this post for upgrades: 
- _do not_ perform Step 7 above- ProjectGuids should be unique for every project, and if you change one, you may hose up any Project/Solution configuration that hangs off it. 
- there may be a stale mscorlib 0.7.0.0 reference that should be removed from old projects as well

**Comment by andrewharry** [comment]
So what is new in this version of Script#?  Are there new features? or is this more bringing the compiler code into the fold?

**Comment by nikhilk** [comment]
Best way to see exactly what is new in each build is to look at the History.txt file in the repository.

As of now the compiler is also in. Has been for a while, but it was in a branch and is now in master. Also recently pushed a bunch of updates in the "cc" branch - this is stuff that will go in into 0.8 which is hopefully not that far off now.
