### ISSUE TITLE
Compiler source code

### ISSUE THREAD

**Issue by pylover** [nikhilk/scriptsharp#224]
I need to change the script# compiler's code to add an Attribute to use on classes to generate javascript types just like extjs new class system

after some crawlings on the source from github i found the compiler's dll on nikhilk-scriptsharp-f7215c5\bin\ref\ScriptSharp.dll

but the compiler source codes is not available on github

Is script# OpenSource? and if yes where i can download the compiler source code?

**Comment by pylover** [comment]
I decompiled the ScriptSharp.dll , so the source code is now available, i will create a fork on your project, to publish the compiler's source code that supporting sencha classes via "SenchaClassAttribute". Also a VisualStudio project system was created with *.jssproj extension.

I think you are a Micro$oft developer that do not know anything about github or opensource world!.
I suggest you to use codeproject or codeplex to publish your compiled assemblies. Github is for OpenSource developers.
and at the end, i have one question: Why you don not publish the source code?

**Comment by nikhilk** [comment]
This is definitely the plan.

As mentioned to @pylover in his email suggesting I should get on with open source world...

```
The sources for the compiler bit will be on github in a short matter of time, where you'll be able to contribute. There is a bit of an overhaul happening, and it would land in a better spot to allow others to contribute in a way that is aligned with future changes I am intending. Releasing current sources is going to result in a bit of double work. The rest of the sources already are.
```

Getting the new sources is taking longer than expected, and IMO putting out a very early version isn't going to help/motivate someone helping it (the foundations need to be in place), and at the same time putting out the old/current sources isn't the best idea, as I'd hate to see someones changes/contributions in that version not make it into the new version, or require double work on someone's part. I am sure there will be differing opinions on that, and I have gone back/forth myself on this... so I might still change that decision based on progress.

I would suggest thinking about contributing the vs extension in the meantime... and discussing it, as that is net-new work. I do have some experience with doing a working prototype of the same here, and its definitely on the desired list.

As for not putting it on codeplex/codeproject, I think the vs extension gallery + nuget packages is a better, more friction-free approach that fits well into developers workflow for acquiring and using script#.
