### ISSUE TITLE
New .vsix deployment incompatible with throwaway projects

### ISSUE THREAD

**Issue by ghost** [nikhilk/scriptsharp#225]
Since moving to the new .vsix deployment, it's not possible to create new Script# projects with throwaway projects enabled in VS (Uncheck Tools->Options->Projects and Solutions->Save new projects when created). The project file rewriting that occurs after creation fails with "Unable to locate the solution directory. Please ensure that the solution has been saved.", and leaves the project file in an unusable state (no references, missing Script# MSBuild targets import).

Throwaway projects aren't very useful for Script# anyway, but I always have them enabled for other stuff, and it's annoying to shut them off when creating a new Script# project (as well as confusing for someone who might not understand the connection).

Nuget has the same issue: http://nuget.codeplex.com/workitem/2184?PendingVoteId=2184 - it appears to be a problem with the  pattern used to rewrite the project file with relative references to the local package, but just wanted to document it here in case anyone else ran into it.

**Comment by pylover** [comment]
I was created a new VS Project system, that works well, see: #224

**Comment by nikhilk** [comment]
Didn't even know about throwaway projects. These sort of options certainly introduce bloat in vs IMO.

That said, there is a prototype of a script# project as well, that will improve the next level... haven't put it out yet, as the approach doesn't lend itself to Express SKUs.
