### ISSUE TITLE
Some errors found in current sources

### ISSUE THREAD

**Issue by edgeroad** [nikhilk/scriptsharp#227]
It compiles fine but generates the wrong javascript.

1) "Script.CreateInstance(foo)" generate "createInstance(foo)" instead of "new foo"
2) "Script.GetField(x,y)" generate "getField(x,y)" instead of "x[y]" (same for Script.SetField)

In mscorlib.js, at // Debug Extensions section, test line "if (!console) {" could be "if (!global.console) {"

**Comment by nikhilk** [comment]
When you picked up the current sources, did you also pick up the updated ScriptSharp.dll from the source tree? It contains changes pertinent to the Script.CreateInstance/GetField methods.

**Comment by edgeroad** [comment]
Hi nikhilk,
I was updating my project from Script# 7.4 to current and I had not yet removed the old msi.
I think it was used the old compiler (dll) instead of the new one (it is possible ?).
Now I have removed the old msi and everything is working properly.
Thank you very much.
