### ISSUE TITLE
Help improving Script# to support more C# Language features

### ISSUE THREAD

**Issue by ghost** [nikhilk/scriptsharp#23]
Nikhik,

I've tried contacting you via blog and email, but have heard no response. I think Script# is great, and would like to help improve it. I have experience writing compilers, and have perused Script#'s via Reflector. I have other ideas that could also ease using Script# libraries from other projects, and not require specifying a script output directory everytime.

Why wont you let me help you?

-Paul

**Comment by nikhilk** [comment]
Hey Paul,
Would love to have you contribute. Really appreciate the patience and the passion!

Sorry for lack of immediate response... been caught up in one thing or other, but wanted to send a full response back and realized I'd be able do more justice on that over the weekend. Please stay tuned... will get back this weekend... promise :-)

Nikhil

**Comment by ghost** [comment]
Thanks for the reply Nikhil; I'll stop copy/pasting from reflector now ;)

I sent an email a few days ago to your live.com email. Can you reply from there so we can move the conversation off github for now?

Regards,
-Paul
