### ISSUE TITLE
Team up with Saltarelle

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#232]
Nikhil, you have been pioneering on c# to javascript compiling, and I think a lot of us appreciate this very much. However, being on your own, progress, although steadily, has been quite slow... esp. for some c# 4.0 features, ScriptSharp still has no support.

Erik Källén has forked your work, and already included a lot of c# 4.0 feature we all love. I have tested the Saltarelle compiler, and was very satisfied with the result, all the new features like anonymous objects, objects initializers, anonymous delegates, lambda delegates, var keyword ect... are already available in Saltarelle.

Now both of you are building almost exactly the same product, so in my opinion a lot of effort is wasted. I would like to ask you, please contact Erik, team up, join forces, I think we will all benefit  a lot if you would do that...

**Comment by ashrafsabrym** [comment]
I agree with @rekna1 about this.
Saltarelle seems to be very promising, and uniting the efforts will be very fruitful.

**Comment by nikhilk** [comment]
Agree on the experience that those features bring. Would have been interesting to see some collaboration on this esp. since it uses the core runtime and libs as a starting point. I'll have to see w. Saltarelle folks if there is any interest now. Closing this issue itself.

**Comment by hamidpp** [comment]
hi: how to use anonymouse object in Saltarelle
[HttpGet]
        public HttpResponseMessage TestJS()
        {
            try
            {
                var charts = chartService.GetAllChart().Select(c => new { c.ChartId, c.Title });
                return Request.CreateResponse(HttpStatusCode.OK, new { list = charts, msg = MSGResource.SuccessEvent, type = MsgType.Success });
            }
            catch (System.Exception e)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, MSGResource.ErrorEvent, e);
            }

```
    }
```

how to get 'list' name object in -
jQuery.Ajax(new jQueryAjaxOptions()
            {
                Url = "/Api/ChartApi/TestJS",
                DataType = "json",
                Type = "GET",
                Success = (d, t, r) =>
                {
                   // how to use d.list ?????
                    var content = jQuery.Select("#FeedItems");
                    content.Html("");
                    foreach (var item in (List<Chart>)d)
                    {

```
                }
            }
        });
```
