### ISSUE TITLE
DialogObject has no constructors defined

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#233]
Using Visual Studio 2012 RC (I know, I should update to RTW version, but I'm trying to understand before I redo my development "test" machine again), when I try to create a jQueryApi.UI.Widgets.DialogObject() it's throwing an error of "The type 'jQueryApi.UI.Widgets.DialogObject' has no constructors defined."

Any help/advice?

**Comment by nikhilk** [comment]
This is like any other jQuery plugin.

```
jQuery.Select("#div1").Plugin<DialogObject>().Dialog()
```
