### ISSUE TITLE
Developing class structures for other javascript libs

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#235]
Going off of this idea:

```
jQuery.Select("#div1").Plugin<DialogObject>().Dialog()
```

Any extensions, say for instance, Twitter Bootstrap's Dialog, would we mimic the way that the jQueryUI DialogObject was defined, where it all inherits from jQueryObject?

I'm asking because although I like jQueryUI for things, I think that I'd like to use Twitter Bootstrap for the UI.  It feels lighter and a bit cleaner.  Wouldn't mind writing the code to be able to then use Script# for doing the rest of the Javascript stuff.

**Comment by michaelaird** [comment]
Here's a class I wrote for the Bootstrap Modal:

```
    [IgnoreNamespace]
    [Imported]
    [ScriptName("$.fn.modal")]
    public class ModalObject : jQueryObject
    {
        public ModalObject()
        {
        }

        [AlternateSignature]
        public ModalObject Modal()
        {
            return this;
        }

        public ModalObject Modal(string action)
        {
            return this;
        }

        public ModalObject Modal(ModalOptions options)
        {
            return this;
        }

        public ModalObject On(string eventName, jQueryEventHandler eventHandler)
        {
            return null;
        }

        public ModalObject Off(string eventName, jQueryEventHandler eventHandler)
        {
            return this;
        }
    }

    [Imported]
    [ScriptName("Object")]
    [IgnoreNamespace]
    public sealed class ModalOptions
    {
        public ModalOptions() { }

        public string Backdrop;
        public bool Keyboard;
        public bool Show;
    }
```

I haven't tackled any of the other Bootstrap plugins but i'd be happy to collaborate with you if you want to work on more of them.

**Comment by dealproc** [comment]
@michaelaird I have the bulk of them all written, I just need to learn how to tweak everything to get them to be usable for using ScriptSharp (and I have to really learn Git, I'm more familiar with SVN and hg, in that order).

It looks like adding Attributes, inheriting from jQueryObject for the "object classes", and learn what the ScriptName attribute does and how we pull the right text from the bootstrap javascript file.

Should this be under the namespace similar to how jQueryUI was done?

**Comment by dealproc** [comment]
@michaelaird @nikhilk How can we use enums for the event names, etc. instead of just encoding strings?  that seems silly, doesn't it?

**Comment by michaelaird** [comment]
See the CompareResultStatus enum that I contributed:

https://github.com/nikhilk/scriptsharp/blob/80bc91c7f6031d08c1fb6cc7b94c5a6073be1ad2/src/Libraries/Knockout/CompareResultStatus.cs

by adding the [NamedValues] attribute, ScriptSharp will replace the enum entries with strings at compile time.

**Comment by dealproc** [comment]
cool!  that's better, as it limits the mistaken typos at 3:00 AM

**Comment by nikhilk** [comment]
I didn't realize bootstrap was a jQuery plugin ... so much to keep up with! :-) ... of course, would be super interesting to see this made available out-of-the-box with script#, so looking forward to it.

I'd say yes, lets mimic jQuery plugins (there are a few in the tree now within the sources and samples in addition to jQueryUI)... so they present a consistent programming model. So for example, on namespace, if you want to follow other jQuery plugins, then jQueryAPI.Bootstrap would be a good choice.

You don't need the ScriptName("$.fn.modal"), since the generated script you'll want is $(...).modal()... in other words, no one is going to refer to this class in generated script, so you don't have to worry about how its going to be named, or override the generated name with explicit specification via ScriptName.

If there is stuff in common to all bootstrap plugins, you might want to define a BootstrapObject deriving from jQueryObject first, just like WidgetObject in jQueryUI.

Let me know if you have any more specific questions, or if you'd like to fork this repo, and put your code, I can even check it and provide feedback before creating a pull request.

**Comment by dealproc** [comment]
I'll probably fork out, so if I louse up the check-in (more comfortable with Hg than git), I can copy the *.cs and re-fork it. (I think the total definition, based on my understanding, is going to be ~400 lines of code...not sure if a base class is going to be needed or not).

I'm not sure if Bootstrap is a "plugin", but it does depend on having jQuery available if you want to use the dialogs, carousel, etc.

**Comment by nikhilk** [comment]
When I see the getting started page (http://twitter.github.com/bootstrap/getting-started.html) and the programmatic api (http://twitter.github.com/bootstrap/javascript.html), its pretty much following the plugin pattern.

**Comment by dealproc** [comment]
gotcha.  I have the basic "constructors" scripted at this point.  Need to dig into the details, but this'll be cool to do the script generation like this.

**Comment by dealproc** [comment]
Ok.  finally got my changes committed to github.  I forked the repository, and I have my code in src\Libraries\jQuery\jQuery.Bootstrap\ (https://github.com/dealproc/scriptsharp.git)

@michaelaird Do you want to take a copy and review/update as you see fit?  I'm at least in the position right now to get started with things, which is better than where I was at.  Just sucks that I can't sync this into KilnHg and keep a link until we get it to nuget... so I'll be maintaining 2 x projects for now.

@michaelaird I also added you as a contributor... hope that is right, so that you don't have to fork from me and do further changes... @nikhilk, if I should do the same with you, please let me know.  Would love to get this into the master copy so that it can get to nuget and everyone can benefit.

**Comment by michaelaird** [comment]
i have some feedback for you but I don't want to clutter it here. can you turn on "issues" for your fork so we can talk about it over there?

**Comment by dealproc** [comment]
sure.

**Comment by dealproc** [comment]
I guess we can close this @michaelaird since you want to take it over to my fork.... makes no sense to keep this open anymore.

**Comment by theoutlander** [comment]
What's the status on this? Are we moving the pulling the bootstrap code into the base? I can find some time to help out if needed.

**Comment by dealproc** [comment]
I have a base implementation in my fork... I just had to abandon the usage of Script# for Typescript, as I didn't ahve much time to do the library implementations... I had to get back to working on our core product.  If someone can give me the IDE format settings that I can go through my stuff and do the CTRL + K, D to everything to get it to the proposed format, I'll push the changes back to core.

**Comment by dealproc** [comment]
I have a base implementation in my fork... I just had to abandon the usage of Script# for Typescript, as I didn't ahve much time to do the library implementations... I had to get back to working on our core product.  If someone can give me the IDE format settings that I can go through my stuff and do the CTRL + K, D to everything to get it to the proposed format, I'll push the changes back to core.
