### ISSUE TITLE
Getting reference to 'this' inside of a delegate where 'this' == specific object type

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#237]
So, trying to get the basics of Sammy encoded, the way you build-up the "program main" in sammy is by doing:

``` javascript
$.sammy('#selector', function() {
    this.get('#/', function() {
         {whatever has to happen when you route here...}
    }
}
```

but I'm unsure how to define 'this' inside of the anonymous function.  Should there be an abstract class to extend from to define the program main, or is there another preferred method to use?

**Comment by nikhilk** [comment]
What is the "this" supposed to refer to?

If you were to write an anonymous delegate inside a c# instance method, and refer to member fields, or other member methods, the compiler will automatically bind the function to the current instance. You don't have to explicitly define it.

I suspect that isn't the scenario though. Is there a link to the Sammy doc that explains it?

**Comment by michaelaird** [comment]
It looks like get is an alias of the route method on the Sammy.application
object. I don't think you need the 'this' reference.

http://sammyjs.org/docs/api/0.7.1/all#Sammy.Application-route

**Comment by michaelaird** [comment]
I just went back for a longer read of the docs.

I think the $.sammy() methed takes an initializer function that gets called
in the context of the new Sammy application object. I don't think c# or
scriptsharp supports this. I would suggest just getting back the Sammy
application object and then calling the methods on it directly.

**Comment by nikhilk** [comment]
Probably worth taking a look at jQuery equivalents and how something similar was implemented.

Sammy is similar to jQuery. It might have a method such as CreateApplication, which gets generated to $.sammy
SammyApplication is similar to jQueryObject and has methods like Get.

jQuery.Current gets generated as "this". Similarly there could be Sammy.Current which is typed as SammyApplication and gets generated as "this"

https://github.com/nikhilk/scriptsharp/tree/master/src/Libraries/jQuery/jQuery.Core

**Comment by dealproc** [comment]
@michaelaird That was my take on it as well.  So, your thought is to basically:

``` C#
SammyObject app = new SammyObject();
app.Get("#/", delegate(){
...
});
```

but then inside of Get, where you're supposed to get the context of the SammyObject, how do you interact?

**Comment by dealproc** [comment]
@nikhilk makes sense.  I'll take a look this evening.  forgot that there was a lot of "static" stuff done.

at this point, not sure if Sammy is the way to go to get routing, but I figure I need to start with something, and after doing some simple stuff and quickly having the refactor capabilities of C#, I don't want to abandon using Script#.

**Comment by dealproc** [comment]
What is the class structure like to create a Javascript line like:

``` js
app.contextMatchesOptions(context, {except: {path:'#/otherpath'}});
```

---

Ah... Dictionary!
https://github.com/nikhilk/scriptsharp/issues/12

**Comment by dealproc** [comment]
I threw what I have thus far into the ScriptSharp project in my repository, should you want to take a look @nikhilk @michaelaird ... just an fyi.

The main application seems to come through, but a few things, like the idea of "Use" needs to be discussed on how you would implement, etc.
