### ISSUE TITLE
Unobtrusive Validation

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#238]
Is there a quick and dirty way to get this rendered?

``` js
    $.validator.unobtrusive.parse(document);
```

some code I'm converting right now depends on jQuery Unobtrusive Validation, and I can't seem to find a quick way to do this.

**Comment by michaelaird** [comment]
Script.Literal("$.validator.unobtrusive.parse(document)");

**Comment by dealproc** [comment]
ah... nice... that's what it was :)  Couldn't recall... and I saw that several times already!

**Comment by nikhilk** [comment]
If you do go that route, do this instead:

```
Script.Literal("$.validator.unobtrusive.parse({0})", document)
```

So that the right identifier gets inserted after minimization of locals.

That said, should this be accounted for in the jQuery.Validation import assembly?

**Comment by dealproc** [comment]
Not sure.. jQuery Unobtrusive Validation was part of MVC3.
the literal javascript was being passed as you see it prior, which is why I'm doing it that way... I just want to get it in c#, and then cleanup/refactor from there.  Tired of managing disjointed javascript sprawled across the pages and in *.js files... trying to consolidate it all into an easier to maintain library. (work project)

**Comment by michaelaird** [comment]
As far as I know, it's not actually part of jQuery.Validation. I believe
it's Microsoft's "unobtrusive" add-on to jQuery-Validation that gets
bundled with MVC.

In our project, we've dropped it in favour of Knockout-Validation (
https://github.com/ericmbarnard/Knockout-Validation) so we can
programmatically set validation in the ViewModel objects.
