### ISSUE TITLE
Build error on VS 2012

### ISSUE THREAD

**Issue by YaakovDavis** [nikhilk/scriptsharp#239]
I'm getting the following error when trying to build the solution, commit f7cf18e47fefa1da5a992baa2d2d98aff817abf3 (latest). Please advise:

Error   1   The command "....\tools\bin\nuget pack Packages\Core.nuspec -OutputDirectory ....\bin\Zip\Packages -NoPackageAnalysis" exited with code 1.

Thanks,

**Comment by michaelaird** [comment]
Build in release mode.

**Comment by nikhilk** [comment]
Please build the release flavor first, and then debug.

I should I guess pass the configuration property to nuget.exe (and figure out how to reference that property in the nuspec file)...

**Comment by YaakovDavis** [comment]
Building in release mode worked, thanks!

**Comment by theoutlander** [comment]
That worked perfect, thanks!
