### ISSUE TITLE
Embedding javascript in Script# DLL to ease referencing

### ISSUE THREAD

**Issue by ghost** [nikhilk/scriptsharp#24]
I believe I have a way to deal with embedding javascript reasources into Script# script and import libraries, so that the DLL can simply be referenced from another web project, and by calling a single method during Global.asax.Global.Application_Start, the script can be saved to whatever Scripts folder is necessary (this also facilited by some post build steps in the ss project). Not quite perfect, but vastly easier than the current, manual and 'labor intensive' way of moving DLL's and their corresponding .js's around and specifying a hard output directory, also helps keep versions of each together. The problem I'm having is your ScriptAssembly attribute. Script# wont compile with out it, but when a script# DLL is loaded during runtime (when the call from Application_Startup is made to copy the embedded javascript resources), ScriptAssemblyAttribute doesnt exist in System namespace (because compiler is now using the 'real' mscorlib), and an exception is thrown. I understand using ScriptAssemblyAttribute to prevent someone from trying to use a 'real' clr assembly in a script project, but I'd much rather be able to ease referencing like I've described above, than be 'protected' from referencing 'real' assemblies. Can you add an option to NOT check for ScriptAssemblyAttribute? or move that attribute out of your mscorlib?

**Comment by erik-kallen** [comment]
You can use Mono.Cecil to load resources from assemblies that cannot be loaded.

**Comment by nikhilk** [comment]
Simplifying copying of script files associated with an assembly using regular assembly references as part of VS project system work.
