### ISSUE TITLE
Adding cleanNode to Knockout static class

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#240]
http://stackoverflow.com/questions/10048485/how-to-clear-remove-observable-bindings-in-knockout-js

Apparently, you're able to call :

``` js
ko.cleanNode(element);
```

to remove Knockout bindings from a particular element.  This isn't documented on Knockoutjs.com, etc, but many people document it works.  We should add this call to KnockoutJS

**Comment by michaelaird** [comment]
I just had a quick glance in the code. ko.cleanNode is actually a shorthand for ko.utils.domNodeDisposal.cleanNode. would it be better to expose that object in Knockout.Utils ?

**Comment by nikhilk** [comment]
Shorthand looks like better api... not just because it's shorter, but stuff like domNodeDisposal looks like internal implementation.

**Comment by dealproc** [comment]
I have the shorthand, but I made a mistake and put it as part of my main repos for this... how do I do a push to just give you those few lines, or do you want me to cut & paste it in a message, and you can just add it to the main repos @nikhilk ???

**Comment by nikhilk** [comment]
I can copy the lines.
