### ISSUE TITLE
jQuery plugin for multi-part form?

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#241]
Trying to post a file to the server, and (I haven't explored every class) it seems like there's no available plugin under the Script# struture to upload mulit-part form data.... anything that I'm missing?

**Comment by nikhilk** [comment]
Unless jQuery core has something, there isn't anything right now.

In general, there are tons of plugins. I think some of the key ones common across apps would be nice to include. Others would land in apps (similar to the approach I took in the samples) to start with.

**Comment by michaelaird** [comment]
I'm not at my computer but I'll send you a couple of lines of code that I
use a little later.

**Comment by michaelaird** [comment]
Here's what I use to post a file

```
                object[] files = new object[0];

                jQueryObject fileUploader = (jQueryObject)e.Data["uploader"];

                Script.Literal("files = e.target.files");

                object data = null;

                Script.Literal("data = new FormData()");
                Script.Literal("data.append('items[]',files[0])");

                jQueryAjaxOptions options = new jQueryAjaxOptions();
                options.Type = "POST";
                options.Url = UploadURL;
                options.Data = data;
                options.ProcessData = false;
                Script.Literal("options.contentType = false"); //set this to false so the mime-type gets set correctly

                jQuery.AjaxRequest<string>(options)
```

In this case "e.target" refers to an input type="file". The "files" property requires HTML5.

Looking back on this, we should really implement the File object (https://developer.mozilla.org/en-US/docs/DOM/File), FileList(https://developer.mozilla.org/en-US/docs/DOM/FileList) , FormData (https://developer.mozilla.org/en-US/docs/DOM/XMLHttpRequest/FormData)  in the Web library.

**Comment by dealproc** [comment]
Is there a way of using Modernizr and Shim-ming this for non html5 capable browsers?
Cool stuff tho.  will compare with how I implemented for a project at the consulting gig shortly.

**Comment by dealproc** [comment]
http://blogs.msdn.com/b/henrikn/archive/2012/03/01/file-upload-and-asp-net-web-api.aspx
adding this link... talks about how you post from a page to Web API, which is what I'm looking to do.  Just wondering if this can be done using json, or if it needs to be a full postback and implement via an iFrame.

**Comment by michaelaird** [comment]
The code I posted above POSTs a file to an API controller in our system. no
postback/iframe required.

**Comment by dealproc** [comment]
We're using a form plugin to handle file uploads on the project @ the consulting gig I'm at...
http://malsup.com/jquery/form/
