### ISSUE TITLE
Adding properties to ObservableArray<T>()

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#242]
Needing to do something like:

``` c#
ObservableArray<object> objects = Knockout.ObservableArray<object>();
objects.Id = "something"
```

I need it for how Ryan N. built out the "Available Students" array in this example:
http://jsfiddle.net/rniemeyer/UdXr4/

any advice?

**Comment by nikhilk** [comment]
Script.SetField would help writing this. (used to be Type.SetField)

**Comment by dealproc** [comment]
Ok.

**Comment by dealproc** [comment]
Are we able to open the Wiki here, and start putting these "issues" up as documentation?  Seems like a lot of what I'm asking would work better if we created Wiki pages, I can pop an IM somewhere, and we can edit the Wiki to get it right?
