### ISSUE TITLE
jQuery.Unique seems to be missing from object model

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#243]
http://api.jquery.com/jQuery.unique/

Workaround?

**Comment by nikhilk** [comment]
Looks like it should be added.

Thoughts/approaches on workarounds, and a general model for addressing these types of issues:
1. To be immediate term unblocked (eg. when you're coding, and hit a missing api) - use Script.Literal with a TODO to go fix later. In fact, FxCop rule flags all use of Script.Literal to serve as reminder.
2. Intermediate term - add the missing member to your local copy of the repo, build the tree, and use the resulting assembly.
3. Longer term - get the fix back into the main repository, where it can be incorporated into a release.

**Comment by dealproc** [comment]
Gotcha.  Been doing #1, can only do #2 on home business systems.. systems @ contract gig can't run git for some reason. #3 - can you do multiple forks of a repo into a personal repo set?

**Comment by nikhilk** [comment]
You can clone a repo (even without forking) into multiple locations any number of times, as well as commit locally into them, merge across them, package the whole local folder, copy it around etc. etc. Love git from that perspective. You can also create multiple branches... but I imagine for this scenario what works best is a clone with local commits buffering up any number of metadata changes needed.
