### ISSUE TITLE
Merge Blade compiler for improved c# features support

### ISSUE THREAD

**Issue by Ventajou** [nikhilk/scriptsharp#244]
We're still waiting for Script# to support c# 4 features. There's another open source c# to JS compiler out there called Blade (https://github.com/vannatech/blade) which already supports most of those nice features, such as: full generics, type inference, lambdas, dynamic (great replacement for Script.Literal), etc... 

I've been using Blade for some side project in the past few months and the experience is frankly great. But it's also a much younger project with some rough edges like for example the lack of minification. In that respect, Script# is a much more established platform.

I think the community could benefit from Script# and Blade complementing each other instead of competing. There is definitely demand around compilation to JavaScript as can be seen with the release of TypeScript. By putting our efforts in a common project instead of two, everyone would benefit.

Am I the only one who thinks that would be a great idea?

**Comment by nikhilk** [comment]
I'm happy to collaborate (or at the very least, learn from other existing efforts), esp. since I am considering couple of possible paths for next steps in terms of language support and what comes beyond that (still early/raw thoughts) for script#. Will check out this other project and ping the folks there.

**Comment by dorba** [comment]
Hi, I'm the developer of Blade, and a friend of Andre (Ventajou). I'm certainly open to discussions around how we could benefit from combined efforts. Blade has quite a few key differences from Script# though, and merging the two could be fairly difficult. But if you see anything useful, by all means, feel free to use it! 

Also, I've personally used Script# quite a bit in the past, and had good success. I'd love to see it get c# 4 support. If there's anything I can do to help on that front, let me know.

**Comment by nikhilk** [comment]
Hi Barry, great to hear from you ... will ping you offline over email once I take a look at Blade a bit (hopefully tomorrow).
