### ISSUE TITLE
Rename 'DependentObservable<T>' to 'Computed<T>' to coincide with Knockout's naming conventions

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#246]
Seems in the 2.0/2.1 release, the name change was done to name it Computed instead of DependentObservable.  Thinking that we should do the same in the c# code to keep it synonymous.

http://knockoutjs.com/documentation/computedObservables.html

**Comment by nikhilk** [comment]
So it is renamed... and certainly for a better name.
Question is whether everyone or generally most folks have moved on to 2.0+ ... if they have, then yes, it would be ok to rename... otherwise its going to break some folks, and might warrant a wait for some period of time.

**Comment by michaelaird** [comment]
What about syncing the version # of the nuget package with the version # of
knockout? And/or branching it for 1.2/2.0?

**Comment by dealproc** [comment]
The way that Steve Sanderson handled that, thus far, was to keep both names in the code, for now.  Just thinking we can add the Computed<T> type for now, and roll it out when they do for their latest build.

With a tool like Script#, I think developers need to realize that it's not going to be like a Microsoft product... wait 3 years, have a release, and that's supported for 15.  The dynamics of the web are changing so rapidly that they'll have to set their release bars, and supported revision levels based on what they need.

**Comment by andrewharry** [comment]
you can use my version https://github.com/maverix/ScriptSharpKnockout
I keep this fairly inline with the current version of knockout

**Comment by nikhilk** [comment]
@dealproc - My point wasn't to hold off indefinitely for making changes - definitely want to keep up-to-date, but I am not tracking knockout, so I have no idea if this change was made in knockout just recently (suggesting many folks might not have updated yet), or has been changed for a while (in which case hopefully most folks have moved up to it).

@michaelaird - struggled a bit with best model for import assemblies and how they relate to versions of script they represent. In an ideal case, there would be an import library that matches 1:1 with the script, but thats going to require too much overhead in keeping in sync, and increase the clutter in the source tree. Ideally I'd like to keep the script# versions consistent amongst themselves, as it would also get a bit crazy to say v2.0 of X depending on v1.7 of Y which depends on 0.7.5 of Z. Way too many versions... so given all that I picked the alternative of keeping generally in sync with scripts, but not in lock step.

@maverix - would you be able to provide a sense of where the script# knockout library is out of sync. I think now might be a good time to sync and document which version the import library is sync'd up to.

For this change in particular, I'd suggest getting it in within the "cc" branch ... the changes there will be released as build 0.8, which contains a few other breaking changes, and so might as well lump this in as well.

**Comment by dealproc** [comment]
no worries.
