### ISSUE TITLE
Can't use Knockout

### ISSUE THREAD

**Issue by athalay** [nikhilk/scriptsharp#248]
I am creating a new ScriptSharp library project in VS2012 on Win8 (downloaded ScriptSharp in VS).

I'm adding Necessary nuger packages, including Knockout.

In the default class's constructor I type the following:

KnockoutApi.Knockout.ApplyBindings(this);

And this even doesn't compile, with error: 'Check that your C# source compiles and that you are not using an unsupported feature.   '

I tried setting the project's runtime version to 2.0, 3.0, 3.5, 4.0 but without any success.

Can anyone help me with this step-0 problem?! :(((

**Comment by athalay** [comment]
It seems I've found the problem, I shouldn't use namespace.class.method format, I should use using for the namespace, now it compiles.

**Comment by nikhilk** [comment]
Which version are you using? I believe the compiler error message specifically alludes to the limitation/likely reason to look for.

That limitation will be addressed when the compiler work gets done to support new language features (currently ongoing).
