### ISSUE TITLE
Multi-dimensional arrays are broken in referring projects

### ISSUE THREAD

**Issue by talshani** [nikhilk/scriptsharp#25]
I Have new Solution with two project
One is "IncludedProject" has one class

``` c#
namespace IncludedProject
{
    public class Class1
    {
        public int[][] Member;
    }
}
```

which compiles fine.

the other one ("Script" project) also has one class

``` c#
namespace Script
{

    public class Class1
    {
    }
}
```

Script has a "project reference" to IncludedProject

and it doesn't compile with the following error

```
Error   1   Unable to resolve referenced type 'System.Int32[]'. Make sure all needed assemblies have been explicitly referenced.    C:\Program Files (x86)\ScriptSharp\v1.0\ScriptSharp.targets 33  5   Script
```

this happens with any type i checked instead of int

**Comment by nikhilk** [comment]
Fixed in 0.7.4.0
