### ISSUE TITLE
Knockout afterRender's 'this' is not the VM itself

### ISSUE THREAD

**Issue by athalay** [nikhilk/scriptsharp#250]
I want to bind many VMs with same template in different places of the page.

I'm setting up everything, and:
- I create a "public void AfterRendered(System.Html.Element[] elements){..}" method for my RepetitionVM
- I define this callback when I'm defining the template for the target render-tag:

data-bind="template: { name: 'repTemplate', afterRender: afterRendered}"

I want to access the 'current' RepetitionVM in my afterRendered, which is a non-static method of my VM. The problem is that the 'this' variable is not the VM itself (which have been used as a VM for the current template), but the page (or whatever)!

Is there any convenient way to retrieve the VM which has been "rendered", or shall I really iterate through all items in the Element[] elements argument, and call 

Knockout.DataFor<RepetitionVM>(elements[i]);

for each of them and check whether the result is no null, and if it's not then it's my VM (hopefully)?

**Comment by nikhilk** [comment]
I think issue #203 relates to this scenario.
I think knockout is not invoking bound methods within the context of the object from which the member method was looked up, and so you have to explicitly do that in your html markup.
