### ISSUE TITLE
'define' is undefined exception - Script# 0.8.0.0

### ISSUE THREAD

**Issue by andrewharry** [nikhilk/scriptsharp#251]
I'm playing with the latest CC build of script sharp.
I have a simple wrapper for the localStorage but the javascript produced is throwing an unusual error on load

0x800a1391 - JavaScript runtime error: 'define' is undefined

I have the correct ss.js script loaded before my scripts.

"use strict";

define('SLC.Storage', ['ss'], function (ss) {
  var $global = this;

  // SLC.Storage.MyStorage

  function SLC$Storage$MyStorage() {
  }
  SLC$Storage$MyStorage.set = function(key, value) {
    window.localStorage.setItem(key, JSON.stringify(value));
  }
  SLC$Storage$MyStorage.get = function(key) {
    var value = window.localStorage.getItem(key);
    if (value == null || !value.toString()) {
      return null;
    }
    return JSON.parse(value.toString());
  }
  SLC$Storage$MyStorage.remove = function(key) {
    window.localStorage.removeItem(key);
  }
  SLC$Storage$MyStorage.clear = function() {
    window.localStorage.clear();
  }
  var SLC$Storage$MyStorage$ = {

  };

  var $exports = ss.module('SLC.Storage', null,
    {
      MyStorage: [ SLC$Storage$MyStorage, SLC$Storage$MyStorage$, null ]
    });

  return $exports;
});

**Comment by nikhilk** [comment]
You'll need to do one of two things:
- Use an AMD-style script loader (that declares define and require). Script# provides a compact version ... see ssloader.js or if you want something more widely used, then requirejs.
- Change the script template (see AssemblyInfo.cs in a new script# project) from the default one used. Change it to not use define.

Either case, look at the samples in the cc branch. They demonstrate all three options - AMD pattern with ssloader, AMD pattern with requirejs, and non-AMD script generation. Samples described in the wiki - https://github.com/nikhilk/scriptsharp/wiki/Repository

**Comment by andrewharry** [comment]
Thanks for the quick response!  I have modified the assemblyinfo and now working.
