### ISSUE TITLE
Alternative to [GlobalMethods] attribute in 0.8

### ISSUE THREAD

**Issue by andrewharry** [nikhilk/scriptsharp#252]
I have a global method which is required to run to kick off my scripts.
Since the GlobalMethods attribute has been removed in 0.8 - what is the best pattern to use now?

```
[GlobalMethods]
public static class Global
{
    static Global() {
        jQuery.OnDocumentReady(delegate {
              //Do Something
        });
    }
}
```

**Comment by nikhilk** [comment]
[ScriptModule] ... represents module-level code and can be applied to a static class. Restricted to static ctor only. I think the jQuery page template reflects the pattern as well.

Doesn't apply to the snippet above, but previously GlobalMethods also allowed generating methods that magically got attached to the window object, which don't make sense in either a module world, or in the node.js world. So for those there is

[ScriptExtension(extendee)]

where you can be explicit about what is being extended. ScriptExtension also subsumes [Mixin] ... so in general there has been a bit of long overdue attribute cleanup.

These will all be things to doc more clearly, as the current release notes list things but not necessarily very clearly... so its certainly useful to hear.

**Comment by andrewharry** [comment]
Using the above ScriptExtension -  I assume that if I make the extendeee 'window' then I'm adding the methods to the window object...  all good.

But how do I get the code to automatically run - as the above code snippet would have?

**Comment by nikhilk** [comment]
ScriptModule does that... code that automatically runs as it is parsed.

One other thing - ScriptModule requires your class to be marked as internal, which makes sense as the type isn't exposed outside of the module being generated.

**Comment by andrewharry** [comment]
Okay so far so good.  I had to split my old global class into two.  One that is using the ScriptModule attribute to invoke automatic starting.  The other using the ScriptExtension('window') to add global methods.

Now i'm just trying to work out why some static constructors are firing before the ScriptModule runs.  Didn't used to be an issue

**Comment by nikhilk** [comment]
All static ctors get generated toward the bottom of the generated script after type registration, but there isn't any order guarantee... never was. Probably just happened to work, but that could change, and I suspect there was a change right now that led to this. Types get sorted right now to generate code such that base classes get generated before derived classes.

I would recommend in general for a particular script to have only one class marked as ScriptModule - it controls when everything else happens, in the desired and predictable manner. Its sort of the Main method/entrypoint method for the module.

Also curious why you're adding to the window ... I keep hearing folks don't want to pollute the global space, hence one of the values of the module pattern. Is it code you have and thats the way it was, or is there specific reason to want to add to window?

**Comment by andrewharry** [comment]
I would probably change it, but it is for some legacy stuff.  Write now I'm just to get everything working in 0.8, which is easiest if I change as little as possible inorder to avoid adding bugs.
