### ISSUE TITLE
Array Length Undefined - 0.8

### ISSUE THREAD

**Issue by andrewharry** [nikhilk/scriptsharp#255]
Looks like something is wrong with the following code:

``` c#
    int[] wonIds = new int[0];
    for (int i = 0, length = deals.Length; i < length; i++) {
         if (dealStateHelper.isWon(deals[i].state))
            wonIds[wonIds.Length] = deals[i].Id;
    }
```

``` javascript
    var wonIds = new Array(0);
    for (var i = 0, length = deals.length; i < length; i++) {
      if (dealStateHelper.isWon(deals[i].state)) {
        wonIds[wonIds.length] = deals[i].id;
      }
    }
```

The length property on the wonIds array is undefined

**Comment by nikhilk** [comment]
Not sure what might be happening here as the script seems to be as expected, and trying to create an Array using the initial capacity and doing a subsequent .length on it works fine. Something else going on in the page?

**Comment by andrewharry** [comment]
Found the issue.  Was a problem with PreserveCase (Id shouldn’t have been id)

Sorry for the goose chase!
