### ISSUE TITLE
"This" scoping issues in 0.7.6 branch

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#262]
In 0.7.5, when I call a delegate, I get this:

``` javascript
Portal.App.SammyAppImplementation.applicationDefinition = Sammy('#app-main', function() {
    this.get('#/', function() {
...
```

In 0.7.6 (from my branch), I get this:

``` javascript
PortalAdministration.App.Bootstrapper.appDefinition = Sammy('#app-main', ss.Delegate.create(this, function() {
    this.get('#/', function() {
```

How should the delegates now be defined so that when I get into my delegate function, the "this" is the right "this" for the context?  In this particular case, "this" should refer to the Sammy.ApplicationContext object.

Looks like SammyJS needs a lot more work before I can submit the pull request.

**Comment by nikhilk** [comment]
See how jQuery.This/jQuery.Current work. Whether a delegate is created or not depends on whether you reference member variables inside your delegate.

**Comment by dealproc** [comment]
My focus on each of these is the first line.  I feel like what I need to do is to create a Delegate call, much like how you do the ArrayIterationCallback() or similar.

What I did initially was to just have a static "CreateApplication(string selector, Action callback){}", but now, with the changes in 0.7.6, it seems like "Action" should be changed to a Delegate.
