### ISSUE TITLE
Javascript obfuscation

### ISSUE THREAD

**Issue by lduchosal** [nikhilk/scriptsharp#263]
Hello,

As a suggestion, I'd like to have an obfuscated version of my Javascript generated classes.
Would need a [Ofuscate=false] attribute to my entry point method/class to get my business started.

I'll gladly add some effort on this development. I would like to hear what you think about this suggestion.

Regards
Luc

**Comment by nikhilk** [comment]
Great to hear you want to put some effort here. I'd certainly be interested in what might be possible.

Do look at AjaxMin (http://ajaxmin.codeplex.com) if it is an interesting starting point. Script# 0.8+ uses ajaxmin as a pluggable minifier.

Once that support exists, we can add the attributes necessary.

---

I'm curious what you're thinking though, so perhaps go ahead and share some more detail... there are "obfuscators" out there, but they're pretty much minimizers.
