### ISSUE TITLE
Public classes for JS code under "window"

### ISSUE THREAD

**Issue by briantoba** [nikhilk/scriptsharp#266]
I'm testing 0.8 and have a problem with an object hanging from window. I have my public API object on window and I achieved this with: [ScriptName("window.class")] on my class. I knew this was a hack but worked.

How can I get something like this on 0.8?

```
// The caller of my API in javascript
window.API.init("MyInitString");
window.API.shutdown();

// In S# I had
[ScriptName("window.API")]
public class API
{
    public void Init(string s);
    public void Shutdown();
}
```

GlobalMethods won't work because I need the window.API part and not just global methods.

Thanks for any suggestion.

Brian

**Comment by briantoba** [comment]
I can do:

```
API api = new API();
Script.Literal("window.API = {0}", api);
```

But I was wondering if there's a more elegant solution.

**Comment by nikhilk** [comment]
Did we cover this in email, or was that someone else asking the same?

```
public sealed class API {
    static API() { Script.SetField(typeof(Window), "API", new API()); }
    public void Init(string s) { ... }
    public void Shutdown() { ... }
}
```

There are other ways to avoid the SetField bit, but I am assuming adding to the window object this way is uncommon.

Ultimately the elegant way is to package your functionality as a module (as the script# compiler now enables), and from the consuming code, require the module so you don't rely or touch window, or degrade and in the worst case scenario, "export" the module by merging its members onto window.

**Comment by briantoba** [comment]
Someone else is asking the same, I guess.

I guess the SetField is a more elegant solution to the Script.Literal.

I'm not familiar with the way exported modules would look like in JS, but my API needs to be called by javascript code that wasn't written in S#.

The FB API is accessed in javascript like:

```
FB.init();
//or
window.FB.init();
```

That's why I'm interested in having it in _window_ and can't rely on "only for S# solutions". I don't want to force my API callers to use require when the most used API (FB) doesn't.

If SetField or my Script.Literal is the only solution, that is fine. I wanted to see if there was a better solution.

Thanks,
Brian

**Comment by nikhilk** [comment]
The module pattern is not a script# pattern. I do agree however its relatively new. It helps that jQuery (which is arguably the most used library), and other libraries such as Knockout do offer it as a choice... so hopefully this will catch on, and other libraries such as the FB one will follow suit. This is why I mentioned both the module pattern, and degrading to the model where you do export a global.

For an example of doing that, see ss.js itself - if you are using an AMD-style script loader, it doesn't touch window, and other modules reference APIs off of ss by requiring "ss" or declaring it as a dependency in their define call. If an AMD-style loader isn't found, ss.js goes ahead and adds "ss" to window.

---

Besides SetField there are alternatives.

Add the following in your assembly's script template (which basically allows you to escape out to script for defining the scaffolding and supporting bits around the generated script):

```
window.API = {}; // define the object if you like this syntax better than Script.SetField.
```

For the script template, see AssemblyInfo.cs if you started with a 0.8 project, or AssemblyInfo.cs in the samples if you had an older existing project.

Now you can write the following code:

```
[ScriptExtension("window.API")]
public static class API {
    public static void Init(string s) { ... }
    public static void Shutdown() { ... }
}
```

The thing to keep in mind is the ScriptExtension is about exposing a set of methods (at the moment), whereas the SetField approach is about exposing an object instance, so it allows for properties, fields if you'll need that as well. It comes down to picking an approach that most closely matches the semantics of what you're doing in your API.

Yet another variant approach is to actually define a import class so you don't have to use a string field name and SetField, but I think its overkill.

Anyway, sounds like you're unblocked, so I'll close this out.
