### ISSUE TITLE
Checking for null, undefined,...

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#27]
Suggestion for adding a method for checking for null, undefined, ... 

Apparently Script.IsNullOrUndefined( ) is not necessary (see http://enterprisejquery.com/2010/10/how-good-c-habits-can-encourage-bad-javascript-habits-part-2/ item 4. NOT TESTING & SETTING DEFAULT VALUES CORRECTLY)

Seems the best way to check is 

```
   if (something) { ... } 
```

which checks for what they call all false-y values...

**Comment by nikhilk** [comment]
Note that Script.IsNullOrUndefined is when you want to know whether something is null or undefined, as opposed to 0, or false, or empty string...

For checking for false-y values, script# did emit the shorter form when comparing against true, false, 0, or empty string, in the past, but as far as I remember there were gotchas with that, and hence currently it only optimizes for true/false, and not other values. I'll have to dig through old logs and bugs to figure out what was going on before bringing back the code to check for 0 and empty string.

**Comment by rekna1** [comment]
ok, it's just a minor thing... can live with the other methods if necessary... maybe in some later version you could provide an alternative method the implements the shorter behaviour ( other features are far more important than this one)

**Comment by nikhilk** [comment]
I went back and found the issues behind removing this optimization... and I think I'll be able to address them, and include the optimization to do a loose equality check when comparing against false-y values, and include in next build...

**Comment by nikhilk** [comment]
Knew I'd find an issue... if you write a method expecting a bool parameter in c#, and you're passed in an int/string/null instead of an actual boolean, and treat it like an int, unexpected things happen.

So now if you're checking for a false-y value, then !expression will be generated.
If you're checking for !false-y value, then !!expression will be generated.

Changed in 0.7.1.
