### ISSUE TITLE
Nuget.exe exiting with code 1

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#273]
I've been merging the master repository with my own fork for a while, but today I came to build the solution after making some changes and I get a build failure because nuget.exe is exiting with code 1, when trying to pack the package libraries.

I'm just wondering if there's something I've missed regarding setting the solution up for building/testing. It appears to be trying to put the files in the correct folders, which do exist on my drive..

**Comment by michaelaird** [comment]
There's an issue when you build in "debug" that the packaging scripts are pointing at the "release" folder. build once in "release" and then come back to "debug" and it will work ok....

**Comment by nikhilk** [comment]
I believe this is fixed in the cc branch - the solution configuration removes the zipx project from the debug build, so you don't run into this.
