### ISSUE TITLE
Some of the properties associated with the solution could not be read

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#277]
I'm getting this error when opening an existing ScriptSharp solution in VS2012, which has been upgraded from 0.7.4 to 0.7.5:

```
Some of the properties associated with the solution could not be read
```

I know that some project keys have been removed, such as WebAppPartitioning, but are those missing keys the things which are producing this error?

**Comment by nikhilk** [comment]
Issue #216 covers migrating a project from 0.7.4 to 0.7.5. However the error doesn't sound related... as far as script# goes, it doesn't impact the solution file... so my guess is something else is going on. Any chance you're opening a vs2010 solution in vs2012.

Also the WebAppPartitioning feature - that still exists in 0.7.5 ... it is going away in 0.8.

**Comment by stevehobbsdev** [comment]
I've managed to solve this by simply re-doing the solution file; creating a new one then adding all the projects back in. I read a forum thread somewhere about the solution file becoming corrupted after an upgrade, in that is declares certain sections multiple times but with differing project count values. I noticed the same pattern with our solution, and it turned out to be the cause.
