### ISSUE TITLE
Window.onbeforeunload missing

### ISSUE THREAD

**Issue by athalay** [nikhilk/scriptsharp#278]
I'd like to hook up for the Window.onbeforeunload event (which should be a Func<string> delegate), but it does not exist.

I tried to hook up with the following code:

```
public delegate string BeforeUnloadCallback();

private static ElementEventHandler _navigateAwayHandler;
private static string _onBeforeUnloadEventName = "onbeforeunload";

_navigateAwayHandler = (ElementEventHandler)(Object)new BeforeUnloadCallback(
                        delegate()
                        {
                            return StringResources.RelationShipHasUnsavedChanges;
                        });
Window.AttachEvent(_onBeforeUnloadEventName, _navigateAwayHandler);
```

But it only works in IE (displaying my string in a confirm() when I try to navigate away), but not in Chrome. When I used Script.Literal it worked, but Script.Literal can only accept static text :(

Any help anyone?

**Comment by nikhilk** [comment]
The fact something works in IE but not in Chrome isn't a script# issue. I see you're using Window.AttachEvent, which is an IE-only API ... and indicates you're using an old build of script#? Suggestion would be to try using latest build and use AddEventListener instead.

**Comment by athalay** [comment]
Dear Nikhilk,

I'm not telling you that Chrome's bugginess is a Script# issue, I'm telling that the lack of onbeforeunload event of Window class in Script# causes me trouble in Chrome.

I'll try out AddEventListener then, thx for the reply.

**Comment by nikhilk** [comment]
The idea is to use AddEventListener - that is the standard api ... rather than a member off of Window.

**Comment by athalay** [comment]
Sorry to bother you again, but in IE8 and IE9 neither the AddEventListener nor the AttachEvent works :(

Only the following code works (for me) in IE8 and IE9:

window.onbeforeunload = function () {
            return "Are you sure you want to navigate away?";
        }

Any advice or idea how shall I overcome this problem? I'd like to avoid using Script.Literal if possible.

**Comment by nikhilk** [comment]
```
Script.SetField(typeof(Window), "onbeforeunload", (Action)delegate() { ... });
```

That would be your best option.

**Comment by athalay** [comment]
Thanks, but the problem is that Script class has no such method. Theoretically I'm using SS 0.7.5, and was upgrading a month ago from my old SS projects by hand :/

Any idea?

**Comment by john-pennington** [comment]
Hey athalay, on S# revs < 0.8, the SetField API is a static method hanging off of the Type type:

```
Type.SetField( ... )
```

Consider taking a look at the Visual Studio Object Browser (CTRL+ALT+J). It is useful for inspecting and discovering the types and members of the S# base class library, or any library referenced by your projects. In the left side of the Object Browser look for mscorlib [0.7.0.0].

More info on the VS Object Browser:
http://msdn.microsoft.com/en-US/library/exy1facf(v=vs.100).aspx
