### ISSUE TITLE
jQueryAjaxOptions - incorrect mapping of JsonpCallback to jsonp

### ISSUE THREAD

**Issue by martimedia** [nikhilk/scriptsharp#28]
In code you have jsonpCallback  mapped to jsonp, but jsonp and jsonpCallback are different, see http://api.jquery.com/jQuery.ajax/

jsonp String

Override the callback function name in a jsonp request. This value will be used instead of 'callback' in the 'callback=?' part of the query string in the url. So {jsonp:'onJSONPLoad'} would result in 'onJSONPLoad=?' passed to the server. As of jQuery 1.5, setting the jsonp option to false prevents jQuery from adding the "?callback" string to the URL or attempting to use "=?" for transformation. In this case, you should also explicitly set the jsonpCallback setting. For example, { jsonp: false, jsonpCallback: "callbackName" }

jsonpCallback String, Function

Specify the callback function name for a JSONP request. This value will be used instead of the random name automatically generated by jQuery. It is preferable to let jQuery generate a unique name as it'll make it easier to manage the requests and provide callbacks and error handling. You may want to specify the callback when you want to enable better browser caching of GET requests. As of jQuery 1.5, you can also use a function for this setting, in which case the value of jsonpCallback is set to the return value of that function.

**Comment by nikhilk** [comment]
Fixed in 0.7.1.
