### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#280]
hey guys,
just to let you know migration from 0.7.5 went seamingless. 
great job there.

but it looks like i have  found an error in the handling of inheritance.

here an example:
public class a
{
 public void SomeMethod()
{}
}

public class b : a 
{
}

public class c : b
{
 // overides method from a 
 public void SomeMethod()
{
base.SomeMethod();
}
}

now ... when new c().SomeMethod(); is called javascript complains that b.SomeMethod() is undefined.
this worked fine in 0.7.5.

to me this is not a major issue since i just implemented ...
 public void SomeMethod()
{
base.SomeMethod();
}
... in class b.

but i thought i d let you know.
regards,
 levi

p.s. i guess this is the same issue as 
https://github.com/nikhilk/scriptsharp/issues/197

**Comment by aschoenebeck** [comment]
Hi levi,

can you try with virtual/override? Like this:

public class a
{
public **virtual** void SomeMethod()
{}
}

public class b : a 
{ }

public class c : b
{
// overides method from a 
public **override** void SomeMethod()
{
base.SomeMethod();
}
}

**Comment by levi2** [comment]
hey aschoenbebeck,
thanks for the comment.
i thought virtual and override were not supported. nice to know they are.

sadly it does not help.
... ps.: works if i add another 
public override void SomeMethod()
{
base.SomeMethod();
}
}

to b ; )

**Comment by nikhilk** [comment]
This is a good issue you've brought up ... something that must definitely be fixed before the final 0.8 build is published, so definitely good timing!

**Comment by levi2** [comment]
aww ... thanks 

_bows_

**Comment by nikhilk** [comment]
Committed a fix to this issue (https://github.com/nikhilk/scriptsharp/commit/01290c010c62789ec182f41daeac59ca33122feb). I'll have it be incorporated into the next 0.8 preview build in a bit, but you can sync and build if you need the fix immediately.

**Comment by levi2** [comment]
thanks!
