### ISSUE TITLE
Jquery UI - slider get/set value

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#281]
Hey guys,
I m not sure if i am just doing it wrong, but getting/setting the value of the slider does not seem to work.

here is what i did.
SliderObject slider = select.Plugin<SliderObject>().Slider(sliderOptions);
slider.Value(1);

due to the description the overrider for "value" with an int parameter is supposed to be implemented in jqueryui.
it even says that this method gets/sets the value for the slider although the method does not return anything.

again not a mayor issue since i can still use it using script.literal.
just wanted to let you know.

regards,
 levi

**Comment by nikhilk** [comment]
Not sure I've understood the bug, so don't know what needs to change - what should the generated script be? What script do you have with Script.Literal that makes it work? What script is currently generated?

Also, for jQueryUI issues, the import assembly was generated (see: https://github.com/igochkov/ScriptSharpJQueryUI) so ideally the generator is fixed, rather than the result.

**Comment by levi2** [comment]
umm sorry i guess its my way expressing it.

step one create a slider.
SliderObject slider = select.Plugin().Slider(sliderOptions);

step two try to get/set its value.
simply said i failed doing that ... maybe because of stupid or because its not working. i dont know.
so i used the script.literal way to get/set the values.

and yes i think too that generator should be fixed. 
but what am i expected to do about that ? shall i create an issue in the jqueryui project?

hope this was clearer.

**Comment by nikhilk** [comment]
The key question was what is the Script.Literal code you had to resort to... the answer to that was key... so this is still unclear.

**Comment by levi2** [comment]
oic sorry. 
//set slider value
   public static void SetSliderValue(jQueryObject select, int value)
        {
            Script.Literal("{0}.slider(\"option\", \"value\", {1});", select, value);
        }

//get slider value
        public static string GetSliderValue(jQueryObject select)
        {
            string result = string.Empty;
            Script.Literal("{1} ={0}.slider(\"option\",\"value\");", select, result);
            return result;
        }

**Comment by levi2** [comment]
will be redirected to jqueryUi
