### ISSUE TITLE
Jquery-ui Region

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#282]
hey guys,
this might be my fault too, but i could not find a way to define the default region for my datepicker.
used to do it by:

Script.Literal("$.datepicker.setDefaults($.datepicker.regional['en']);");

sorry if this is more a question than an issue.

regards,
 levi

**Comment by nikhilk** [comment]
Are you saying the API is missing from the current import assembly?
Please see https://github.com/igochkov/ScriptSharpJQueryUI - this is the generator. Ideally changes are made there to fix missing APIs.

**Comment by levi2** [comment]
um.
lets put it this way.
i was not able to do what i did with that script.literal statement with the jqueryUI api.

and yes i think too that generator should be fixed. 
but what am i expected to do about that ? shall i create an issue in the jqueryui project?

hope this is clearer

**Comment by nikhilk** [comment]
Yes, I think the right place to follow up is in the jQueryUI project, and perhaps even help fix the generator.

**Comment by levi2** [comment]
will do.
and yes i d love to contribute.

sadly right now every last bit of awake time is in use : /
