### ISSUE TITLE
 stacktrace with method name

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#283]
given any errorhandling scenario:

```
    public void SomeMethod()
    {
        try
        {
            throw new Exception("someerrror");
        }
        catch (Exception ex)
        {
            Window.Alert(ex.StackTrace);
        }
    }
```

the stacktrace that is presented does not contain the method name anymore.
only the errorline in the script.
In the 0.7.5 release there were method names.

Maybe i am missing something.
but i would not know what.
i am making a debug build and use the non minified version of the script.

one might say that this is just an annoyance.
to which i would agree.
but not a minor one when working in larger contexts.

if this turns out to be a question and not an issue please excuse me and let me know what to do.

regards, 
 levi

**Comment by nikhilk** [comment]
I believe this is a problem in IE. In chrome, you do get method names.

**Comment by levi2** [comment]
yes. my bad.

testresults:
- safari / ie dont have any stacktrace.
- mozilla / chrome / opera have stacktrace and methodnames.
  .
