### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#284]
I guess this is not an issue but a question:
given two classes:

namespace Main
{
    using B;

```
public class MainClass
{
    public void MainMethod()
    {
        new AnotherClass().AnotherMethod();
    }
}
```

}

namespace Main.B
{
    public class AnotherClass
    {
        public void AnotherMethod()
        {
        }
    }
}

when compiling i get the error:
Check that your C# source compiles and that you are not using an unsupported feature. Common things to check for include use of fully-qualified names (use a using statement to import namespaces instead) or accessing private members of a type from a static member of the same type.

pointing to the invocation of new AnotherClass().AnotherMethod();

strangely this error is gone as soon as i use the full namespace for b like this
namespace Main
{
    using Main.B;

```
public class MainClass
{
    public void MainMethod()
    {
        new AnotherClass().AnotherMethod();
    }
}
```

}

namespace Main.B
{
    public class AnotherClass
    {
        public void AnotherMethod()
        {
        }
    }
}

in the second example everything is fine an compiles.

Sadly i could not figure out how to make visual studio allways add "full" namespaces when automatically adding namespaces. 
further more i am asking myself what this is actually about. or what to do about it.

any help is appreciated.
levi

**Comment by nikhilk** [comment]
Will be taken care of in a future revamp of compiler. For now, this is going to remain unsupported, so no point in having the issue stick around.

FWIW, its pretty straightforward to simply type "using Main.B" or when using VS and choosing resolve type by adding a using, VS does generate a full namespace.

**Comment by levi2** [comment]
thanks for the answer.

i was not sure if i just did something wrong.
