### ISSUE TITLE
Consider implicit cast operators for built-in collection/array types

### ISSUE THREAD

**Issue by john-pennington** [nikhilk/scriptsharp#288]
mscorelib.dll defines a core API that app and platform writers use as the foundation for S# systems. The API is crafted carefully and colludes with the S# compiler to produce script that runs on top of the S# script runtime. Certain constructs in the API are elided and compile "away" or "down to" something lower level or optimized in the runtime.

After a long time writing S# applications, I am aware that the types:
1. Array
2. ArrayList
3. List&lt;T&gt;

Are all just JS Arrays at runtime. In 0.7.5 and below, the S# runtime augments the JS Array prototype with additional APIs, and in 0.8 it does the same without stepping on the primitive type itself. At development time however, the available API between these types are not equivalent, in particular Array and ArrayList.

In my travels with S#, I have had many occasions to call a S# API which returns an Array or ArrayList only to have to double-cast (from source to object to target) because I need access to the the API of the other type, or I need to return the other type as part of another contract. In particular, an implementation of LINQ query operators that relies heavily on the S# map/filter/reduce APIs provided in the collection types, I have been forced to explicitly cast to get where I am going.

All casts are elided when compiled, so the resulting script is without the cruft. These operations are by and large internal to some specific library or function I am providing, so the casts I am doing there are not aggregious by any means. Still, since these types are truly the same runtime type, each having the full fidelity of the combined APIs as exposed through their type definitions, would you consider adding implicit (preferred) or explicit cast operators to their type definitions in mscorlib.dll so we can avoid extra characters, increase comprehension and save line-length in source code?

As an example, the type definition for List&lt;T&gt; already includes one explicit cast operator:
public static explicit operator Array(List&lt;T&gt; list);

I propose augmenting type definitions in mscorelib.dll with more operators, and preferrably making them implicit (this is using the 0.7.5 syntax with AlternateSignature):

For List&lt;T&gt;:
[AlternateSignature]
extern public static implicit operator Array(List&lt;T&gt; from);
[AlternateSignature]
extern public static implicit operator ArrayList(List&lt;T&gt; from);
[AlternateSignature]
extern public static implicit operator object&#91;&#93;(List&lt;T&gt; from);

For Array:
[AlternateSignature]
extern public static implicit operator List&lt;object&gt;(Array from);
[AlternateSignature]
extern public static implicit operator ArrayList(Array from);
[AlternateSignature]
extern public static implicit operator object&#91;&#93;(Array from);

For ArrayList:
[AlternateSignature]
extern public static implicit operator List&lt;object&gt;(ArrayList from);
[AlternateSignature]
extern public static implicit operator Array(ArrayList from);
[AlternateSignature]
extern public static implicit operator object&#91;&#93;(ArrayList from);

Again, this is available to us today through casts or double-casts, but building it in the type definitions will lead to better comprehension in code that does this.

As an aside, consider the runtime equivalence of the JS primitive Object type and the S# Dictionary (non-generic) type, could we do implicit cast operators (both directions) there as well? That would eliminate (Dictionary) casts and/or the Dictionary.GetDictionary() API, which is runtime-elided.

Has anyone felt these (minor) effects when writing platform code, or is it just me?

**Comment by nikhilk** [comment]
Making the casting easier makes sense... for both arrays and objects. I have debated adding them as well... though in those thoughts I've leaned toward making them explicit cast operators... so that the change in semantics (going from Array to ArrayList for example) is captured explicitly at the source code level. Thoughts on that?

Note ... within an imported type, such as the ones in mscorlib, [AlternateSignature] is not required.

There might be a little bit of a hiccup for going from List&lt;T&gt; to T[] with the current compiler, but certainly something that can/will be addressed as the compiler gets updated.

**Comment by nikhilk** [comment]
I added some converters. Most of them are explicit (when expanding semantics - array to List, or relaxing type constraints ... generic List to untyped array or ArrayList).

Can't do this for Dictionary <-> object conversions as c# doesn't allow defining conversion operators to/from derived or base classes.

**Comment by john-pennington** [comment]
Hey Nik, can't argue your reasoning for explicit operators when expanding semantics or relaxing type constraints.

I kind of hoped that others would weigh in and say it's fair to expect implicit (no pun intended) understanding of the semantic equivalance and common runtime identity of object[], Array, ArrayList and List&lt;&gt; types. There would then be cause for arguing more strongly for implicit cast operators all around. Alas, the issue didn't gain traction with the community so I guess I will abandon that selfish hope.

And yes of course the Dictionary/object cast operator is not legal according to C# spec. I should have remembered this before suggesting such nonsense.

I should apologize for my example having the AlternateSignature decoration and extern keywords. When I write import libraries (and these cast operators as examples of import-style APIs), i use this syntax to avoid having to write a no-op method body. I realize that doesn't match the published convention that your implementation adhears to, and didn't mean to muddy the waters with a non-standard reference example.

Thanks for the updates. I'll close this one out.

**Comment by nikhilk** [comment]
Hey, no problem about the Dictionary/object cast operators. I actually tried it and that is how I found out about the c# spec constraints. I wouldn't expect anyone to carry around the c# spec in their head :)

No need to apologize on the extern thing either. Your suggestion was accompanied by concrete details, and that was good.
