### ISSUE TITLE
Knockout Extenders

### ISSUE THREAD

**Issue by aschoenebeck** [nikhilk/scriptsharp#291]
Id like to use extenders with some of my Knockout observables like here: http://knockoutjs.com/documentation/extenders.html

I've understood that I need to add the extender function name via Observable<>.Extend() but I'm not sure where to define the extender function. In javascript you normally add it to ko.extenders.

**Comment by nikhilk** [comment]
See how jQuery plugins are written (there is a template for creating them to see the full pattern, but at the very basic level, they are static classes with methods that extend jQuery.fn at runtime). The same would apply to knockout extenders adding to ko.extenders.

**Comment by Sam7** [comment]
@aschoenebeck 
Did you figure it out?
If so, do you mind posting an example?
Thanks
