### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by edgeroad** [nikhilk/scriptsharp#295]
Hi nikhilk,
consider the code:

```
C ref = new C();
ref.Test()
```

where:

```
 public class A {
     public virtual Test() {
         // do something
    }
}

public class B : A {
    public override Test() {
        base.Test();
        // do something
    }
}

public class C : B {
}
```

The problem is in base.Test(): S# searches the base-code for B.Test() in the context of C so you get B.Test() again (with loop).

S# use ss.base() in generated code:

```
function base(instance, method) {
  return instance.constructor.$base.prototype[method];
}
```

I have tried this successfull workaround in ss.base() :

```
function base(instance, method) {
    var fn = (instance.constructor.$base ? instance.constructor.$base : instance.$base);
    var mt = fn.prototype[method];
    return (mt !== instance[method] ? mt : base(fn, method));
}
```

but I am sure you can do better!

thanks nikhilk

**Comment by nikhilk** [comment]
That's a reasonable fix actually. The only other fix that comes to mind right now is to add a 3rd parameter to base which is the current type surrounding the call site, and change the compiler output to include that 3rd parameter. Instead your script change accomplishes that without a compiler change...

**Comment by edgeroad** [comment]
thanks nikhilk

**Comment by andekande** [comment]
Unfortunately didn't solve this scenario:

``` csharp
public class A
{
   public virtual void DoFirst()
   {
      Window.Alert("A First");
   }
   public virtual void DoSecond()
   {
      Window.Alert("A Second");
   }
}

public class B : A
{
   public override void DoFirst()
   {
      Window.Alert("B First");
      base.DoSecond();
   }
}

B classB = new B();
classB.DoFirst();
```

Outputs "A First" but then hangs in ss.base() because baseType == null
