### ISSUE TITLE
Lib.Node.Mongo.Nuspec file is missing 

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#298]
Lib.Node.Mongo.Nuspec file is missing under zipx\packages resulting in the following error:

Error 1 The command "....\tools\bin\nuget pack Packages\Lib.Node.Mongo.nuspec -OutputDirectory ....\bin\Zip\Packages -NoPackageAnalysis" exited with code 1. C:\sd\scriptsharp-cc\src\ZipX\ZipX.csproj 83 5 ZipX

**Comment by Mike-E-angelo** [comment]
+1. :)

**Comment by nikhilk** [comment]
Fixed...
