### ISSUE TITLE
Ability to embed text resources.

### ISSUE THREAD

**Issue by duckmaestro** [nikhilk/scriptsharp#30]
This is related to another user's question: http://stackoverflow.com/questions/5857470/clean-way-to-include-html-in-script-projects, and useful for my own code: https://github.com/duckmaestro/Sharp-UI.

For the single-page apps I build, I find it it tedious and error-prone to write scripts that are not tightly coupled with the CSS and HTML that they target. Whether it's dealing with difficult to tame browser cache behavior, or just not having a great encapsulation model for building out complex UIs, I decided to replicate something like the Web User Control model, where "controls" can declaratively instantiate other "controls", where ID'd elements are bound to correspondly-named fields, and, taking it a step further, where locally targetted CSS rules are declared alongside your control's HTML, rather than in a .css file in a completely separate area of your codebase. The "web user control" (WUC) sort of paradigm that I've mimicked has so far given me a lot of mileage and I find it immensely useful for the above stated goals/reasons. It is also useful because I can compile an entire "app" or area into a single JS file, for a single download (faster), and guarenteed consistent HTML/CSS/JS(CS) (fewer reported one-time "bugs" from customers).

At this moment, to get HTML in the Script# output, I use a file naming convention of .html and .html.cs, and compile both files as C#. Both declare the same partial class, and derive from a base class that knows how to locate the HTML string constant. This works well enough except that I must use single-quotes, there is some ugly C# code to maintain at the top and bottom of my HTML files, and there are some other minor limitations as well. 

There is potentially a greater solution that could be developed as part of Script# officially (a WUC-like paradigm with designer files etc), though I suspect this strays too far from Script#'s mission and becomes too specialized. So as for the here and now, it'd be great (for in general too) if text resouces could be "embedded" into the JS file for retrieval at run-time. This would allow my HTML files to use the full range of syntax, and avoid some of the other limitations associated with the current HTML as CS build trick.

**Comment by nikhilk** [comment]
Did you try embedding text resources in resx?

The resx model can be extended to any other file format as well - a Visual Studio single file generator can take as input any file and produce any other file, including c# code. That is in fact how resx files are handled. They produce a resource class that gets compiled into the generated script.

I can provide guidance if you'd like to pursue this as a complementary project, evolve the idea a bit, and then evaluate how it might fit in into the script# project.

More info on single file generators - http://msdn.microsoft.com/en-us/library/bb166817(v=VS.100).aspx

I can also provide the code for the resx implementation before it gets added to github if you're interested in picking it up.

**Comment by nikhilk** [comment]
As I think some more... would this be generally useful?

Say I have a file Foo.xyz.htm alongside Foo.cs in a Bar folder - it can be associated with a generator that creates the following:

```
namespace Bar {
    partial class Foo {
        private const string xyz = "... contents of Foo.xyz.htm ...";
    }
}
```

The generator doesn't care about which file/format it is associated with - it just creates a string. This allows you to use the default editor for the file. In fact, it isn't even script# specific!

**Comment by duckmaestro** [comment]
I would find that useful in general, yes. Also I think it would good if the project's default namespace were used for the inference of the generated namespace. For instance if the csproj namespace were `WidgetsInc`, I would want the output to be `namespace WidgetsInc.Bar` in your example. Also, for simplification in a single resource per class situation, it would be convenient (I think) if Foo.htm (no infix) assumed a default name for the output constant, such as "DefaultContent" (`WidgetsInc.Bar.Foo.DefaultContent`).

However, with regard to my WUC-inspired setup specifically, I'm actually very interested in what you mentioned earlier about a single file generator. It sounds like I should be able to go so far as replicate the ".designer.cs" sort of output, complete with auto-generated fields for locally ID'd elements. And of course I would also be able to define the HTML string constant in the most appropriate way via this method as well. Some source for your resx implementation as offered would be great to give me a head start.

And I am definitely open to guidance/opinion on ways I can better shape "Sharp UI" to complement Script# going forward.

**Comment by nikhilk** [comment]
Check out https://gist.github.com/952879 for a snippet/sample.

Yes, the single file generator gets the full namespace, so you'll get the root namespace included.

Regarding "DefaultContent" - this is convention space, and as such everyone has an opinion... but yes, a default seems reasonable when one isn't specified in the file name. I'd claim a default such as "markup"/"html" for a .htm, and "style"/"css" for a .css would potentially be more general, but its really your choice.

**Comment by duckmaestro** [comment]
That is fair. 

Thanks for the code snippets... I'll should be able to run with this...

**Comment by juye** [comment]
This thread got me thinking about T4 templates. Here is a quick one that I knocked together which is working just fine for me.

https://gist.github.com/953864

Pop this in your script sharp project (you will want to customise the way it writes out your classes) and it will read all of your html files and generate the c# classes for you. It's doesn't figure out the namespaces as it walks the directories but could be a good starting point.
