### ISSUE TITLE
UnitTest.vstemplate still points to ScriptSharp.Testing 0.7.5 instead of 0.8

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#301]
I ran into weird issues all night and thought it was something related to having 0.7.5 installed initially causing the test framework to still reference it in 0.8.

However, I just noticed that we're still referencing ScriptSharp.Testing 0.7.5 in Other\ZipX\ProjectTemplates\UnitTest\UnitTest.vstemplate instead of 0.8.

**Comment by theoutlander** [comment]
Btw, how can I tag issues with labels so that this shows up in the bug filter?

**Comment by nikhilk** [comment]
Good catch... committed the fix for it.
