### ISSUE TITLE
Test JS file not generated when namespace doesn't end with '.Tests'

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#302]
This might be expected behavior, but it doesn't make sense since we're deriving from TestClass. The compiler should generate the test.js file regardless of the namespace. 

That namespace logic when the class is added in a nested folder structure (Tests\Models) where VS will assign a namespace like **[DefaultNamespace].Tests.Models**.

**Comment by nikhilk** [comment]
The Tests namespace is for helper code that doesn't derive from TestClass. For example, a mock implementation of an interface. For example: https://github.com/nikhilk/scriptsharp/blob/cc/samples/Photos/PhotoList/Tests/MockFlickrService.cs

I was pretty sure classes derived from TestClass can themselves be in any namespace.

The logic around https://github.com/nikhilk/scriptsharp/blob/cc/src/Core/Compiler/Compiler/MetadataBuilder.cs#L815 needs to change to account for Tests namespaces with sub-namespaces to include a contains check as well.

**Comment by theoutlander** [comment]
The code change makes sense. It means that any class that derives from TestClass needs to be in a namespace that has the word Tests. Does that sound like the expected behavior??

**Comment by nikhilk** [comment]
Yes, that is expected behavior - namespace ends with ".Tests" or contains ".Tests." ... change made and committed in 2435d8d874712fa478db1d69aeaea3cc7dbed949.
