### ISSUE TITLE
Sample Questions and Issues

### ISSUE THREAD

**Issue by Mike-E-angelo** [nikhilk/scriptsharp#304]
I've been digging into the Samples to learn about Script#.

1) It appears that the TODO Sample doesn't work as expected in runtime.  The application does load and you can type an entry, but in both IE10 and FireFox, the entry does not commit when the user presses Enter.
2) The Fishtank Sample does not render properly in IE10.
3) The KOWorld Sample references Knockout 2.1, and the release version on the project's site is 2.2.  Should this be updated?
4) The KOWorld has a lot of missing script files in the /Scripts/ folder.  Is this a known issue?  Perhaps there's a missing/broken build command?

I would be more than happy to submit a bug fix for these issues.  Please provide guidance and I'll check it out.

**Comment by nikhilk** [comment]
Did you let nuget package restore do its thing? That brings in scripts.
As far as I know, these should run in IE as well.

**Comment by Mike-E-angelo** [comment]
Ahhh... kicking off the newb-webs here.  I thought I had it enabled, but apparently not.  That fixed it.  Thank you for your patience as I get acclimated.
