### ISSUE TITLE
Cloud9 IDE (c9.io) support

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#307]
I'm curious about what it would take to enable S# projects in the web based IDE c9.io? I guess it's something that they might have to start supporting.

**Comment by nikhilk** [comment]
Does c9 provide an experience for .net (and more specifically c#) projects (editing, intellisense, etc.), and nuget and msbuild support? Those would be the main pre-requisites for the experience as it currently exists to work in that environment.

**Comment by theoutlander** [comment]
AFAIK, they don't support nuget and probably don't give control on the build side of things (to plugin ssc for instance). Will investigate when I get a chance and close this issue for now.
