### ISSUE TITLE
Grid support on ScriptSharp

### ISSUE THREAD

**Issue by binydev** [nikhilk/scriptsharp#309]
I am trying to develop application which need data Grid, when I search on the internet I get "jqxgrid" nice but, due to I'm using script# for a lot of reason, I am not willing to write direct script which makes my application unmanageable. 
1. does script# support "jqxgrid"? 
2. does any grid alternative that is supported by script#?

plz I need help!

**Comment by nikhilk** [comment]
You'll need to create an import assembly and declare the appropriate APIs to use it. See the existing import libraries in the sources for example of how to go about doing it, as well as the import library project template.

**Comment by binydev** [comment]
Thanks!
