### ISSUE TITLE
System.Math fails Script# compiler

### ISSUE THREAD

**Issue by southpolenator** [nikhilk/scriptsharp#313]
Having System.Math.Sqrt function call in code fails Script# compiler without any error message.

Math.Sqrt function call works if System is specified in uses list.

**Comment by john-pennington** [comment]
Hey southpolenator, S# does not support fully qualified type names in source code. it's just a by-design limitation of the S# compiler. The original S# documentation (now outdated) makes mention of this. The solution is to qualify types via 'using' statements as you allude to above.

**Comment by nikhilk** [comment]
I'm inferring from the described behavior that you have an older version of the compiler. Let me know if that isn't the case. If you can update, that would probably help a bit in easier pinpointing of code when such an error happens.

The newer version of the compiler doesn't [yet] support namespace-qualified names, but doesn't "fail" either. Instead it flags the specific line of code with an error, and even suggests checking for namespace-qualified names as this is probably the primary cause for these kinds of failure at this point.

**Comment by southpolenator** [comment]
I downloaded Script# 0.7.5.1 and created new project. I was importing files from old Script# project into it and added new files from another C# project. After compiling I was only getting DLL built and Script# compiler was silently failing. I figured out that it must be because of files I added from C# project so I started removing files from Script# project until I got error. Error was on line containing System.Math.Sqrt and after I removed System it worked. I found on multiple other places the same error and afterwards Script# compiler was generating correct messages.

I'm not sure if this silent failing was because I had another unsupported error message. I was calling function from two dimensional array:

MyClass[][] table = ...;
NewMyClass[][] newTable = ...;

newTable[i][j] = table[i][j].Transform(); // This is unsupported

// But this is supported:
MyClass item = table[i][j];
newTable[i][j] = item.Transform();

**Comment by nikhilk** [comment]
Please log a different bug for the different issue, so its easier to track.
