### ISSUE TITLE
IndexedDB Support

### ISSUE THREAD

**Issue by aschoenebeck** [nikhilk/scriptsharp#316]
Hello friends!

In ScriptSharp I like to store data browserside with WebSQL. Unfortunately WebSQL (http://www.w3.org/TR/webdatabase/) is discontinued in favour of IndexedDB (http://www.w3.org/TR/IndexedDB/).

Now I'd really like to see IndexedDB implemented in ScriptSharp. It's becoming mainstream now: http://caniuse.com/#feat=indexeddb

Cheers,
Andreas

**Comment by michaelaird** [comment]
It's not as fancy as IndexDb but there is already support for Local Storage (http://caniuse.com/#feat=namevalue-storage).

You access it through Window.LocalStorage.GetItem or Window.LocalStorage.SetItem.

Michael.

**Comment by nikhilk** [comment]
Yep, its certainly interesting ... if you're up for getting it started and filling in the missing types in Script.Web.dll, that would be awesome.

**Comment by aschoenebeck** [comment]
Okay I have implemented the asynchronous API. Sent pull request https://github.com/nikhilk/scriptsharp/pull/319.
