### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by kzaher** [nikhilk/scriptsharp#320]
Hi, this won't compile

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Client
{
    [ScriptImport]
    [ScriptIgnoreNamespace]
    [ScriptName("wtb")]
    public class Something
    {
        String three = 12.ToString();

```
    //[ScriptAlias("weStarted")]
    //[ScriptField]
    public String GetMeHere()
    {
        Func<int, String> append = (int number) => { return number + three; };

        int[] whatIsThis =  new int[2] { 1, 2 };
        foreach (int three in whatIsThis) {
            return append(three);
        }

        return @"asdas";
    }
}
```

}

**Comment by nikhilk** [comment]
A script import shouldn't be placed on a class with code you want to have compiled. That is only meant for defining existing APIs you want to reference. I'd recommend checking out the samples.

Also, what is the exact failure/error. I am going to close this unless there are more specifics.

**Comment by kzaher** [comment]
Hm. Maybe i wasnt clear enough :) Ssc.exe reports syntax error while parsing lambda expression :) Attributes dont matter in this case. It's parser error. I've posted a bad example, i realize that now, but can it parse lambda expressions and convert them to javascript? What syntax does it support, i couldn't find info anywhere. I've seen you've implemented top down parser by yourself so I'm concerned that such strange problems can arise even for valid c# code.

**Comment by nikhilk** [comment]
Yep, being more precise than "won't compile" will certainly get you better response. Use the delegate syntax:

```
Func<int, String> append = delegate(int number) { return number + three; };
```
