### ISSUE TITLE
Generic error

### ISSUE THREAD

**Issue by roll314** [nikhilk/scriptsharp#322]
This code pattern no compile
 void MyFun<TData>(Action<TData> someAction) {
// do somthing
}

But error messages is no.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by LucasOromi** [comment]
Try with Delegate and then call Invoke()

void MyFun(Delegate someAction) {
someAction.Invoke();
}

**Comment by roll314** [comment]
Thx, its work.

**Comment by roll314** [comment]
A bit more complicated:

  public void MyFun < TData > (Action < TData > onSuccess)
        {
            // do somthing
        }

....

MyFun< string >(delegate(string data)
            {
                Script.Alert(data);
            });

still silent fault compilation

**Comment by nikhilk** [comment]
At the moment you cannot declare generic types and methods in your code that is compiled by the script# compiler. You can only declare those types within separate import assemblies that aren't being compiled to script, but rather just containing API declarations.

**Comment by roll314** [comment]
Could you explain your thought?

**Comment by nikhilk** [comment]
This is a limitation in the current implementation.
