### ISSUE TITLE
0.8 preview release disappeared after GitHub removed downloads

### ISSUE THREAD

**Issue by sidecut** [nikhilk/scriptsharp#328]
As you know, GitHub removed downloads several weeks ago, thus removing the only location from which to download the 0.8 preview. I've checked scriptsharp.com and there's no mention of it, the NuGet package is 0.7.5.1, and there is no 0.8 branch or tag in Git. Is there another location from which 0.8 can be downloaded? Thanks!

**Comment by nikhilk** [comment]
Need to put out that build! Things have been crazy busy...

The 0.8 branch is the "cc" branch.

**Comment by sidecut** [comment]
Thanks! I'll investigate that branch.
