### ISSUE TITLE
Where should small libraries reside in the source?

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#333]
Occasionally, I use libraries that are literally a function or two and would like to port those over as they're still useful. For example: https://github.com/einars/js-beautify - It takes a JS string or file as an input and spits out JS that's beautified or a library for obfuscating JS.

I don't like the idea of project an individual project with simply one file exposing a couple of functions. Where should such kind of libraries reside in the source path? Should we create a project for such utilities?

**Comment by nikhilk** [comment]
This thought in some ways relates to the previous issue and discussion there...

What about having a nuget package (yes, its still a bit heavy weight) for these snippet-sized imports. That way, one can have a custom solution-scoped import library project, and nuget their way to getting useful functionality. I'd rather there not be a single kitchen-sink project that collects snippets from all over the map and lands stuff you don't want into your solution/class browser/intellisense.

I really wish VS code snippets had a more capable extensible backend... or something like a gist importer, and then these could be much more lightweight gists. These discussions are great in that they show how much the experience could be improved. And then they immediately after raise the question of how to get there :)

The reason I say related to previous issue, is perhaps it is also a source-centric solution to work in progress import libraries that are even earlier than the threshold of sharing and converting into an actual project.

**Comment by theoutlander** [comment]
Yes, it does relate to the other discussion in some ways but I'm not sure if it makes sense to combine the two as they're talking about slightly different issues.
- I think a utilities nuget might be the way to go (although the Gist importer is an interesting idea).
- We should also track Feature Requests, List of features being implemented and a Roadmap. 
- It would be nice to release updated nugets for the CC branch on a daily basis
- Also, I'd like to contribute some useful libraries/algorithms, but I don't know they're out of scope for this repo. For instance, a pub/sub observer, extensible logger that has providers for console logging, server logging, test hooks, etc. It will make the S# library quite rich for SPA's.
