### ISSUE TITLE
Windows 8 WinJS support

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#337]
I havn't done any Windows 8 programming yet, but figured it allows writing apps entirely in JS. 

Is this library (http://msdn.microsoft.com/en-us/library/windows/apps/br229773.aspx) including other namespaces worth porting over?? I guess it would also require a Win8 script project type?

**Comment by nikhilk** [comment]
Potentially interesting... in fact script# had some Windows-related APIs that applied to gadget scenarios.

Question is whether this is interesting to enough people ... specifically would those wanting c# automatically just always use c# + xaml? Personally I've sometimes wished a bit for the HTML UI stack but with a c# programming model, so this would certainly be interesting from that perspective.

As far as project stuff goes, I think it would be interesting to understand the msbuild flow used to create and package a win8 app, and to interject a script# step in between that produces the actual script to be packaged.

**Comment by nikhilk** [comment]
Also there are two parts to this - the WinRT APIs and the WinJS APIs. The former can be used without WinJS. We should keep the separation intact.

**Comment by theoutlander** [comment]
Should categorize this into an ideas bucket of some sort. Closing for now.
