### ISSUE TITLE
Stack<T> Conflict

### ISSUE THREAD

**Issue by rjamesnw** [nikhilk/scriptsharp#340]
This is a new ScriptSharp project created via "Add New Project" in VS.  The Stack<T> apparently is in conflict between the two assemblies.  I need System for Regex.

Error   175 The type 'System.Collections.Generic.Stack<T>' exists in both 'C:\Data\Visual Studio\Projects\MyProject\packages\ScriptSharp.0.7.5.1\tools\mscorlib.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.dll'    C:\Data\Visual Studio\Projects\Common Libraries\Common\Utilities\Utilities.cs   846 6   Common.JS

**Comment by theoutlander** [comment]
The problem is that you're referencing a .NET assembly. You need to remove the reference to System.dll. It could have been automatically added by Resharper (if you're using it) or if you added a reference to it manually or if you tried to add a non-s# class file.

Either way, just remove the reference to system.dll in the project references.

For Regex, you simply need the using System statement which is part of mscorlib (in 0.8) ... don't recall if it's a different library in 0.7.5, but it should be included by default.

**Comment by rjamesnw** [comment]
Ok, thanks.  Is there official documentation anywhere?

-jw
(sent via iPhone)

**Comment by theoutlander** [comment]
Documentation is being worked on. Let me know if you have any suggestions/requests and I can try to work on something. In the meanwhile, I'm happy to help you get started.

You can check out the samples folder [here](https://github.com/nikhilk/scriptsharp/tree/cc/samples). For high-level details on what each one addresses, look at the sample section in [Repository Notes](https://github.com/nikhilk/scriptsharp/wiki/Repository).

Note that this is referencing the CC branch (which is 0.8 RC). You can find something similar on master branch (0.7.5), but 0.8 is way better IMO.

**Comment by rjamesnw** [comment]
Ok, thanks.  I'm working on a Twitter Bootstrap library for use in a site I'm building, and thought I'd try building it with script# (so far so good).  I noticed the bin also contains a DLL of my project I was able to reference in another .net 4.0 project - this is pretty cool, do I've also created a second script# library to help share common validation logic - among other utilities - between client and server. :)

-jw
(sent via iPhone)

**Comment by theoutlander** [comment]
I don't think you can use the dll in another project if it references S# libraries. How is it working for you?

**Comment by rjamesnw** [comment]
For doc suggestions, all is needed is a mapping table of JavaScript objects, functions, and properties on one side, and the .net objects with strong type details on the right. Some other small details might be nice - for example, does the parse methods throw exceptions, or return NaN, but how can parseInt return NaN when it returns an int!? ;) I think once the basic mapping is made, there's enough JavaScript docs to learn the rest - you shouldn't need to write another JS doc. :)

-jw
(sent via iPhone)

**Comment by rjamesnw** [comment]
... Speaking of which, once I get a handle on it all, I may create some docs  myself eventually, and post it later.

-jw
(sent via iPhone)

**Comment by rjamesnw** [comment]
Well, I was able to reference it fine, just haven't compiled and ran it yet. :) I was able to explore the objects in it.

-jw
(sent via iPhone)

**Comment by rjamesnw** [comment]
I thought so as well, and I tried to remove it, but then I get this error:

Error      1              The type or namespace name 'Text' does not exist in the namespace 'System' (are you missing an assembly reference?)

… on this line:  using System.Text.RegularExpressions;

If I remove that line, and just keep the System reference, the system can no longer resolve “Regex”.  I downloaded the latest version for MVC – is there a different DLL for Regex?

**Comment by nikhilk** [comment]
There was a mention of Bootstrap - something has been started here (https://github.com/dealproc/scriptsharp/tree/master/src/Libraries/Bootstrap) ... I believe its not 100% complete, and that since then there might have been a newer version of Bootstrap with some changes/additions. However, it might be interesting to take a look and see if you can steal anything from it, to jumpstart your effort.

On the other error, indeed in the script# mscorlib, System.Text.RegularExpressions doesn't exist. The script RegExp type is represented by System.RegExp correspondingly.

**Comment by rjamesnw** [comment]
Ok, I still do not see RegEx.  I have Script.jQuery, Script.Web, and ScriptSharp references, and there is no RegEx type anywhere to be found (Visual Studio will not even resolve it).

**Comment by rjamesnw** [comment]
There is no “System.RegExp”. I have script sharp 7.5.1, and version 7.5 of Script.jQuery and Script.Web. That name space doesn’t exist.

**Comment by rjamesnw** [comment]
Oh, I see what’s going on, I think.  The DLL version via NuGet has the old long name still. :) RegEx doesn’t exist yet.  Is there a more recent update?

**Comment by theoutlander** [comment]
If you're using the master branch (0.7.X), I think it's the [RegularExpression](https://github.com/nikhilk/scriptsharp/blob/master/src/Core/CoreLib/RegularExpression.cs) class.

If you're on the latest CC branch, it is the [RegExp](https://github.com/nikhilk/scriptsharp/blob/cc/src/Core/CoreLib/RegExp.cs) class.

**Comment by rjamesnw** [comment]
How is it working?  Easy, when I compile a Script# project, there’s a .DLL in the bin folder.  Turns out it’s a regular .NET (probably 2.0) compile of the code. I just added a project reference to the Script$ project.   I am able to call my Button class to create the HTML for the Bootstrap button, then I simply used Html.Raw() to write to the output stream.  I’m looking forward to being able to use the compile JavaScript to do the same client side if ever needed. :)

I had a general utilities C# file I use in all my projects, and I tell you, it was quite fun (not really ;)) trying to make it compatible (almost 2500 lines). LOL.  I had compiler directives that supported .NET and Silverlight, and now Script#. ;) So far I have two Script# projects: A “Common.JS” one for the utility methods, and “UI.Bootstrap” to render HTML on both the client and server sides. :)

I had one beef though: I had an error where I was accessing the private member of a class object passed to a parameter while within the SAME class, and there was no line info. I had no idea where the issue was for some time (just gave some general error).  That is easily a common issue and should probably have better error reporting. In fact, there was no error regarding the non-support of generic methods until much later on, when I suddenly got a bunch of weird identifier errors. :)

Anyhow, all looks good thus far, thanks,

James

**Comment by rjamesnw** [comment]
I’m not on a branch, I used the DLL downloaded via NuGet.

**Comment by theoutlander** [comment]
That's 0.7.5+ I think, so you should be looking for RegularExpression (if I remember correctly from looking at the source). Try browsing the API in the IDE to see where it is.

If you want to update to the latest, there are two ways to do it:
1. Enlist in the CC branch 
2. Download the current code base as a zip from [here](https://github.com/nikhilk/scriptsharp/archive/cc.zip)

Here are some steps that might get you started (I will try to document them soon)
- **Build:**
  - Build the CC project in Release mode. 
  - Then, under cc\bin\Zip\Packages should have the latest Nuget packages locally.
  - And, cc\bin\ScriptSharp.vsix will have the studio extensions / templates for 0.8
- **Uninstall Previous Version**
  - You will first need to uninstall the old version of S# packages associated with your existing project by right clicking your solution->Manage Nuget packages and removing all installed packages for s# 0.7.5
  - Next, go into VS->Tools->Extensions and Updates, Installed->Templates, Uninstall S# templates (this is what shows up when you create a new project)
- **Install New Version:**
  - Then go to your project solution->Manage Nuget Packages->Settings (at the bottom left in VS2012)
  - Add a new package source and point it to the cc\bin\Zip\Packages folder (which has your locally built 0.8 pacakges)
  - Once you click ok, in the Manage Nuget Packages window, go to Online tab and select your local package source that you defined above and install the latest stuff.... 

Please note that you might need to follow the same process for future updates, but only remove and add specific packages that you're interested in.

Let me know if this helps and I can use this as a starting point for the help doc on this topic.

**Comment by nikhilk** [comment]
Some of this is listed on https://github.com/nikhilk/scriptsharp/wiki/Building-and-Testing ...

**Comment by theoutlander** [comment]
Oh man, I should have looked at the wiki first! I suppose I can try to make a nicer page with step-by-step instructions and screenshots.

**Comment by rjamesnw** [comment]
:)
