### ISSUE TITLE
Json deserialization

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#345]
I tried using json deserialization in the following way:
created 2 classes (server/client)
public class SomeClass 
{
public int SomeInt;
public string TestMethod()
{
return "test";
}
}

on server side i used javascriptserializer to create a string of one instance of class SomeClass 

on the client side i tried to use:
SomeClass  deserializedResult = Json.ParseData<SomeClass >(input);

doing that i faced two problems:
1. "SomeInt" was correctly serialized as "SomeInt" but not recognized on client side since it starts lower case in js (someInt).
2. when calling the method TestMethod of the instance of the deserialized result of SomeClass i get the error "unkonwn method" 

now the first problem was easy to solve.
but the second one was virtually onsolvable to me without merely recreating the whole class.

regards,
 levi

**Comment by nikhilk** [comment]
Script# is a compiler, not a framework, so it doesn't abstract things. You get the behavior of the underlying environment. Specifically JSON.parse returns a vanilla object.

To model the vanilla JSON object as a strong type you can declare a structural type. See the examples in the samples - eg. the AroundMe sample, and how the photo json response from Flickr APIs is modeled.

If you want to use your type around the json data which has properties, and methods, you'll need to instantiate your type, and copy over the raw json data into it.
