### ISSUE TITLE
Release build error with NuGet.exe

### ISSUE THREAD

**Issue by xersoft** [nikhilk/scriptsharp#346]
When I try to build the release version so I can get the .vsix I am getting an error: 

The command "....\tools\bin\nuget pack Packages\Runtime.nuspec -OutputDirectory ....\bin\Zip\Packages -NoPackageAnalysis" exited with code 1

So far I've tried to update the NuGet.exe to the latest version but as expected that didn't solve the issue.

**Comment by theoutlander** [comment]
Don't quite understand what's going on. Can you zip your solution and post it somewhere so I can take a look?

**Comment by nikhilk** [comment]
I just realized I didn't commit some files (as a result of some .gitignore settings). I'll commit them later today.

The build uses nuget.exe that is already in the repository, so upgrading nuget won't help. Odd that nuget didn't report the files being referenced as not existing instead.

**Comment by nikhilk** [comment]
Please try now ... just pushed the missing files. Sorry for the inconvenience.
