### ISSUE TITLE
Where do I set DeploymentPath?

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#349]
We were running a 0.8 build from 3 months ago that allowed us to set DeploymentPath in the targets file.

Your recent change in https://github.com/nikhilk/scriptsharp/commit/21af186664764be30c0afb073e0da0347bd3312b removed that functionality. Do we use OutputPath instead? I'm looking to output the JS file into my web app's script folder. Thanks!!

**Comment by nikhilk** [comment]
Per the description associated with that commit:

Deployment via msbuild task in web app project
1. Add ScriptSharp.Runtime nuget package to web app project
2. Add reference to client projects via project-to-project reference

**Comment by theoutlander** [comment]
Oh wow, thought that's what I had read but didn't think we could reference a S# project from ASP MVC yet.... I had to revert to the older build unfortunately since we have a demo coming up, but I'll try it in another 2 weeks. Thanks!

**Comment by ramnkl** [comment]
Thanks Nikhilk,

after added the ScriptSharp.Runtime in MVC web project I'm getting below error.

Error   1   The attribute "KeepDuplicates" in element <Content> is unrecognized.    WebApplication1
