### ISSUE TITLE
ss.loader.registerScript includes "core" and other assembly referred in that project

### ISSUE THREAD

**Issue by chandramuralis** [nikhilk/scriptsharp#35]
After migrating from 0.6.3 to 0.7.1.0, the generated javascript code includes [core] in the registerScript function call. It also includes some other assemblies that are referred in that project. Below is the code generated in two seperate js files

ss.loader.registerScript('TouchMini', [core], executeScript);

ss.loader.registerScript('Framework.Mobile.Touch', [core,Framework,TouchMini], executeScript);

While executing the page in browser I get the below exception
Uncaught ReferenceError: core is not defined

**Comment by stevehobbsdev** [comment]
If you have a look in your Properties folder iinside the project there should be a file which ends in .script like this:

[your project name].script

.. which contains some template script used by ScriptSharp when generating your javascript. It seems this file was changed in the new version and should now contain the following content:

```
//! #= ScriptFile ##
//
(function($) {
#include[as-is] "%code%"
})(jQuery);

//! This script was generated using Script# v#= CompilerVersion ##
```

If you replace the contents of that file with the content above (assuming you haven't modified that file yourself) the error should be resolved. I had this issue today and this is what I did to fix it.

When you create a new project using Script# the file will contain the correct content, but upgrading an existing project from an older version raises this issue.

**Comment by chandramuralis** [comment]
Thanks. I followed your approach and figured out the code you pasted is valid for "jQuery Script library" template. For regular "Script Library" the code should be like below

<pre>
//! #= ScriptFile ##
//

(function() {
#include[as-is] "%code%"
})();

//! This script was generated using Script# v#= CompilerVersion ##
</pre>


It would be better if we could do this automatically while migrating to new version.

**Comment by stevehobbsdev** [comment]
Ah ok, I didn't consider the different project types. Thanks for pointing that out!

**Comment by nikhilk** [comment]
It can't be done automatically, easily. The .script file is there for folks to customize... and it could very well have been customized and potentially even changed drastically.

Unfortunately no time/resources to build a project migration tool...

And yes, different project types have different script templates - eg. the windows sidebar gadget template is also different.
