### ISSUE TITLE
Enumerator / Enumerable

### ISSUE THREAD

**Issue by jimmygilles** [nikhilk/scriptsharp#355]
Hello,

I am not sure if enumerators are supposed to be supported or not ? But I found 2 problems.

Example:

``` javascript
public class MyClass
{
    // ...
}

public class MyEnumerator
{
    public MyClass Current
    {
        get { return _current; }
    }

    public Boolean MoveNext()
    {
        // ...
    }

    public void Reset()
    {
        // ...
    }
}

public class MyEnumerable
{
    public MyEnumerator GetEnumerator()
    {
        // ...
    }
}
```

1)
If **MyEnumerator** inherits **IEnumerator<MyClass>**, Visual Studio fails when compiling the solution (_Rebuild Failed_).
It seems to work if the class inherits **IEnumerator** but, in that case, **Current** returns an object which is not great.

2)

If I use a foreach on the enumerator, the JS code is something like that:

``` C#
foreach(MyClass myClass in new MyEnumerable())
{
    // ...
}
```

``` javascript
var $enum1 = ss.IEnumerator.getEnumerator(new MyEnumerable());
while ($enum1.moveNext()) {
    var item = $enum1.current;
    // ...
}
```

As we can see here, **current** is a field.
But the **Current** property of **MyEnumerator** is converted to
**get_current: function MyEnumerator$get_current() {**
which is a function ; so **current** does not exist.

I didn't try with S# 8.0, maybe it is already fixed?
Thank you very much.

**Comment by theoutlander** [comment]
Is the problem that Current is showing up as get_current() instead of current? 

Try marking it with the ScriptField attribute:

```
[ScriptField]
public MyClass Current
{
    get { return _current; }
}
```

**Comment by nikhilk** [comment]
On the first bit - you do have to implement the interface and does mean you have to have an object current property. Until you can implement the generic version (not yet)

On 2nd one, seems like a mismatch of compiler/mscorlib/runtime script. This definitely worked. In the new version (0.8) enumeration is handled differently.

**Comment by jimmygilles** [comment]
Hello for 1) the generic was missing in my comment.
I wanted to say :
"If MyEnumerator inherits IEnumerator&lt;MyEnumerator&gt;, ..."
instead of
"If MyEnumerator inherits IEnumerator, ..."
Sorry.
So ok, I will wait the generic version to adapt my code.

2)
Ok, so until I am on 8.0 I have a workaround : I call the while (enumrator.MoveNext()) { ... .Current; }; instead of using the foreach.

Thanks!

**Comment by nikhilk** [comment]
2) foreach should work without workarounds. Essentially all three - compiler, mscorlib, and runtime script need to be in sync. At some point all of them were set up to produce a .get_current() call, and some point later, all of them were updated to generate a simpler .current field lookup.
