### ISSUE TITLE
The Samples do not build

### ISSUE THREAD

**Issue by thulka** [nikhilk/scriptsharp#356]
Upon package restore I get

Error   1   Unable to find version '0.8' of package 'ScriptSharp'.  H:\dev\reps\github\scriptsharp\samples\AroundMe\packages\nuget.targets  14  5   Twitter

**Comment by theoutlander** [comment]
Before you can run the samples, you need to build and install s# v0.8 by following directions @ https://github.com/nikhilk/scriptsharp/wiki/Building,-Installing-and-Testing.  There's also a build that @nikhilk has put out on dropbox @ http://dl.dropbox.com/u/26621494/Releases/ScriptSharp.0.8.zip as mentioned in http://stackoverflow.com/questions/15614725/when-will-scriptsharp-0-8-be-the-official-build. Hope that helps.
