### ISSUE TITLE
jQueryObject is missing overloads on replaceWith

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#36]
I've seen other issues relating to missing overloads for related frameworks and so I'd thought I'd report another one.

Would it be possible to create 2 overloads on jQueryObject.ReplaceWith() to accept (as well as a string):
- a normal Element
- another jQueryObject

This is supported by jQuery since v1.2 (as specified at http://api.jquery.com/replaceWith ) and would be very useful.

**Comment by nikhilk** [comment]
If you can provide the signatures that need to be added, I can try and do this today...

**Comment by stevehobbsdev** [comment]
I would imagine the signatures would just be something like:

<pre>
jQueryObject ReplaceWith(Element newContent);
jQueryObject ReplaceWith(jQueryObject newContent);
</pre>


Overloads on ReplaceWith where we can set a Element or jQueryObject instance (in addition to a string, which you have done already), and to be able to access the new element which is returned by that method.

**Comment by nikhilk** [comment]
Fix included in 0.7.2.0 release.
