### ISSUE TITLE
Tutorials on wiki vs. gh-pages

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#361]
@nikhilk  - I created a tutorial on my s# fork's wiki on [using the dev branch](https://github.com/theoutlander/scriptsharp/wiki/Using-the-development-branch), but I can't send a pull-request for it as that's not allowed on GitHub. Although, the images I used on that page had to be uploaded to gh-pages for which I would have to send a pull-request.

I was wondering if I should create html pages instead that we can link to on the main site under a documentation section? That way we can send pull requests for the tutorials and they will look a lot nicer too with HTML/CSS instead of MD.

What do you think?

**Comment by nikhilk** [comment]
Need to do a bit of work on the main site ... getting it ready for new content. Fingers crossed, this weekend...

**Comment by theoutlander** [comment]
This is going to be awesome!!! Looking forward to it. Let me know if you need any help.

Not sure if you're working on any (basic) tutorials at the moment, but I'm planning to work on a Hello World tutorial which explains:
- The various templates and their purpose
- Brief intro/reference to AMD pattern
- Actual program will simply print Hello World in the html page and a Javascript Alert on document load (something on those lines)

I'll also demonstrate hello world with RequireJS in related module. Although, I forget what the limitations of SSLoader are and if and why we need to continue to support SSLoader?

**Comment by theoutlander** [comment]
When you get a chance, can you share what the tutorials page should look like? That way I can build the above Hello World tutorial in that format. Thanks!

**Comment by nikhilk** [comment]
I am hoping that the scaffolding for the site that I am putting together will work well with content written as a github flavored markdown.

I'll have one scaffolding/structure for the main page with a larger banner on top, and for article pages, there will be a minimal header and a small footer which is going to be shared across pages.

**Comment by theoutlander** [comment]
Where would be a good place to store the tutorials since gh-pages don't allow pull requests. I think if we got a tutorials sub-folder, people could at least start contributing/benefiting from it.

Also, do you still plan on adding support to keep up with the latest release of .NET? I think we could use NRefactory or Roslyn. It would be really awesome to contribute to that part of the project and help S# stay on the cutting-edge language wise.

**Comment by nikhilk** [comment]
I do want to get current with c# support (likely using NRefactory) ... perhaps a summer project. Want to meet up some time to sketch a plan both time-frames, as well as sketch out an overall design?

**Comment by theoutlander** [comment]
That sounds like a good idea. I'm in the process of closing, selling and moving homes (to NE Redmond) so might be slightly busy for the next month or two, but let me know what days work for you and we'll make it happen. We should at least get the ball rolling... :) Thanks!!

**Comment by theoutlander** [comment]
@nikhilk - Finally settling down after the move... we should start our conversation on the documentation & C# support.... 0.8 should be released as well IMO. Let me know if you want to meet one of these evenings or weekends.
