### ISSUE TITLE
Base64 encoding/decoding

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#362]
I don't see any stubs for base64 encoding/decoding.

Can I add stubs for Base64 to Binary ([atob](https://developer.mozilla.org/en-US/docs/DOM/window.btoa)) and Binary to Base64 ([btoa](https://developer.mozilla.org/en-US/docs/DOM/window.atob)) in the Window class as Base64ToBinary and BinaryToBase64?

**Comment by nikhilk** [comment]
Wow, never knew about these APIs... they're odd to show up on Window though. Ideally this would be javascript functionality and not DOM functionality. In nodejs, this functionality comes by way of the Buffer class.

So for now I guess we can't put this in mscorlib where it really should have belonged given the differences in the two environments. So yes, go ahead and add to Window.
