### ISSUE TITLE
 0.8 version mscorlib.js runtime

### ISSUE THREAD

**Issue by MaxEden** [nikhilk/scriptsharp#368]
Hello,
Our client submited an issue https://github.com/nikhilk/scriptsharp/issues/366
Unfortunately I cant find any official release except 7.5.
Could you be kind to tell me how stable new version is? Or is it just in development?
If that's possible could you provide us latest version of mscorlib?
Thanks.

**Comment by theoutlander** [comment]
New version is very stable. We use it in production. The code is ready, but the release is pending completion of documentation, tutorials, etc. Here's a tutorial on [getting started with the dev branch](https://github.com/theoutlander/scriptsharp/wiki/Using-the-development-branch) which I'm waiting to merge into the main branch. That should help you get started.

What are the specific problems that you're facing with mscorlib?

**Comment by MaxEden** [comment]
Thank you for the useful link.
The issue is that mscorlib overrides base javascript objects prototypes and that often causes conflicts with third party libraries. Even if there is no problem it's still a strange behavior.

**Comment by theoutlander** [comment]
Interesting. I can see how that can be a problem. I think it's fixed in 0.8 as per https://github.com/nikhilk/scriptsharp/issues/264. If your application is written in 0.7x, the port will require some code changes but its not too bad and definitely worth it. 

Let us know how 0.8 works out for you and do ask for help if you run into issues.

**Comment by theoutlander** [comment]
@MaxEden - Were you able to get around the problem you're facing after trying out 0.8? Can you please close the issue in that case? Thanks!

**Comment by MaxEden** [comment]
Sorry for no response. I'm currently converting our project for 0.8. I faced some code changes and differences in output scripts. However everything is going fine and I think we can close this case. Thanks a lot!

**Comment by theoutlander** [comment]
No worries! Glad things are working out. Thanks for closing the issue.
