### ISSUE TITLE
Missing regex overrides for string replace

### ISSUE THREAD

**Issue by robitar** [nikhilk/scriptsharp#37]
Shouldn't be to much work to add them in:

```
string Replace(RegularExpression, string)
string Replace(RegularExpression, Func<string, string>)
```

Without them you have to use Type.InvokeMethod, which gets ugly if you want to use a replacement function as you have to assign it to a temporary variable first.

**Comment by nikhilk** [comment]
Use ReplaceRegex - you'll see the overloads.

This is to distinguish from Replace which gets mapped to replaceAll in script.
