### ISSUE TITLE
The float ending with 0 gets converted to int.

### ISSUE THREAD

**Issue by sameerk** [nikhilk/scriptsharp#373]
Hi,
If a property has value of float that ends with 0 (e.g. 1000.0), Json.ParseData will convert it to integer i.e. 1000

My version is 0.8

Is this a known issue? What is the workaround/fix?

Thanks,

S

**Comment by nikhilk** [comment]
Json.ParseData is effectively JSON.parse ... in other words, you get the behavior of the native script APIs. Script#, the compiler, doesn't abstract things.

Furthermore, in script numbers are represented as Number types. There really isn't an integer or a float.
