### ISSUE TITLE
Assembly-wide ScriptNamespace

### ISSUE THREAD

**Issue by Ventajou** [nikhilk/scriptsharp#38]
Definitely not a big issue, but it would be convenient to not have to use ScriptNamespace on all classes and instead do it once for each namespace.

For example: ScriptNamespace("My.Very.Long.Namespace", "abc");

**Comment by nikhilk** [comment]
Did you try:

```
[assembly: ScriptNamespace("abc")]
```

There is no way to map a particular c# namespace to a particular script namespace. However I'd recommend thinking of a script namespace as a "brand" - you have a single script namespace, potentially across assemblies for a logically related set of code.

Having a single script namespace will help minimizing the size of the script, and in the future will be required.
