### ISSUE TITLE
Breeze/Q Support

### ISSUE THREAD

**Issue by jgarverick** [nikhilk/scriptsharp#381]
Hi Nikhil,
I was wondering if you had any plans on incorporating support for the Breeze and/or Q libraries?

**Comment by nikhilk** [comment]
I didn't have specific plans at the moment - I am fine if someone in the community wants to pick these up and take a stab at adding import libraries for these.

**Comment by jgarverick** [comment]
Fair enough. I might just give it a go. Thanks!
