### ISSUE TITLE
ScriptIgnoreNamespaceAttribute Don't work  :(

### ISSUE THREAD

**Issue by Unvilon** [nikhilk/scriptsharp#402]
For example:

namespace Villain512JSTools
{
    [ScriptIgnoreNamespace]
    internal static class TextE
    {
        static RegExp IsUrlRegex = new RegExp(@"/^(https?:\/\/)?([\da-z.-]+).([a-z.]{2,6})([\/\w .-]_)_\/?$/");
        public static bool IsUrl(string s)
        {
            return IsUrlRegex.Test(s);
        }
    }
}

compiled as 

function Villain512JSTools$TextE() {
}
Villain512JSTools$TextE.isUrl = function(s) {
  return Villain512JSTools$TextE._isUrlRegex.test(s);
}
var Villain512JSTools$TextE$ = {

};

It is in every class

why?

**Comment by andekande** [comment]
strange, can't reproduce this in cc branch

**Comment by nikhilk** [comment]
In the current code, namespace-qualified names are only generated if you have similarly named classes within different namespaces in the same assembly, which should hopefully be quite rare.

ScriptIgnoreNamespace is only useful when defining imported types - it has no effect for script# generated scripts.
