### ISSUE TITLE
Getting 'owebdriver.dll' could not be opened - 'the assembly is not a script assembly' build error

### ISSUE THREAD

**Issue by PardeepK** [nikhilk/scriptsharp#404]
Hi,

When I am including owebdriver.dll in my source file, I am getting 'owebdriver.dll' could not be opened - 'the assembly is not a script assembly' build erro.
Can someone let me know why I am hitting this issue? can we compile owebdriver.dll in script#.

Thanks in anticipation,
PardeepK

**Comment by theoutlander** [comment]
Script# does not convert DLL's to JS. It is simply a S# (C# 2.0 as per ScriptSharp spec) to JS compiler where you're using C# to write JS.
