### ISSUE TITLE
sharepoint and script#

### ISSUE THREAD

**Issue by sharaditmca** [nikhilk/scriptsharp#405]
when i m runing my sharepoint2010 project its works well but when i try to use script# in sharepoint2010then following error occurs 

1.)The type 'System.CodeDom.Compiler.GeneratedCodeAttribute' exists in both '..\packages\ScriptSharp.0.7.5.1\tools\mscorlib.dll' and 'c:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll

2.)The type or namespace name 'ComVisibleAttribute' could not be found (are you missing a using directive or an assembly reference?)

3.)The type or namespace name 'GuidAttribute' could not be found (are you missing a using directive or an assembly reference?)

i download script# in vs2012 via nuget

thanks in advance 
sharad

**Comment by nikhilk** [comment]
You'll want to create a script# project separately, rather than add script# to an existing .net project. The scripts produced from a script# project could be deployed into your sharepoint app if what you're trying to achieve is some client-side script functionality within your sharepoint app.
