### ISSUE TITLE
Get textbox value using Script#

### ISSUE THREAD

**Issue by parthangshu** [nikhilk/scriptsharp#415]
Hi,

I have generated one textbox for user to enter his/her name using Script#. Say the textbox id is txtName. Now I want get the text (text entered by users) of that textbox (txtName). Please guide me how can I get the textbox value/text.
Thanks,
Partha

**Comment by michaelaird** [comment]
Look at the sample application:
https://github.com/nikhilk/scriptsharp/tree/master/samples/Todo/Todo

**Comment by theoutlander** [comment]
A couple of tutorials that might be helpful:

https://github.com/nikhilk/scriptsharp/wiki/Creating-your-first-HTML5-Application:-Hello-World
https://github.com/nikhilk/scriptsharp/wiki/Building-a-spreadsheet-in-Script%23-using-HTML5

**Comment by nikhilk** [comment]
See comment on previous question - the general idea is if you know how to do it in script, it should hopefully be a direct or trivial mapping to the script# equivalent.
