### ISSUE TITLE
All samples rely on the ScriptC# V0.8 Nuget package which does not exist

### ISSUE THREAD

**Issue by SimonDarksideJ** [nikhilk/scriptsharp#417]
The latest version of ScriptC# on Nuget is 0.7.5.1

So al lthe samples fail to compile becuase it cannot restore the packages.

If I remove them and install the 0.7.5.1 release, I get build errors for attributes:
ScriptModule
ScriptTemplate

I've got everything installed, including the VS extension

**Comment by michaelaird** [comment]
The 'master' branch corresponds to the released version. I think Nikhil may
have changed the default branch to 'cc'. Which is the unreleased v.next and
has lots of breaking changes.

**Comment by SimonDarksideJ** [comment]
That worked, thanks for the clarification
