### ISSUE TITLE
Export to text file using Script#

### ISSUE THREAD

**Issue by parthangshu** [nikhilk/scriptsharp#419]
Hi,

I have to export the content of some DB field to text file and will give user this file to Download over the Browser. In normal .NET using Response.Write and set content type to "text" I can do this. But in Script# I am not able to do.

Please help!!!

Thanks,
Partha

**Comment by nikhilk** [comment]
Assuming the server is still written in .net you'd do whatever you've been doing, i.e. without script# used for your server. That said, as mentioned multiple times now, this isn't really a script# issue, but general q&a, which is better directed elsewhere. Closing...
