### ISSUE TITLE
Writing to a File

### ISSUE THREAD

**Issue by SaktiEricsson123** [nikhilk/scriptsharp#422]
Hi Nikhil,

  I have a requirement of writing the value of a CLOB field to a new .txt file. Means on Click of a button (Client is a mobile phone in this case), I have to get the details from server, create a txt file and write the contents in the txt file and save it. I am getting no idea how to do it in Script # as it does not support any server side pages (example asp) neither it supports System.IO. Please help me in this. Any similar code snippet will help. This may be simple, I am new to script # and has limited knowledge of the same.

**Comment by nikhilk** [comment]
Use the HTML5 file APIs if you're doing this on the client. See https://github.com/nikhilk/scriptsharp/tree/cc/src/Libraries/Web/Html/Data/Files

Hope that helps.
