### ISSUE TITLE
Check internet connectivity using Script#

### ISSUE THREAD

**Issue by parthangshu** [nikhilk/scriptsharp#423]
Hi Nikhil,

I have to check internet is available or not using Script#. I tried Navigator.Online property. But it is not working.

Could you please give some sample code from your blog or something like that.

Many thanks,
Partha

**Comment by michaelaird** [comment]
Have you read this:
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine.onLine ?

Navigator.online is not reliable and behaves differently in different
browsers. If you search StackOverflow you can find some different solutions
for checking connectivity in javascript. These can easily be adapted to
Script#.

In general, I would always suggest searching for javascript solutions to
these problems and then adapting them to Script#.

**Comment by nikhilk** [comment]
I've also mentioned this several times to you ... but will repeat. As Michael mentioned - you need to first look at how you'd do something in javascript, rather than search for some special script# solution to most of your questions.
