### ISSUE TITLE
mscorlib conflict. Could not load type 'System.ScriptAssemblyAttribute' from assembly

### ISSUE THREAD

**Issue by kirakosyan** [nikhilk/scriptsharp#424]
Hi
How I can see this is a known problem, but I could not find a proper workarround.

I had working MVC application which had SignalR installed NuGet package.
I have added a Script# project to the solution and added reference from MVC application to the newly created S# project.

Now I have a conflict with mscorlib between SignalR and S#
Could not load type 'System.ScriptAssemblyAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

I am not able to make them to work togather.

One known solution was offered by Nikhil to remove S# reference, but then I will miss autocreated js files in my Scripts folder. Also I have inherited some S# classes in my MVC model which saved me a lot of time. 

So I would like to keep SignalR package and S# reference togather.
I am pretty sure there are other NuGet packages which will cause the same problem.

Any good solution?

My environment:
VS 2013. S# 0.8. .NET 4.5

**Comment by nikhilk** [comment]
It looks like signalr enumerates/loads all assemblies in the bin directory. As you mention the workaround is to remove references... but this breaks the ability to deploy script files into a web app via project-to-project references (as well as have the vs solution understand intra-project dependencies and infer build order).

Is there some config in signalr to list assemblies to load and/or not blindly enumerate all assemblies in the bin directory?

I don't know msbuild enough to know if its possible to have a referenced project's assembly land in some other directory besides /bin. Maybe someone else knows?

**Comment by nikhilk** [comment]
Found this question on SO - http://stackoverflow.com/questions/280751/what-is-the-best-practice-for-copy-local-and-with-project-references

Might be worth trying to see if copy local can be set to false, and if it has effect, or alternatively try some msbuild black magic as covered in that thread ... maybe it can be adapted to this scenario?

**Comment by kirakosyan** [comment]
Hi
Thanks. 
So "Copy local" = False was the key

**Comment by theoutlander** [comment]
Wow, I didn't think I'd find this issue here....thanks for the workaround!
