### ISSUE TITLE
Nothing emitted for abstract properties

### ISSUE THREAD

**Issue by robitar** [nikhilk/scriptsharp#43]
If I add an abstract property, the compiler ignores it when generating script, but it does emit null get_ and set_ properties for an interface definition, is there any reason why abstract properties cant be represented in the same way?

For context, I'm looking at the prototype of the generated classes at runtime so I can proxy abstract property accessors with implementations that work with a Knockout observable.

Currently, the only way to get this working is to create an interface and implement it on the type, then sniff the properties on the interface. It's an added burden which almost outweighs the benefit of using normal properties instead of observable delegates (almost).

C# code

```
namespace Client.Model {
    public interface IModelClass {
        string Prop { get; set; }
    }

    public abstract class ModelClass {
        public abstract string Prop { get; set; }

        public string Foo {
            get {
                return null;
            }
        }
    }
}
```

Generated Script

```
////////////////////////////////////////////////////////////////////////////////
// IModelClass

IModelClass = function() { 
};
IModelClass.prototype = {
    get_prop : null,
    set_prop : null
}
IModelClass.registerInterface('IModelClass');


////////////////////////////////////////////////////////////////////////////////
// ModelClass

ModelClass = function ModelClass() {
}
ModelClass.prototype = {

    get_foo: function ModelClass$get_foo() {
        /// <value type="String"></value>
        return null;
    }
}
```

**Comment by nikhilk** [comment]
Actually interfaces are also empty in release builds. Going forward, this will be true of debug builds as well, so things are consistent across release/debug. Interfaces are essentially markers in script.

**Comment by robitar** [comment]
I still argue that for these kinds of scenarios (interop, proxying etc) its worth making more use of interfaces, rather than just wiping them out of the resulting script all together. It's frustrating, because there aren't many options with Script# for this kind of scenario, to avoid having to deal with repetitive boilerplate code.

Thanks for the heads up regarding release builds, I must remember to check that, its bitten me before at the last minute.

**Comment by nikhilk** [comment]
I am not seeing why you can't just enumerate the actual type's prototype?

For KO, you could probably use something like this in an import library:

```
public delegate TValue ObservableValue<TValue>(params TValue[] values);
public static class KO {
    public static ObservableValue<TValue> Observable<TValue>() { return null; }
}
```

And in your model class:

```
public class MyModel {
    public readonly Observable<string> Foo = KO.Observable<string>();
}
```

rather than trying to do something at runtime with proxy classes.

As far as interfaces go and abstract methods go, I am relatively sure of the approach that they don't have a runtime footprint. Even minimizers like the closure compiler take a similar approach where the equivalent of interfaces get minimized away.

Ultimately what you want is to do what you're doing at the c# source level at compilation time where all the type information is available. That is certainly interesting, but in reality will be some time before it can come together.

I'll let you close out the issue... :-)

**Comment by nikhilk** [comment]
Additional footnote -

Just realized it was you in fact who had suggested that approach for observables. And your other comment on a different issue helped explain what you're trying to do...

As an opinion, I am not sure the KO model of changing how properties surface to the consumer to support observability is the best approach. Properties should have same pattern regardless of underlying implementation. That is what I am building toward with script#.

**Comment by robitar** [comment]
I cant use the real prototype, because the properties aren't emitted for it, I would have to implement dummy properties which would be confusing:

```
class {
    string Prop {
        get {
            //ignored, gets overwritten magically at some point
            return null;
        }
    }
}
```

Yes the delegate approach works well for 80% of the KO use cases, and I'm still currently using it, but it has some drawbacks:
- You cant add members to delegates, so subscribing to an observable becomes more cumbersome, because there's no way to map the 'subscribe' function to an observable delegate, and using a helper function means you lose your generic typing support (everything has to be cast to object to make it work)
- Property syntax is easier to understand and use
- After a while, the observable fields take up most of the class definition, making it hard to read.

Yes I agree, its not ideal having the abstract properties magically proxied, and I would usually (server side) use an attribute to make it more obvious.

However, I think that the intention is clear, these are abstract properties that are being implemented by the runtime, using a hidden backing field. They have value semantics. Its exactly the same as generating a delegate for an event without making it obvious to the user what's really going on, the only difference here is that I'm performing the transformation at runtime instead of compile time.

**Comment by robitar** [comment]
After some hacking, I've decided to do this the right way, by generating code from an assembly. I take your point, interfaces should represent a contract, there's no requirement that they be included in the generated output.
