### ISSUE TITLE
Script.Web Javascript output file

### ISSUE THREAD

**Issue by Paul-Rogliano** [nikhilk/scriptsharp#433]
Hy Nikhil,

Thank's very much for your very useful tool. I use it since 2 years now, when to day I tried to acces the following class:
System.Web.Navigator

Where is the javascript version of this class please ? I cannot find the corresponding javascript source code as result of the S# compiler.

Can you help me ?

Regards, PR

**Comment by nikhilk** [comment]
This represents the built in window.navigator object.
