### ISSUE TITLE
ScriptSharp's lack of resources

### ISSUE THREAD

**Issue by jshaker** [nikhilk/scriptsharp#437]
Hey guys,

I started using the ScriptSharp API to work on some already existing C#/S# projects. I learned the basics by looking at already existing code, but then I got really intrigued and wanted to work with ScriptSharp for my own projects. To my own disappointment, http://www.scriptsharp.com no longer is owned by Script# (nor nikhilk). I can't find any guides. I can't find any documentation.

So my question; is this API dead or dieing? Is it not used anymore? Is there better approaches than Script# for compiling C# into JS? Have I been looking in the wrong place? Why isn't there any documentation?

Thank you,
Jeremie Shaker

**Comment by gcnm-pgeil** [comment]
Given the commit activity (last one more than 2 years ago) and how fast the JavaScript language spec is evolving -- I would consider Script# as dead.

**Comment by michaelaird** [comment]
I would say that it's "done". As you've noticed, there doesn't appear to be any activity on the core and the attempt at v4.6 was never really released.

For new development, I would suggest TypeScript. Or checkout this: http://bridge.net/ ( i haven't used Bridge but it looks promising)

**Comment by jshaker** [comment]
Yeah, I've moves onto TypeScript, as it appears even Google started using for 
projects such as Angular 2. Thanks!
Sent with [inky](http://inky.com?kme=signature)

**Comment by nikhilk** [comment]
OK, I should chime in here --

First, apologies for not responding sooner, but its hard to be active on a front that isn't on your radar day in and day out.

Its been awesome to work on script#, see so many users, and apps built on it over the life of the project. Thanks for all the support over the years. Hopefully, I'll get to meet and have paths cross with folks I know in other contexts.

But now even more so than before, its time to look at what comes next. For me, its been a new and different set of priorities for the last couple of years (though I am still active on github), and for web app development, there so much to look forward to, with much improved JavaScript all around, and TypeScript bringing those improvements for use today. That said I still love c# and c# to javascript will always have special meaning.

Thanks!!!

**Comment by jshaker** [comment]
Thanks for taking the time to reply!

It would have been a fun experience to build an entire web project in C# and the whole OOP structure, but I've made the move to TypeScript, just as Google has, and it's been great.

Have a good evening!
Jeremie Shaker

**Comment by michaelaird** [comment]
@nikhilk : I totally understand that you've moved on to other things but I wanted to take a minute to thank you for the work you've done in the past. 

When we started our project 3+ years ago, there was no TypeScript. For a group of devs with strong C# skills but weak JavaScript skills, it allowed us to create amazing, responsive, cleanly coded viewmodels that are still in use on a daily basis.

Even though we're in the process of transitioning many 1,000's of lines of code to TypeScript, we wouldn't be where we are today without Script#. 

Thanks for all your work!
