### ISSUE TITLE
Unable to Build - ScriptSharp 0.7.5.1 - Visual Studio 2012 (Windows 10)

### ISSUE THREAD

**Issue by syafrin-liong** [nikhilk/scriptsharp#438]
Hi nikhilk,

I have not been able to build a Script# project. The error as follows:

The "ScriptCompilerTask" task could not be loaded from the assembly C:\TestProject\packages\ScriptSharp.0.7.5.1\tools\ScriptSharp.Build.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Can you help?

Cheers,
Sy

**Comment by michaelaird** [comment]
Can you confirm that the ScriptSharp.Build.dll file is in your
packages\ScriptSharp.0.7.5.1\tools\
folder?

**Comment by syafrin-liong** [comment]
Hi michaelaird, 

Thank you for your reply. What happened was Script# requires .NET 2.0 to build targets and on my Windows 10 the older .NET Frameworks are not installed by default. Once installed, all works fine.

Cheers,
Sy
