### ISSUE TITLE
Generic class with a generic action wont compile

### ISSUE THREAD

**Issue by Lightw3ight** [nikhilk/scriptsharp#44]
If i try and create a class with a generic attribute and then add a field with a generic Action that uses's the class' generic attribute
the project does not compile and gives no error message, here's an example of what wont compile

public class GenericTest<T>
{
    Action<T> MyAction;
}

thanks
-Kris

**Comment by nikhilk** [comment]
You can't create generic classes (as listed in the release notes) for now. You can only use generic types that have been carefully (there are some other constraints) defined in import libraries (eg. mscorlib, Script.jQuery, etc.)

Yes, I know it is a limitation. As script# will have better support for more of the c# language, these sort of scenarios will be accounted for.

**Comment by Lightw3ight** [comment]
Thanks Nikhil, I suspected as much and should have read the release notes ;)
