### ISSUE TITLE
Unable to build using the source

### ISSUE THREAD

**Issue by larrywelch** [nikhilk/scriptsharp#444]
I downloaded a copy of the source and tried to build using VS 2015 Community edition.  I get the following build errors:
1>CSC : error CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.

this one repeats for what looks like a lot of projects:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Dev_Area\ScriptSharp\scriptsharp-cc\scriptsharp-cc\bin\Debug\mscorlib.dll' could not be found	Web	C:\Dev_Area\ScriptSharp\scriptsharp-cc\scriptsharp-cc\src\Libraries\Web\CSC	1	Active

**Comment by scottdurow** [comment]
I have only ever built using VS2012 - but once built you can install it inside VS2015.

**Comment by larrywelch** [comment]
I was able to build with VS2012.  Thanks.
