### ISSUE TITLE
Attempted to Add Support for Bing Map V8 - Build and Use issues

### ISSUE THREAD

**Issue by larrywelch** [nikhilk/scriptsharp#446]
I really like what ScriptSharp can do for me and I have a large project with dependencies on maps.  Bing Map V7 is end of life in June, 2017 so I want to use V8.  I decided to take a crack at adding support (Libraries\BingMapsV8) .  I limited my work to initializing a map while I get my feet wet.  I have a successful build but I haven't been able to use it.

I've followed the instructions for uninstalling the release version from VS and then adding the Script# Local.  I've created a project and I can see that it's included ScriptSharp.0.8 in the packages folder.  This leads me to believe that I have the dll's with my new code.  Unfortunately whenever I try to build the application I get:
1>------ Build started: Project: Application1, Configuration: Debug Any CPU ------
1>  Consider app.config remapping of assembly "mscorlib, Culture=neutral, PublicKeyToken=8fc0e3af5abcb6c4" from Version "0.7.0.0" [] to Version "0.8.0.0" [C:\Dev_Area\scriptsharp-cc\BingMapV8\ScriptLibrary1\packages\ScriptSharp.0.8\tools\mscorlib.dll] to solve conflict and get rid of warning.
1>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly.
1>  Application1 -> C:\Dev_Area\scriptsharp-cc\BingMapV8\ScriptLibrary1\Application1\bin\Debug\Application1.dll
1>C:\Dev_Area\scriptsharp-cc\BingMapV8\ScriptLibrary1\packages\ScriptSharp.0.8\tools\ScriptSharp.targets(36,5): error : The assembly 'C:\Dev_Area\scriptsharp-cc\BingMapV8\ScriptLibrary1\packages\ScriptSharp.Lib.HTML.0.8\lib\Script.Web.dll' is not a valid script assembly.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Any ideas?

**Comment by scottdurow** [comment]
The NuGet package for script# is 0.7.5 and this is the version I use since it is stable. 
I've been meaning to create a branch for this version since I don't want to move to 0.8 due to the breaking changes.

I would recommend creating a separate assembly import for Bing Maps V8 to replace the existing one rather than adding it directly into the ScriptSharp compiler package it's self.

**Comment by larrywelch** [comment]
Thanks for the feedback. Is there documentation on the wiki explaining how to create an import?  

Get Outlook for iOS




On Fri, Mar 3, 2017 at 5:18 AM -0700, "Scott Durow" <notifications@github.com> wrote:












The NuGet package for script# is 0.7.5 and this is the version I use since it is stable.

I've been meaning to create a branch for this version since I don't want to move to 0.8 due to the breaking changes.


I would recommend creating a separate assembly import for Bing Maps V8 to replace the existing one rather than adding it directly into the ScriptSharp compiler package it's self.

**Comment by larrywelch** [comment]
I apologize but I'm new to GitHub and contributing to open source.  I gave it some thought this morning and decided to try and just create a new Script# Script Library and use the source from the original Bing Map V8 work I did.  I had to remove some of the attributes ([ScriptImport]) to make it compile.  I then found that I couldn't have overloaded constructors.  I overcame these issues and generated a very minimal implementation of the Map class.  I then created another Script# Script Library and named it Unit Test.  I included a project reference to the Bing Map V8 project.  I was able to create an instance of the Map and set some properties.  The unit test project compiled but it didn't output any JS.

Am I on the write track?   

One other note: I'm attempting to use VS 2015.  Should I stick with VS 2012?

**Comment by larrywelch** [comment]
Spent a bit more time to flush out more thoughts.  It looks like VS2015 is a bit finicky about generating Script# projects.  It also looks like it brings in V7.6?  

I decided to create a Script# template project from one that I created with VS2012.  I then used that template to generate additional projects and they all behave as expected and generate javascript.  

So I now have a Bing Map V8 project that generates script and dlls.  I then have a test harness that utilizes the Bing Map V8 dll.  The test project is generating js and the output is aligning with the Bing Map V8 documentation.  I'm going to keep going down this path unless someone informs me that there is a different approach that I should take.

**Comment by scottdurow** [comment]
Definitely on the right path! Do you have a Git Repo for your new import library?
I need to move some code over to the V7 API 👍

**Comment by scottdurow** [comment]
How are you getting on with this - can you point me at your repo? I'd like to help!

**Comment by larrywelch** [comment]
Hi Scott,
I have a version that allows for creating the map with options and push pins. Need to fill in the remaining sub classes. 
I've never contributed to open source before. What's the best way?  Do I just create a git repo and publish to it?  Or do I publish to this repo?
Get Outlook for iOS




On Thu, Mar 9, 2017 at 5:03 AM -0700, "Scott Durow" <notifications@github.com> wrote:












How are you getting on with this - can you point me at your repo? I'd like to help!

**Comment by scottdurow** [comment]
I recommend creating your own repo for the Script# Bing Maps V8 Import 👍

**Comment by larrywelch** [comment]
I'll do that today and send you the details. Thanks for your help!

Get Outlook for iOS




On Thu, Mar 9, 2017 at 9:56 AM -0700, "Scott Durow" <notifications@github.com> wrote:












I recommend creating your own repo for the Script# Bing Maps V8 Import 👍

**Comment by larrywelch** [comment]
Hi Scott,

I am on holiday but was able to get the GitHub project created.  The url is: 
https://github.com/larrywelch/ScriptSharpBingMapsV8Import
I welcome any advice or guidance.  The repo includes all files from the v7 library but the project only includes the files that have been updated for v8.
