### ISSUE TITLE
Duplicate-named member error - overloaded methods and constructors

### ISSUE THREAD

**Issue by larrywelch** [nikhilk/scriptsharp#447]
Is there a trick to overloaded methods and constructors or are they just not supported?

Ex:
        [ScriptName("tryLocationToPixel")]
        public MapPoint[] TryLocationsToPixels(MapLocation[] locations) {
            return null;
        }

        [ScriptName("tryLocationToPixel")]
        public MapPoint[] TryLocationsToPixels(MapLocation[] locations, MapPointReference pointReference) {
            return null;
        }

or 
        public Map(Element element, MapViewOptions options) {}
        public Map(string elementName, MapOptions options) { }
        public Map(string elementName, MapViewOptions options) { }

**Comment by scottdurow** [comment]
You can overload methods provided the class is marked as Imported

```
[Imported]
    public class ImportedClass
    {
       
      
        public ImportedClass(string s)
        {

        }
        public ImportedClass(int i)
        {

        }
        public void Foo(int i)
        {

        }

        public void Foo(string s)
        {

        }
    }
```

**Comment by larrywelch** [comment]
Perfect!
