### ISSUE TITLE
Culture not modifiable

### ISSUE THREAD

**Issue by milanaleksic** [nikhilk/scriptsharp#47]
It would be nice to be able (as it was in 0.5.1 version)  to change the current culture. 
This way we can use different locales on the same web site, and be able to modify them on the fly (for example when visitor decides to go to French pages instead of English).

This is because propery Culture.CurrentCulture is read-only. Is it possible to modify Current Culture in some other way, except explicitly mentioning the culture I want to use in a specific place? This is quite problematic in our case since we depend on using active culture.

**Comment by nikhilk** [comment]
Current culture is modified by loading a script file for the right culture that replaces the value of currentCulture in script. These localized culture files are generated, and hence there is no need to set from within c# code. For example, the script would contain:

```
ss.CultureInfo.CurrentCulture = { 'fr', /* culture-specific values */ ... };
```

**Comment by milanaleksic** [comment]
I understand the approach but I believed better one would be to do it from Script# instead of delegating this action to external JavaScript

**Comment by mattclay** [comment]
Is there some place the generated culture files can be downloaded, or is there a tool available to generate them?

**Comment by nikhilk** [comment]
There isn't a tool implemented to do that yet... though writing one would/should be straightforward.
