### ISSUE TITLE
WebAppPartitioning limitations

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#48]
Currently we're using ScriptSharp in a rather large enterprise project, and we're making use of the WebAppPartitioning flag in the project file to cause ScriptSharp to generate one .js file per root folder from inside our project.

However, when we come to use code across folders the compiler complains that we're using an unsupported feature and will not build. Instead we should be putting such code into the Shared folder so that the output is copied into each partitioned file.

I think I understand why this is done - the risk is that code would be split across two js files and there is more room for error.

If the above is correct and there isn't a technical limitation from the compiler's perspective as to why it prevents us from using partitioning in this way, is there a way for you to allow us to opt-in to prevent this check from happening (such as another project file setting), and leave it up to the responsibility of the developer to make sure all relevant code files are included on the web page?

As it stands, when we use S# to author several different frameworks within the same project, but some other code depends on one of these frameworks, we can't code against it because of the above limitation.

Web Partitioning is excellent, but in order to make full use of it we really need to be able to code against types which exist in different root folders.

If this is not possible, could you briefly explain how the bigger projects which use S# overcame this limitation? It seems likely to me that they would have already come across this.

Thanks

**Comment by nikhilk** [comment]
Actually the way partitioning happens is the msbuild task invokes the compiler multiple times, passing in only code/source files from one folder at a time along with any code in the Shared folder.

So if you have any code at all you want to share across folders, you'll need to put it into the shared folder. It is by definition not scoped to a single page within a web app if it is being referenced from within multiple folders.

The general idea is to minimize per-page script... page script should be mostly glue code that handles events and calls into a framework/library that is compiled separately as independent projects (which work much better from a reuse/flexible factoring perspective), or additionally page level script instantiates behaviors/jquery plugins and associates them with elements. This is how most of the large projects are organized.

I personally think code can be divided into 3 buckets:
1. Framework code that is reusable building blocks ... which includes UI behaviors/plugins.
2. App code that is UI independent (view models for example)
3. View code that is the glue between UI and #1 and #2. I also think #3 can be mostly declarative markup annotations with the right framework.

I've done this in context of Silverlight as well as some script apps, and hoping to flesh it out further with a script framework on top of script#.

**Comment by stevehobbsdev** [comment]
Thanks for the insight. For some reason I didn't realise that you could reference one Script# project from another and program against types in a different library. Now it makes complete sense, but I think I must have concentrated on the WebAppPartitioning route in the first instance and dismissed the fact that multiple projects are what we actually needed (and indeed, that it would even work).

Thanks for clearing that up. Incidentally I notice that the web application project templates are missing from the project setup; is this scenario obsolete already or will it be fully supported in future releases?

**Comment by nikhilk** [comment]
The scenario/support hasn't gone. The template's existence was causing too much confusion - everyone picks it over the library project, and doesn't realize the implications.

You'll still be able to modify the csproj manually (presumably anyone doing so will have understood the subtleties).

Eventually a project wizard could ask for this option... and even further, the best case scenario would be for a script#-flavored c# project that had its specific UI in the project properties to turn this on/off.

**Comment by stevehobbsdev** [comment]
Thanks, Nikhil
