### ISSUE TITLE
Suggestion: name change for template for Script# class template

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#49]
Would it be possible to rename the Class template to "Script# Class"...

Once in I while, I find myself adding a Script# class to a non Script project by accident.
This has the annoying effect that it adds Script#'s dll's to the project.
If the name would be 'Script# class' I would immediately see the difference and I guess it would be just a small change.

**Comment by nikhilk** [comment]
Perhaps Script Class... just like the project templates say Script Library.

**Comment by rekna1** [comment]
that would be ok

**Comment by josche-duplicate** [comment]
I've been using class.js.cs to differentiate files from the scriptsharp project with regular project so I'd recommend this too.

**Comment by rekna1** [comment]
@josche : it's not the name of the class I create that confuses me, it's the name of the 'template'... thx for the tip anyway.

**Comment by robitar** [comment]
Also a minor pet peeve is the fact that it adds a comment with the name of the class to the top of the file, the first thing I do after creation is delete it.

**Comment by nikhilk** [comment]
Fix included in 0.7.2.0 release.
