### ISSUE TITLE
GeolocationService.WatchCurrentPosition has wrong method name

### ISSUE THREAD

**Issue by chandramuralis** [nikhilk/scriptsharp#50]
<b>WatchCurrentPosition</b> should be named as <b>WatchPosition</b> in  <b>System.Html.Services.GeolocationService</b> class , this is what the <a href="http://dev.w3.org/geo/api/spec-source.html#watch-position">Standard API</a> says.

Thanks,
Murali.

**Comment by chandramuralis** [comment]
thanks nikhil. Is there any planned date for next version release?

**Comment by nikhilk** [comment]
Fix included in 0.7.2.0 release.
