### ISSUE TITLE
<IE9 IgnoreNamespace and object creation

### ISSUE THREAD

**Issue by josche-duplicate** [nikhilk/scriptsharp#57]
I have an issue with 'xxx' is undefined in IE 8

my Script# class is defined like
<code>
[IgnoreNamespace]
public class MyClass: IDisposable
{
    // properties methods and the usual
}
</code>

I call it in inline markup : var class = new MyClass();

It all works in IE9, Firefox, Chrome etc no problem.

However in IE8 I get 'MyClass' is undefined. The emitted JavaScript looks similar to:
<code>
(function($) {
Type.registerNamespace('MyLib');
MyLib.Util = function MyLib_Util(){}
MyLib.Util.FindX = function MyLib_Util$findX(){return "Here it is!";}
MyClass = function MyClass(args) {
  if(args)  {
    //do something
  }
}
 MyClass.prototype = { 
  _myFunction: function(){
    alert('Bing!');
  }
})(jQuery);
</code>

Have no idea why the object is not seen in IE 8

**Comment by nikhilk** [comment]
I don't see why you see the error only in IE8. This should be an error everywhere.

MyClass only exists within the function scope representing your assembly. You should have a namespace for your type. Alternatively if you want to create global script, remove the outermost function scope in the script template (the .script file) within your project.
