### ISSUE TITLE
Compile error due to assembly name sort order

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#62]
There was a regression between the 0.7.1 and 0.7.2 releases that causes a build error due to how assembly names sort in relation to dependencies between projects.

I have a solution that builds under 0.7.1 and will not build under 0.7.2.  There are three projects in the solution:

C (Import Library)
A (Script Library) depends on C
E (Script Library) depends on C, A

Renaming the output assembly for A to F allows the solution to build under 0.7.2.

**Comment by mattclay** [comment]
You can download a ZIP file with two solutions to demonstrate the problem here: [AssemblyNameSortOrderBug.zip](https://github.com/nikhilk/scriptsharp/files/232709/AssemblyNameSortOrderBug.zip)

One solution in the "Good" folder will compile under both 0.7.1 and 0.7.2.  The other in the "Bad" folder will only compile under 0.7.1.  The only difference between the two is the name of the output assembly of one of the projects.

**Comment by nikhilk** [comment]
Fixed in 0.7.4.0 - thanks for including a repro. Referenced assemblies are now topological sorted before being loaded.

Previously the order didn't matter, but the introduction of generics and expansion of generic instance types requires assemblies to be loaded in order.
