### ISSUE TITLE
System.dll' is not a valid script assembly

### ISSUE THREAD

**Issue by accacc** [nikhilk/scriptsharp#64]
if i add a new class in my project,i can not build my project because i get below error,how i can solve this?

Error   1   The assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.dll' is not a valid script assembly.

**Comment by nikhilk** [comment]
Add new classes using the 'script class' template under the script# node instead of a regular class... And/or remove the system dll reference added by the regular one ... as the error message says, it is not a valid script assembly.
