### ISSUE TITLE
Calling ToString() on a constant breaks minified script

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#65]
I have the situation where I'm applying some Css styles to an element, one of these is a height value, and I'm storing this height as an integer constant:

<pre>private const int MIN_SCRATCH_HEIGHT = 100;</pre>

Then, setting the style as follows:

<pre>_scratchArea.CSS("min-height", MIN_SCRATCH_HEIGHT.ToString());</pre>

The call to ToString() in this case seems to be giving me issues only in the minified version of the generated script file (the debug one is ok). Basically I'm getting this error using Google Chrome:

<pre>Uncaught SyntaxError: Unexpected token ILLEGAL</pre>

.. and Internet Explorer 8 doesn't report any error, but also does not process any of the Javascript (no script on my page is working, for example).

If I change the line to use the Type object instead (so that I can pass MIN_SCRATCH_HEIGHT as an object without the call to ToString()):

<pre>Type.InvokeMethod(_scratchArea, "css", "min-height", MIN_SCRATCH_HEIGHT);</pre>

.. then the error does not surface and I my page works (in both browsers mentioned above).

The generated script looks as you'd expect:

<pre>
// with ToString(), minified
this.$1B.css('min-height',100.toString());

// without ToString(), minified
this.$1B.css('min-height',100);

// with ToString(), debug
this._scratchArea$1.css('min-height', Editor._region._miN_SCRATCH_HEIGHT$1.toString());

// without ToString(), debug
this._scratchArea$1.css('min-height', Editor._region._miN_SCRATCH_HEIGHT$1);
</pre>

It seems odd that this particular change would cause such an error.

**Comment by stevehobbsdev** [comment]
After further testing it seems like it's an issue pretty localised to this block of code. If I was to create a new jQuery Page item, put in a class-level constant and then set a Css value on an element using this constant (whilst calling ToString()) then it works ok and doesn't generate the error..

**Comment by nikhilk** [comment]
I think the generated script needs to have been (100).toString() ... that is a bug that needs to be fixed.

As a workaround, can you try (MIN_SCRATCH_HEIGHT).ToString()

Also, it seems it would be equally nice to allow the CSS method to take in an object, or have overloads to take in numbers and booleans, so you don't need to call ToString in source code, or in generated script.

**Comment by stevehobbsdev** [comment]
Sorry for the long reply.

Wrapping the constant within my C# class does nothing; it seems to strip out the brackets when compiled. However, when I dive into the generated script and wrap the number in brackets there, the error goes away.

Having it accept an object or other overloads would be a nice solution, as it does seem to be the ToString() call which is giving me grief!

**Comment by nikhilk** [comment]
Another workaround for now -
(string)(object)MIN_SCRATCH_HEIGHT

Basically cast to object, and then to any type... this essentially "turns off" type checking at the c# compiler level.

**Comment by stevehobbsdev** [comment]
This is great, thanks!

**Comment by nikhilk** [comment]
Fixed in the 0.7.3 release.
