### ISSUE TITLE
Nullables not working correctly

### ISSUE THREAD

**Issue by joeferner** [nikhilk/scriptsharp#66]
This does not compile with the C# compiler...
```int? i = null;
if(i==null) {}

``````
I get "error CS0656: Missing compiler required member 'System.Nullable.GetValueOrDefault'"

If I write this...
```int? i = null;
if(!i.HasValue) {}
``````

Script# generates invalid code.
```var i = null;
if(!ss.isValue(i)) {}

```
Not sure what "ss" is.

Using 0.7.2.0
```

**Comment by nikhilk** [comment]
Are you including the latest mscorlib.js? ss.isValue should be defined in there...

**Comment by joeferner** [comment]
Thanks, that fixed the ss.isValue issue.  But didn't fix...
`if(i==null) {}`

**Comment by james-baker** [comment]
I get the same `Missing compiler required member 'System.Nullable.GetValueOrDefault'` error when trying to write a `i ?? 0`.  What exactly am I missing?

**Comment by nikhilk** [comment]
Fix included in 0.7.4.0
