### ISSUE TITLE
Missing overload on jQuery : Html( JQueryObject)

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#7]
jQuery allows to set html from another jQuery object:

eg.
var _summaryContent = $('&lt;ul id=\'summary-ul\' class=\'error\'&gt;&lt;/ul&gt;');

// loop items
_summaryContent.append('&lt;li&gt;'+ item + '&lt;/li&gt;');
// end loop

$('#divId").html( _summaryContent);

currently Html does not allow to be called with jQuery object

**Comment by nikhilk** [comment]
Should be easy enough to add... until then the ugly workaround is:

$("#divId").Html((string)(object)_summaryContent);

**Comment by rekna1** [comment]
was using the workaround already, thx anyway... just registering to help improve script# ( btw 0.7 is a major improvement !!!)

**Comment by nikhilk** [comment]
Oh, absolutely, by all means do report the issues. Was just pointing out workarounds in case it was blocking.

**Comment by nikhilk** [comment]
Included fix in release 0.7.0.2.

**Comment by rekna1** [comment]
where is download? installer msi on projects.nikhilk.net seems to be version 7.0.0 ?
update: you can ignore this comment, apparently ,mscorlib.dll and other dll's still have version number 7.0.0 which was confusing me. I looked at mscorlib.js which contains version number 7.0.2, so apparently installer is ok.
