### ISSUE TITLE
Compiler in 0.7.2 does not support const decimal

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#70]
The compiler in 0.7.2 will accept const float, int and string, but not decimal.  Instead I get the following error:

Missing compiler required member 'System.Runtime.CompilerServices.DecimalConstantAttribute..ctor'

A work-around is to switch to static readonly decimal.

**Comment by nikhilk** [comment]
The above change should be included in the 0.7.3 release.
