### ISSUE TITLE
mscorlib.js Date.prototype._netFormat does not support quoted string literals

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#71]
In mscorlib.js the 'en-US' culture uses quotes for string literals: gmtDateTimePattern: 'ddd, dd MMM yyyy HH:mm:ss \'GMT\''

Which when formatted with String.LocaleFormat("{0:r}", DateTime.Now) ends up as: Tue, 31 May 2011 14:19:21 'G5T'

Notice the quotes are left in place and the M was converted to a 5 -- the quotes had no effect.

NOTE: Testing this requires fixing issue #69 so String.LocaleFormat is properly defined.

**Comment by nikhilk** [comment]
I'll be fixing this by removing the GMT bit from the pattern ... and instead appending ' GMT' to the string if the format specifier is 'r'.

**Comment by mattclay** [comment]
Unfortunately that doesn't fix the problem for other cultures.  I've exported some .NET cultures already, such as "es-MX" and they have format patterns which won't work without quoted string literals, such as:

dateTimePattern: 'dddd, dd\' de \'MMMM\' de \'yyyy hh:mm:ss tt'

**Comment by nikhilk** [comment]
That's going to require bigger changes in the regex then to skip over quoted literals. Did you make that change as well?

By the way, I noticed that the UTC functionality itself doesn't seem to work...

**Comment by mattclay** [comment]
I haven't made any changes to support quoted string literals yet.

The jquery-global plugin should make a good reference.  If the license is compatible it would be nice to be able to re-use the relevant portions so they don't need to be re-implemented from scratch.

As for the UTC formatting, I haven't tested that since it wasn't functionality I needed.

**Comment by robitar** [comment]
Ran into this myself. Looking at the source for date format, I wonder could you just count the number of ' chars before and after the match. If there's an even count on either side then you are not in a quote, and if there's an odd count you are.

```
a 'b' c 'd'''e
```

a is not quoted, has 6 quotes after
b is quoted, 1 before, 5 after
c is not quoted, 2 before, 4 after
d is quoted, 3, before, 3 after
e is not quoted, has 6 quotes before

Seems to work, and wouldn't require any changes to the matching logic.

**Comment by nikhilk** [comment]
@ecm-mclay - you are using the UTC functionality in your GMT format. It is broken.

@robitar - here is what I did - updated the regex to be:
    /'[^']+'|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z/g
which allows me to match substrings like 'GMT' and handle them appropriately.

Let me know if either of you have thoughts on that.

**Comment by mattclay** [comment]
@nikhilk - I didn't even think about the fact I used UTC in my original example. I just wanted a brief example, so I picked the 'r' format specifier since that used the built-in 'en-US' pattern with the quoted 'GMT'.  I've actually been doing all my testing with the 'F' format specifier and exported patterns from .NET cultures, like 'es-MX'.

I tried your updated regex. It protects the string literals, but also leaves the quotes in the formatted string. Adding the following before the switch statement removes the quotes:

```
    if (fs.startsWith('\'') && fs.endsWith('\'')) {
        part = part.substring(1, part.length - 1);
    }
```

**Comment by nikhilk** [comment]
I didn't list the full fix - just the regex part. The full fix includes a default switch case, which strips out the quotes.

My comment above was primarily to get any input on the regex if either of you had any feedback on it. Looks like it works in cases you have.

**Comment by robitar** [comment]
Makes more sense as it keeps the switch easier to manage, my idea was a bit gimmicky tbh

The only other thing that comes to mind is outputting escaped quotes via \', but without negative lookbehind in javascript regex, it would be awkward to handle with just the pattern. I'm happy enough with that limitation for now.

**Comment by mattclay** [comment]
I've confirmed this is fixed.
