### ISSUE TITLE
Creating Record objects from another library

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#73]
I've found an issue with creating objects that exist in other Script# libraries.

I've recently split out my large ScriptSharp project into smaller projects and am now creating a 'Common' library which is referenced by other projects. One type in particular, "DialogOptions" inherits from Record as I just want a simple object type to pass into an external Api. Specifically, this type maps to the dialog options required by the JQuery UI dialog. 

This type exists in a library called 'Common' and looks like the following:

<pre>   
public sealed class DialogOptions : Record
{
  public bool Disabled;
  public bool AutoOpen;
  public Dictionary Buttons;
  public bool CloseOnEscape;
  public string CloseText;
  public string DialogClass;
  public bool Draggable;
  public int Height;
  public string Hide;
  public int MaxHeight;
  public int MaxWidth;
  public int MinHeight;
  public int MinWidth;
  public bool Modal;
  public bool Resizable;
  public string Show;
  public bool Stack;
  public string Title;
  public int Width;
  [ScriptName("zIndex")] public int ZIndex ;

  public DialogOptions()
  {
    ZIndex    = 1000;
    Resizable   = true;
    AutoOpen    = true;
    CloseOnEscape = true;
    Draggable   = true;
    MinHeight   = 150;
    MaxHeight   = 150;
    Stack     = true;
  }
}
</pre>

This is how the object is created (pretty standard stuff), from a separate project which references Common:

<pre>           
DialogOptions dlgOptions = new DialogOptions();
</pre>

Now, the generated code for DialogOptions is this, as I would expect:

<pre>
Common.$create_DialogOptions = function Common_DialogOptions() {
    var $o = { };
    $o.zIndex = 1000;
    $o.resizable = true;
    $o.autoOpen = true;
    $o.closeOnEscape = true;
    $o.draggable = true;
    $o.minHeight = 150;
    $o.maxHeight = 150;
    $o.stack = true;
    return $o;
}
</pre>

However, the generated construction code is this:

<pre>
var dlgOptions = new Common.DialogOptions();
</pre>

Shouldn't this be `Common.$create_DialogOptions()` in this case? The actual error at runtime is `Uncaught TypeError: undefined is not a function`, and it's because in the generated code there is no such type as Common.DialogOptions.

I've tried not inheriting from Record but then I don't get a simple object map and jQuery UI does not like it. I've tried using Type to access the Prototype object but this again doesn't give me the correct data.

What I have tried is manually changing the generated code to `var dlgOptions = new Common.$create_DialogOptions();`, which works as expected.

At the moment I'm unsure which is the intended behaviour, but I would have expected the generated code to construct the object using `$create_DialogOptions` on a Record type - can you clarify?

**Comment by robitar** [comment]
Have you tried not inheriting from Record and adding [ScriptName("Object")] to the type?

**Comment by stevehobbsdev** [comment]
Thanks for the reply. I've just tried your suggestion and I can already see it won't work from the generated code. I end up with the same situation except that the object being created has a different name; doesn't really have any impact.

**Comment by robitar** [comment]
I think I follow, the compiler probably treats both approaches the same way.

**Comment by heiskanen** [comment]
Hi,

I have this same issue and I "solved" it by creating record like this:
DialogOptions dlgOptions = (DialogOptions)Script.Literal("new Common.$create_DialogOptions()");

Is there a fix for this, I could not find it allthought there is "fix available" label on this issue.

**Comment by nikhilk** [comment]
Fixed in 0.7.3.
