### ISSUE TITLE
Compiler crash in 0.7.2 defining decimal type with non-integer value

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#76]
Defining a decimal type with a non-integer value results in a crash of the compiler.

decimal x = 1.1m;

First you get the "Microsoft Visual Studio 2010 has stopped working" dialog, followed by "The Microsoft (R) Visual C# 2010 Compiler has encountered an internal error." dialog.  Once you click the close program button, the following errors are displayed:

Error   6   Internal Compiler Error (0xc0000005 at address 60ABC303): likely culprit is 'CODEGEN'.

An internal error has occurred in the compiler. To work around this problem, try simplifying or changing the program near the locations listed below. Locations at the top of the list are closer to the point at which the internal error occurred. Errors such as this can be reported to Microsoft by using the /errorreport option.
    ScriptLibrary1
Error   1   Internal Compiler Error: stage 'BEGIN'  ScriptLibrary1
Error   12  Internal Compiler Error: stage 'CODEGEN'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    13  9   ScriptLibrary1
Error   11  Internal Compiler Error: stage 'CODEGEN' symbol 'ScriptLibrary1.Class1.Class1()'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    11  18  ScriptLibrary1
Error   3   Internal Compiler Error: stage 'COMPILE'    ScriptLibrary1
Error   4   Internal Compiler Error: stage 'COMPILE'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    ScriptLibrary1
Error   5   Internal Compiler Error: stage 'COMPILE' symbol '<global namespace>'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    ScriptLibrary1
Error   7   Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    8   11  ScriptLibrary1
Error   8   Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1.Class1' C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    11  18  ScriptLibrary1
Error   9   Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1.Class1.Class1()'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    11  18  ScriptLibrary1
Error   10  Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1.Class1.Class1()'    C:\Users\mclay\AppData\Local\Temporary Projects\ScriptLibrary1\Class1.cs    11  18  ScriptLibrary1
Error   2   Internal Compiler Error: stage 'EMIT'   ScriptLibrary1

**Comment by mattclay** [comment]
Defining a large value for a decimal type has the same effect:

decimal x = 10000000000000000000m;

**Comment by nikhilk** [comment]
The above change should be included in the 0.7.3 release.
