### ISSUE TITLE
vsdoc support

### ISSUE THREAD

**Issue by josche-duplicate** [nikhilk/scriptsharp#79]
Any chance to have the compiler build the vsdoc version for intellisense support with existing javascript? This would be handy for times when we can't currently port existing scripts but need to update them with functionality from new Script# projects

**Comment by nikhilk** [comment]
The compiler already does that - if you have written xml doc-comments in your c# code, and have the c# compiler build the .xml file, the script# msbuild task picks that up and includes vsdoc-style doc-comments into the generated debug script.
