### ISSUE TITLE
Array.Length is not readonly

### ISSUE THREAD

**Issue by Lightw3ight** [nikhilk/scriptsharp#8]
System.Array.Length is currently readonly where in javascript the Length field of the Array object is not readonly, according to w3Schools
"The length property sets or returns the number of elements in an array"

http://www.w3schools.com/jsref/jsref_length_array.asp

**Comment by Lightw3ight** [comment]
Im in the process of refactoring my javascript and had to write the following line:
Type.SetField(SelectedItems, "length", SelectedItems.Length - 1);
instead of:
SelectedItems.Length--;

**Comment by duckmaestro** [comment]
Hmm. Personally I'm on the fence about a change to that. When there are other choices such as ArrayList or now List<>, why not keep the contract of System.Array such that its length is immutable and thus consistent (in that regard) with .NET? I prefer being able to choose between a resizable and non-resizable array in my variable declarations, because I can use it to imply certain things within my code.

**Comment by nikhilk** [comment]
Yes, I am on the same page - I think keeping Length read-only probably reflects the use-case of an array ... and helps catch errors when code doesn't match array semantics. This is the reason there is a distinction between Array and ArrayList/List members.

I also wonder if Length should be settable even on ArrayList/List. I think seeing code that does Adds/Remove/RemoveAt on a List would be more clear, than just setting Length to a number. In your case,
    selectedItems.RemoveAt(selectedItems.Length - 1)
might be more reflective of the intent, no?

Finally as you pointed out in your comment, for exceptional scenarios, Type.SetField allows you to escape the static type system.

**Comment by Lightw3ight** [comment]
Fair call, I wasn't thinking along the lines of "Is it a good thing to do", I just saw that it was possible in javascript
I will eventually re-factor things but at the moment I'm simply trying to port all our javascript into script#, then i can look at refactoring it :)

**Comment by nikhilk** [comment]
Well, sometimes Script.Literal helps if you're porting existing javascript code that you'll refactor/change...
Script.Literal("{0}.Length--", SelectedItems);

Its an escape hatch kind of tool, that I won't recommend extensive usage of, but it exists nonetheless.
