### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by henkosch** [nikhilk/scriptsharp#83]
Hey!

Currently we are using haxe for our javascript project development. We considered using scriptsharp a year ago, but it lacked generics, so we decided for haxe. Now you project seems nice, so we're thinking of porting our project to scriptsharp.

There is one thing we like in haxe very much, it is the serialization feature. Here you can read about it:
http://haxe.org/manual/serialization

It can handle circular references, any classes and most of the basic types. So you can just pick a root object and serialize it into a string with all the type information and all of its references.

Do you have such feature in scriptsharp?
I saw the Json serializer, but that didnt work this way.

Henko

**Comment by robitar** [comment]
Sounds like this would be a good 'contrib' addition, if you fancy porting the Haxe implementation to C#.

**Comment by nikhilk** [comment]
This isn't a compiler feature or a core framework feature - however, you could implement a custom serializer in javascript, and like Rob mentioned, it could probably be written in c# and compiled to javascript using script#.

It would make for a good standalone library for folks who do need to serialize object graphs that contain circular references.
