### ISSUE TITLE
if(<var> is <type>) not compiled properly when <type> is a delegate.

### ISSUE THREAD

**Issue by vgribok** [nikhilk/scriptsharp#84]
Hi!

I have this in C#:

namespace somens
{
    internal delegate object CalcValueDelegate(object entity);
    ...
    void somemethod(objet val)
    {
        if(val is CalcValueDelegate)
            ...

The last line gets compiled to JS as "if (Type.canCast(val, somens._calcValueDelegate))", and _calcValueDelegate is not defined in the JS output file produced by S# compiler, leading to a runtime error.

Vlad.

**Comment by nikhilk** [comment]
Will fix this to generate:

```
if (Type.canCast(val, Function))
```

A delegate is basically a function under the covers.

**Comment by nikhilk** [comment]
The above change should be included in the 0.7.3 release.
