### ISSUE TITLE
Version number on js files

### ISSUE THREAD

**Issue by eNepper** [nikhilk/scriptsharp#85]
I'll like to see a way to add a version number in the file name of the generated js file.

**Comment by nikhilk** [comment]
This would be interesting - there are a few bits that make up the generated js file:
- Build flavor: debug vs. release (and in case of our team here, there is also a perf/instrumented flavor)
- Locale: eg. foo.en.js vs foo.fr.js ... sometimes people want the locale to be reflected as a sub-folder, which btw is a (not documented) property supported by the msbuild task.

I just checked in the sources for the msbuild tasks - these will be in the ScriptSharp.Build assembly in the next release - but the sources are now in, and will allow folks to hopefully contribute at the build workflow level.

More importantly, the script# compiler has a high-level API, allowing you to invoke it as you want - the msbuild task is one consumer of this API.

I think it would be interesting to surface the assembly version as specified in the assembly metadata (as this isn't currently) and surface that for generated script to reference as well as for the msbuild task to use. Will do that...

**Comment by robitar** [comment]
Are you able to elaborate on the instrumented build you are using? Is it a post compilation step to add tracing to function calls etc?

**Comment by nikhilk** [comment]
Its not really something sophisticated, though the request to build in something automatic (eg. auto-logging of all functions called via instrumentation) has come up.

Right now its much more manual - just like Debug.Assert, imagine Instrumentation.Log, which only gets emitted conditionally into an instrumentated build flavor by virtue of a [Conditional("INSTRUMENTATION")] on the API.

**Comment by robitar** [comment]
Makes sense, so its not for profiling each function call etc, but a conditional output more detailed than debug.
