### ISSUE TITLE
isNullOrUndefined is undefined script error when creating a new Exception in Firefox

### ISSUE THREAD

**Issue by jrockwood** [nikhilk/scriptsharp#89]
Hi, Nikhil! I'm back into Script# having convinced our team it's a good thing after years of experience with it on Excel Server in my Microsoft days. I still love it! :)

This only happens on Firefox, but the fix is brain-dead simple. The problem is in Error.prototype.popStackFrame on line 983 in the mscorlib.debug.js for version 0.7.2:

```
var nextFrame = stackFrames[1];
```

-->    if (isNullOrUndefined(nextFrame)) {
        return;
    }

The line pointed to above should be ss.isNullOrUndefined.

**Comment by nikhilk** [comment]
Hi Justin,

This is great to hear and awesome to see you around again!

As for this issue, I'll include the fix in the next build. Thanks for pointing it out.

**Comment by nikhilk** [comment]
The 0.7.3 release is out, and should have the fix.
