### ISSUE TITLE
Build error: Could not load type 'ScriptSharp.IErrorHandler'

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#91]
When trying to build the latest ScriptSharp source I'm receiving the following error during the build process (both in debug and release builds).

------ Build started: Project: CoreScript, Configuration: Release Any CPU ------

  Unhandled Exception: System.TypeLoadException: Could not load type 'ScriptSharp.IErrorHandler' from assembly 'ScriptSharp, Version=0.7.0.0, Culture=neutral, PublicKeyToken=8fc0e3af5abcb6c4'.
C:\Users\mclay\Downloads\nikhilk-scriptsharp-69f97f0\src\Runtime\Client\Core\CoreScript.csproj(38,5): error MSB3073: The command "........\bin\Release\sspp.exe /nologo /debug /d:DEBUG /crlf /input:Loader.js /output:........\bin\Release\Sharpen.Loader.debug.js" exited with code -532462766.

**Comment by nikhilk** [comment]
The ScriptSharp.dll has changed in bin/ref folder, which is what sspp.exe gets built against, but the one in the GAC (the publicly released one) is being used when sspp.exe runs.

Possible solutions:
a) Temporarily GAC the ScriptSharp.dll in bin/ref (the original installed one will be in program files\scriptsharp)
b) Wait for the new msi (hopefully will put it out tonight - I have one more bug fix I'd like to include in the 0.7.3 release)

**Comment by nikhilk** [comment]
Please try again once you've installed the new msi from the 0.7.3 release.

**Comment by mattclay** [comment]
Yes, it's working with the 0.7.3 release.
