### ISSUE TITLE
Regression in 0.7.3 compiler handling of inline constants in debug output

### ISSUE THREAD

**Issue by mattclay** [nikhilk/scriptsharp#92]
The compiler in 0.7.3 emits constants differently in debug output than was done in 0.7.2.  Release output is unchanged.

In 0.7.3 the constant member is included on the class, but the value is inline where used, the member is never referenced.
In 0.7.2 the constant member is included on the class, a member reference is used rather than an inline value.

I suspect one of the following was actually intended:
- The member should not be emitted, causing debug and release output to be the same.
- The member should be referenced rather than placing the value inline.

**Comment by nikhilk** [comment]
Fixed in 0.7.4.0 - debug and release outputs exhibit same behavior now ... internal const is not generated as its value has been inlined.
