### ISSUE TITLE
Error compiling cross-referenced projects in 0.7.3

### ISSUE THREAD

**Issue by stevehobbsdev** [nikhilk/scriptsharp#93]
We've come across this issue today while compiling a coluton containing 16 Script# projects. This is the simplified issue:
- ProjectA is a project containing common code, and is referenced by ProjectB.
- ProjectA contains a reference to Script.Knockout, but ProjectB does not.
- ProjectA contains a class which references some types from Script.Knockout.

Given this hierarchy, ProjectA compiles fine whereas ProjectB will fail, and will produce no errors in the error log. If I exclude the code from ProjectA (or remove the reference to Script.Knockout) which use types from Script.Knockout, both projects compile.

I can see how the issue makes sense - normally (correct me if I'm wrong) in C# if I reference a library which has a further dependency which I haven't included myself, then I am asked to include that reference myself. However, I am only normally asked to do this if I have used some code which requires that reference - simply the act of making the reference without then using any types from it shouldn't cause this issue. 

In my example above, ProjectB doesn't use any types from ProjectA which require the reference to Script.Knockout. Normally that would mean I wouldn't require the reference to Script.Knockout in ProjectB (which was the case in 0.7.2).

It should be noted that this issue probably doesn't occur specifically with Script.Knockout - I would imagine that any projects configured as above with any reference might exhibit this issue.

If this is the expected behaviour, I can live with that. At the very least though there should be an error message produced which explains the issue.

**Comment by stevehobbsdev** [comment]
If it's any use, I have a bare-bones solution file with two projects which demonstrates the issue; I found I was able to recreate the problem pretty easily.

http://dl.dropbox.com/u/5229980/Code/ScriptSharp%20Library%20Ref%20Issue.zip

**Comment by nikhilk** [comment]
Out of curiosity, can you add [CLSCompliant(true)] to the projects and see if that changes things where the c# compiler adds an error when ProjectB is compiled without the reference to Knockout?

**Comment by stevehobbsdev** [comment]
I've tried your suggestion, but I'm afraid it hasn't changed anything in terms of error output or ability to successfully build.

**Comment by mattclay** [comment]
I don't know if this helps or not, but your sample solution fails to compile under 0.7.2 as well.

Adding a reference to Script.Knockout in ProjectB fixes the issue.

**Comment by stevehobbsdev** [comment]
That is most odd. The reason I reported it was because this error only started occurring after we had upgraded to 0.7.3.. immediately after upgrading I recompiled our project (without any changes) and this issue arose. I had just naturally assumed there was a change between builds that had caused this to surface in our case.

**Comment by nikhilk** [comment]
FIx included in 0.7.4.0 - require transitive closure of assemblies to be specified ... otherwise error is reported instead of silent failure.
