### ISSUE TITLE
Type.CreateInstance(Type.GetType('Foo')) returns null.

### ISSUE THREAD

**Issue by aronmek** [nikhilk/scriptsharp#94]
Type.CreateInstance(Type.GetType('Foo')) compiles as 

<pre>
new Type.getType('Foo')();
</pre>

There is some limitation in javascript that you can't call new on a returnvalue of a function in one line, The way it has to be is like this.

<pre>
var type = Type.getType('Foo');
var instance = new type();
</pre>

**Comment by nikhilk** [comment]
Uggh... such is JavaScript I suppose.

Breaking a single statement into multiple is a bit complex - as it requires introduction of temporaries as at least one bit of complexity. Might have to introduce a wrapper function that is like a generic factory, and then try optimize the case where the wrapper is not needed, i.e. when you have a type variable reference, as opposed to some other arbitrary expression.

**Comment by mattclay** [comment]
Wrapping the function call in parenthesis works:

new (Type.getType('Foo'))();

**Comment by nikhilk** [comment]
Good to know - that would be a better workaround to generate.

It seems to be only required when the type is a result of a function call - is that accurate? For example, when I tried doing a member access (like window['Foo'] it didn't require to be split across lines).

**Comment by aronmek** [comment]
Yes, I encountered this problem only when calling the "new" operator on a return value of a function call.

**Comment by nikhilk** [comment]
FIx included in 0.7.4.0.
