### ISSUE TITLE
Compilation failure without warnings/errors

### ISSUE THREAD

**Issue by ghost** [nikhilk/scriptsharp#95]
I created a project where I'm trying to create a View Model for a KnockoutJs application. I'm trying to do a simple Dependency Injection for testability. I created a Script Library project. The following code causes a compilation failure with 0.7.3 - no warnings and no errors generated:

```
namespace SSTest
{
    public interface IObservable<T>
    {
        T Value
        {
            get;
            set;
        }
    }

    //[IgnoreNamespace]
    //[Imported]
    public class KoObservable<T> : IObservable<T>
    {
        private T theValue;

        public KoObservable(T value)
        {
            theValue = value;
        }

        public T Value
        {
            get { return GetValue(); }
            set { SetValue(value); }
        }

        //[ScriptName("")]
        public T GetValue()
        {
            return theValue;
        }

        //[ScriptName("")]
        public void SetValue(T value)
        {
            theValue = value;
        }
    }

    public class ItemViewModel
    {
        private int id;
        private IObservable<string> name;

        public ItemViewModel(int taskId)
        {
            id = taskId;
            //Name = ...
        }

        public IObservable<string> Name
        {
            get { return name; }
            set { name = value; }
        }
    }
}
```

**Comment by robitar** [comment]
You should be using the bindings for Knockout included in the latest version. I think the compiler is failing because you are defining generic types and properties, you can only consume generics in 'script' code.

**Comment by nikhilk** [comment]
Yes, generic types can only be used, and not declared.

The Knockout assembly that Rob is referring to (and helped with) has all the necessary bindings for working with Knockout. It is not compiled via the script# compiler (only the c# compiler) and can therefore declare generic types (that you can subsequently use in your project).
