### ISSUE TITLE
Compiler unsupported feature

### ISSUE THREAD

**Issue by jimmygilles** [nikhilk/scriptsharp#96]
Hello,

The compiler doesn't compile on this line.
double l1 = ((+0.5) - zCam) \* 2;

If I remove the + (plus) sign, it compiles.
double l1 = ((0.5) - zCam) \* 2;

**Comment by robitar** [comment]
Yea I ran into this as well trying to negate a number, I believe it wouldn't take 'x \* -1'

**Comment by nikhilk** [comment]
Couldn't repro the negation unary operator... but fixing the issue with + unary operator.
Interesting how handled/unhandled scenarios reflect one's own authoring patterns. :-)

**Comment by nikhilk** [comment]
FIx included in 0.7.4.0
